//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace EDDY.IS.MatchingEngine.DTO
{
    [DataContract]
    public partial class VW_Matching_SoftRockReservationLeadCountsDTO
    {
        [DataMember]
        public int ClientRelationProductMappingId { get; set; }
        [DataMember]
        public Nullable<int> ClientRelationshipId { get; set; }
        [DataMember]
        public string Name { get; set; }
        [DataMember]
        public Nullable<int> Percentage { get; set; }
        [DataMember]
        public int DaysLeads { get; set; }
        [DataMember]
        public int MonthsLeads { get; set; }
        [DataMember]
        public decimal MonthCap { get; set; }
        [DataMember]
        public Nullable<decimal> DayCap { get; set; }
    }
    
}
