//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Test.MatchingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.Core.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EDDY.IS.MatchingEngine.DTO.BaseMatchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EDDY.IS.MatchingEngine.DTO.CrossSellMatchRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ISApplication", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.Core")]
    public enum ISApplication : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eLDrupal = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EMDDrupal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExpressDirectories = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FormsEngine = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MatchingEngine = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorAPI = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HostAndPost = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PixelService = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Apollo = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TDC = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CE = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SC = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LandingPages = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProspectService = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tracking = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LeadService = 16,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchingService.IMatchingService")]
    public interface IMatchingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetFormPrograms", ReplyAction="http://tempuri.org/IMatchingService/GetFormProgramsResponse")]
        EDDY.IS.MatchingEngine.DTO.FormProgramResponse GetFormPrograms(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetFormPrograms", ReplyAction="http://tempuri.org/IMatchingService/GetFormProgramsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.FormProgramResponse> GetFormProgramsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetInstitutions", ReplyAction="http://tempuri.org/IMatchingService/GetInstitutionsResponse")]
        EDDY.IS.MatchingEngine.DTO.InstitutionResponse GetInstitutions(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeCampus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetInstitutions", ReplyAction="http://tempuri.org/IMatchingService/GetInstitutionsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.InstitutionResponse> GetInstitutionsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeCampus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetCampuses", ReplyAction="http://tempuri.org/IMatchingService/GetCampusesResponse")]
        EDDY.IS.MatchingEngine.DTO.CampusResponse GetCampuses(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetCampuses", ReplyAction="http://tempuri.org/IMatchingService/GetCampusesResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CampusResponse> GetCampusesAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetPrograms", ReplyAction="http://tempuri.org/IMatchingService/GetProgramsResponse")]
        EDDY.IS.MatchingEngine.DTO.ProgramResponse GetPrograms(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeProgramDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetPrograms", ReplyAction="http://tempuri.org/IMatchingService/GetProgramsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramResponse> GetProgramsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeProgramDetail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetCategories", ReplyAction="http://tempuri.org/IMatchingService/GetCategoriesResponse")]
        EDDY.IS.MatchingEngine.DTO.CategoryResponse GetCategories(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetCategories", ReplyAction="http://tempuri.org/IMatchingService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CategoryResponse> GetCategoriesAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetSubjects", ReplyAction="http://tempuri.org/IMatchingService/GetSubjectsResponse")]
        EDDY.IS.MatchingEngine.DTO.SubjectResponse GetSubjects(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetSubjects", ReplyAction="http://tempuri.org/IMatchingService/GetSubjectsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.SubjectResponse> GetSubjectsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramLevels", ReplyAction="http://tempuri.org/IMatchingService/GetProgramLevelsResponse")]
        EDDY.IS.MatchingEngine.DTO.ProgramLevelResponse GetProgramLevels(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramLevels", ReplyAction="http://tempuri.org/IMatchingService/GetProgramLevelsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramLevelResponse> GetProgramLevelsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramsForCrossSell", ReplyAction="http://tempuri.org/IMatchingService/GetProgramsForCrossSellResponse")]
        EDDY.IS.MatchingEngine.DTO.CrossSellProgramResponse GetProgramsForCrossSell(EDDY.IS.MatchingEngine.DTO.CrossSellMatchRequest crossSellRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramsForCrossSell", ReplyAction="http://tempuri.org/IMatchingService/GetProgramsForCrossSellResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CrossSellProgramResponse> GetProgramsForCrossSellAsync(EDDY.IS.MatchingEngine.DTO.CrossSellMatchRequest crossSellRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetInstitutionDetails", ReplyAction="http://tempuri.org/IMatchingService/GetInstitutionDetailsResponse")]
        EDDY.IS.MatchingEngine.DTO.InstitutionDetailResponse GetInstitutionDetails(int applicationId, int institutionId, System.Guid TrackGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetInstitutionDetails", ReplyAction="http://tempuri.org/IMatchingService/GetInstitutionDetailsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.InstitutionDetailResponse> GetInstitutionDetailsAsync(int applicationId, int institutionId, System.Guid TrackGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramDetails", ReplyAction="http://tempuri.org/IMatchingService/GetProgramDetailsResponse")]
        EDDY.IS.MatchingEngine.DTO.ProgramDetailResponse GetProgramDetails(int applicationId, int programId, System.Guid TrackGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/GetProgramDetails", ReplyAction="http://tempuri.org/IMatchingService/GetProgramDetailsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramDetailResponse> GetProgramDetailsAsync(int applicationId, int programId, System.Guid TrackGuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/ValidateProgram", ReplyAction="http://tempuri.org/IMatchingService/ValidateProgramResponse")]
        EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse ValidateProgram(EDDY.IS.MatchingEngine.DTO.ProgramValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/ValidateProgram", ReplyAction="http://tempuri.org/IMatchingService/ValidateProgramResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse> ValidateProgramAsync(EDDY.IS.MatchingEngine.DTO.ProgramValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/ValidateCountryAndProgram", ReplyAction="http://tempuri.org/IMatchingService/ValidateCountryAndProgramResponse")]
        EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse ValidateCountryAndProgram(EDDY.IS.MatchingEngine.DTO.CountryValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/ValidateCountryAndProgram", ReplyAction="http://tempuri.org/IMatchingService/ValidateCountryAndProgramResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse> ValidateCountryAndProgramAsync(EDDY.IS.MatchingEngine.DTO.CountryValidateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/RefreshCacheItem", ReplyAction="http://tempuri.org/IMatchingService/RefreshCacheItemResponse")]
        void RefreshCacheItem(EDDY.IS.MatchingEngine.MatchingCacheItem key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/RefreshCacheItem", ReplyAction="http://tempuri.org/IMatchingService/RefreshCacheItemResponse")]
        System.Threading.Tasks.Task RefreshCacheItemAsync(EDDY.IS.MatchingEngine.MatchingCacheItem key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/RemoveCacheItem", ReplyAction="http://tempuri.org/IMatchingService/RemoveCacheItemResponse")]
        void RemoveCacheItem(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchingService/RemoveCacheItem", ReplyAction="http://tempuri.org/IMatchingService/RemoveCacheItemResponse")]
        System.Threading.Tasks.Task RemoveCacheItemAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchingServiceChannel : EDDY.IS.MatchingEngine.Test.MatchingService.IMatchingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchingServiceClient : System.ServiceModel.ClientBase<EDDY.IS.MatchingEngine.Test.MatchingService.IMatchingService>, EDDY.IS.MatchingEngine.Test.MatchingService.IMatchingService {
        
        public MatchingServiceClient() {
        }
        
        public MatchingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDDY.IS.MatchingEngine.DTO.FormProgramResponse GetFormPrograms(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetFormPrograms(directoryMatchRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.FormProgramResponse> GetFormProgramsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetFormProgramsAsync(directoryMatchRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.InstitutionResponse GetInstitutions(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeCampus) {
            return base.Channel.GetInstitutions(directoryMatchRequest, includeCampus);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.InstitutionResponse> GetInstitutionsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeCampus) {
            return base.Channel.GetInstitutionsAsync(directoryMatchRequest, includeCampus);
        }
        
        public EDDY.IS.MatchingEngine.DTO.CampusResponse GetCampuses(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetCampuses(directoryMatchRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CampusResponse> GetCampusesAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetCampusesAsync(directoryMatchRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.ProgramResponse GetPrograms(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeProgramDetail) {
            return base.Channel.GetPrograms(directoryMatchRequest, includeProgramDetail);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramResponse> GetProgramsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest, bool includeProgramDetail) {
            return base.Channel.GetProgramsAsync(directoryMatchRequest, includeProgramDetail);
        }
        
        public EDDY.IS.MatchingEngine.DTO.CategoryResponse GetCategories(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetCategories(directoryMatchRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CategoryResponse> GetCategoriesAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetCategoriesAsync(directoryMatchRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.SubjectResponse GetSubjects(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetSubjects(directoryMatchRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.SubjectResponse> GetSubjectsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetSubjectsAsync(directoryMatchRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.ProgramLevelResponse GetProgramLevels(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetProgramLevels(directoryMatchRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramLevelResponse> GetProgramLevelsAsync(EDDY.IS.MatchingEngine.DTO.DirectoryMatchRequest directoryMatchRequest) {
            return base.Channel.GetProgramLevelsAsync(directoryMatchRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.CrossSellProgramResponse GetProgramsForCrossSell(EDDY.IS.MatchingEngine.DTO.CrossSellMatchRequest crossSellRequest) {
            return base.Channel.GetProgramsForCrossSell(crossSellRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.CrossSellProgramResponse> GetProgramsForCrossSellAsync(EDDY.IS.MatchingEngine.DTO.CrossSellMatchRequest crossSellRequest) {
            return base.Channel.GetProgramsForCrossSellAsync(crossSellRequest);
        }
        
        public EDDY.IS.MatchingEngine.DTO.InstitutionDetailResponse GetInstitutionDetails(int applicationId, int institutionId, System.Guid TrackGuid) {
            return base.Channel.GetInstitutionDetails(applicationId, institutionId, TrackGuid);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.InstitutionDetailResponse> GetInstitutionDetailsAsync(int applicationId, int institutionId, System.Guid TrackGuid) {
            return base.Channel.GetInstitutionDetailsAsync(applicationId, institutionId, TrackGuid);
        }
        
        public EDDY.IS.MatchingEngine.DTO.ProgramDetailResponse GetProgramDetails(int applicationId, int programId, System.Guid TrackGuid) {
            return base.Channel.GetProgramDetails(applicationId, programId, TrackGuid);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramDetailResponse> GetProgramDetailsAsync(int applicationId, int programId, System.Guid TrackGuid) {
            return base.Channel.GetProgramDetailsAsync(applicationId, programId, TrackGuid);
        }
        
        public EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse ValidateProgram(EDDY.IS.MatchingEngine.DTO.ProgramValidateRequest request) {
            return base.Channel.ValidateProgram(request);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse> ValidateProgramAsync(EDDY.IS.MatchingEngine.DTO.ProgramValidateRequest request) {
            return base.Channel.ValidateProgramAsync(request);
        }
        
        public EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse ValidateCountryAndProgram(EDDY.IS.MatchingEngine.DTO.CountryValidateRequest request) {
            return base.Channel.ValidateCountryAndProgram(request);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.DTO.ProgramValidateResponse> ValidateCountryAndProgramAsync(EDDY.IS.MatchingEngine.DTO.CountryValidateRequest request) {
            return base.Channel.ValidateCountryAndProgramAsync(request);
        }
        
        public void RefreshCacheItem(EDDY.IS.MatchingEngine.MatchingCacheItem key) {
            base.Channel.RefreshCacheItem(key);
        }
        
        public System.Threading.Tasks.Task RefreshCacheItemAsync(EDDY.IS.MatchingEngine.MatchingCacheItem key) {
            return base.Channel.RefreshCacheItemAsync(key);
        }
        
        public void RemoveCacheItem(string key) {
            base.Channel.RemoveCacheItem(key);
        }
        
        public System.Threading.Tasks.Task RemoveCacheItemAsync(string key) {
            return base.Channel.RemoveCacheItemAsync(key);
        }
    }
}
