//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseSearchKVData
    {
        public long MatchResponseSearchKVDataId { get; set; }
        public long MatchResponseSearchId { get; set; }
        public string Key { get; set; }
        public int KVCodeDataId { get; set; }
    
        public virtual MatchResponseSearch MatchResponseSearch { get; set; }
    }
}
