//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatchLoggingModelContainer : DbContext
    {
        public MatchLoggingModelContainer()
            : base("name=MatchLoggingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MatchResponseDisplayed> MatchResponseDisplayeds { get; set; }
        public virtual DbSet<MatchResponseDisplayedFactorScore> MatchResponseDisplayedFactorScores { get; set; }
        public virtual DbSet<MatchResponseFactorAggregate> MatchResponseFactorAggregates { get; set; }
        public virtual DbSet<MatchResponseAvailableProgram> MatchResponseAvailablePrograms { get; set; }
        public virtual DbSet<MatchResponseAvailableProgramFactorScore> MatchResponseAvailableProgramFactorScores { get; set; }
        public virtual DbSet<MatchResponseRemovalReasonJson> MatchResponseRemovalReasonJsons { get; set; }
        public virtual DbSet<MatchResponseRemovalReason> MatchResponseRemovalReasons { get; set; }
        public virtual DbSet<MatchResponseFactorAggregateValue> MatchResponseFactorAggregateValues { get; set; }
        public virtual DbSet<MatchResponse> MatchResponses { get; set; }
        public virtual DbSet<MatchResponseSearch> MatchResponseSearches { get; set; }
        public virtual DbSet<MatchResponseSearchRemoval> MatchResponseSearchRemovals { get; set; }
        public virtual DbSet<MatchResponseSearchResult> MatchResponseSearchResults { get; set; }
        public virtual DbSet<MatchResponseSearchKVData> MatchResponseSearchKVDatas { get; set; }
    }
}
