//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseAvailableProgramFactorScore
    {
        public int MatchResponseAvailableProgramFactorScoreId { get; set; }
        public int MatchResponseAvailableProgramId { get; set; }
        public int BusinessModelFactorId { get; set; }
        public decimal FactorScore { get; set; }
        public Nullable<decimal> FactorValue { get; set; }
    
        public virtual MatchResponseAvailableProgram MatchResponseAvailableProgram { get; set; }
    }
}
