//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseRemovalReason
    {
        public int MatchResponseRemovalReasonId { get; set; }
        public long MatchResponseId { get; set; }
        public int ProgramProductId { get; set; }
        public int EntityMetaId { get; set; }
        public Nullable<int> RuleEntityId { get; set; }
        public int RuleTypeId { get; set; }
        public string RuleDetail { get; set; }
    
        public virtual MatchResponse MatchResponse { get; set; }
    }
}
