//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseSearchRemoval
    {
        public long MatchResponseSearchRemovalId { get; set; }
        public long MatchResponseSearchId { get; set; }
        public Nullable<int> ClientRelationshipId { get; set; }
        public Nullable<int> ClientRelationProductMappingId { get; set; }
        public Nullable<int> PsiId { get; set; }
        public Nullable<int> ProgramProductId { get; set; }
        public string RuleName { get; set; }
        public int RuleId { get; set; }
        public string BaseRuleType { get; set; }
        public int InstitutionId { get; set; }
        public Nullable<int> ClientCampusProductMappingId { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        public virtual MatchResponseSearch MatchResponseSearch { get; set; }
    }
}
