//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseDisplayed
    {
        public MatchResponseDisplayed()
        {
            this.ChildMatchResponseDisplayed = new HashSet<MatchResponseDisplayed>();
            this.MatchResponseDisplayedFactorScores = new HashSet<MatchResponseDisplayedFactorScore>();
        }
    
        public int MatchResponseDisplayedId { get; set; }
        public long MatchResponseId { get; set; }
        public int EntityId { get; set; }
        public int EntityMetaId { get; set; }
        public decimal SRAScore { get; set; }
        public int CollectionIndex { get; set; }
        public Nullable<int> ParentMatchResponseDisplayedId { get; set; }
        public Nullable<int> MatchResponseTypeId { get; set; }
    
        public virtual ICollection<MatchResponseDisplayed> ChildMatchResponseDisplayed { get; set; }
        public virtual MatchResponseDisplayed ParentMatchResponseDisplayed { get; set; }
        public virtual ICollection<MatchResponseDisplayedFactorScore> MatchResponseDisplayedFactorScores { get; set; }
        public virtual MatchResponse MatchResponse { get; set; }
    }
}
