//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseSearch
    {
        public MatchResponseSearch()
        {
            this.MatchResponseSearchResults = new HashSet<MatchResponseSearchResult>();
            this.MatchResponseSearchRemovals = new HashSet<MatchResponseSearchRemoval>();
            this.MatchResponseSearchKVDatas = new HashSet<MatchResponseSearchKVData>();
        }
    
        public long MatchResponseSearchId { get; set; }
        public long MatchResponseId { get; set; }
        public System.Guid TrackId { get; set; }
        public string CallingApplication { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public string DialerKey { get; set; }
        public string TSR { get; set; }
        public Nullable<int> LeadCreationTypeId { get; set; }
        public Nullable<int> CampusTypeId { get; set; }
        public Nullable<bool> HasComputer { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public string Email { get; set; }
        public string ExternalLeadId { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> HSGraduationYear { get; set; }
        public Nullable<bool> IsCitzen { get; set; }
        public Nullable<bool> IsMilitary { get; set; }
        public Nullable<int> MilitaryStatusId { get; set; }
        public string LastName { get; set; }
        public string Phone1 { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> StateId { get; set; }
        public string StreetAddress { get; set; }
        public string CategoryList { get; set; }
        public string SubjectList { get; set; }
        public string SpecialtyList { get; set; }
        public string SmartMatchedInstitutionList { get; set; }
        public int ReturnedSchools { get; set; }
        public int AvailableSchools { get; set; }
        public int RemovedSchools { get; set; }
    
        public virtual MatchResponse MatchResponse { get; set; }
        public virtual ICollection<MatchResponseSearchResult> MatchResponseSearchResults { get; set; }
        public virtual ICollection<MatchResponseSearchRemoval> MatchResponseSearchRemovals { get; set; }
        public virtual ICollection<MatchResponseSearchKVData> MatchResponseSearchKVDatas { get; set; }
    }
}
