//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseFactorAggregate
    {
        public MatchResponseFactorAggregate()
        {
            this.MatchResponseFactorAggregateValues = new HashSet<MatchResponseFactorAggregateValue>();
        }
    
        public int MatchResponseFactorAggregateId { get; set; }
        public long MatchResponseId { get; set; }
        public int BusinessModelFactorId { get; set; }
        public int MatchResponseFactorAggregateTypeId { get; set; }
        public Nullable<decimal> AggregateValue { get; set; }
        public Nullable<int> ProgramProductId { get; set; }
    
        public virtual ICollection<MatchResponseFactorAggregateValue> MatchResponseFactorAggregateValues { get; set; }
        public virtual MatchResponse MatchResponse { get; set; }
    }
}
