//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseFactorAggregateValue
    {
        public int MatchResponseFactorAggregateValueId { get; set; }
        public int MatchResponseFactorAggregateId { get; set; }
        public int BusinessModelFactorId { get; set; }
        public Nullable<decimal> AggregateValue { get; set; }
    
        public virtual MatchResponseFactorAggregate MatchResponseFactorAggregate { get; set; }
    }
}
