//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.Logging.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchResponseAvailableProgram
    {
        public MatchResponseAvailableProgram()
        {
            this.MatchResponseAvailableProgramFactorScores = new HashSet<MatchResponseAvailableProgramFactorScore>();
        }
    
        public int MatchResponseAvailableProgramId { get; set; }
        public long MatchResponseId { get; set; }
        public int ProgramProductId { get; set; }
        public decimal SRAScore { get; set; }
        public int CollectionIndex { get; set; }
        public Nullable<int> MatchResponseTypeId { get; set; }
    
        public virtual ICollection<MatchResponseAvailableProgramFactorScore> MatchResponseAvailableProgramFactorScores { get; set; }
        public virtual MatchResponse MatchResponse { get; set; }
    }
}
