//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.SEOAllocation.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSAllocationDetail
    {
        public int GSAllocationDetailId { get; set; }
        public int GSAllocationMasterId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int ProgramId { get; set; }
        public int ProgramLevelId { get; set; }
        public int ProgramProductId { get; set; }
        public int ProgramCampusTypeId { get; set; }
        public int InstitutionId { get; set; }
        public int ClickLeadProgramTypeId { get; set; }
        public int PaidStatusTypeId { get; set; }
        public decimal RPL { get; set; }
        public decimal ClickPrice { get; set; }
    
        public virtual GSAllocationMaster GSAllocationMaster { get; set; }
    }
}
