//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.SEOAllocation.Console.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSAllocationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GSAllocationMaster()
        {
            this.GSAllocationDetails = new HashSet<GSAllocationDetail>();
        }
    
        public int GSAllocationMasterId { get; set; }
        public int NodeId { get; set; }
        public string URL { get; set; }
        public System.DateTime RunTime { get; set; }
        public int ProgramCount { get; set; }
        public int InstitutionCount { get; set; }
        public int PaidClickProgramCount { get; set; }
        public int PaidLeadProgramCount { get; set; }
        public int PaidClickLeadProgramCount { get; set; }
        public int FreeProgramCount { get; set; }
        public int PaidProgramCount { get; set; }
        public int FraidProgramCount { get; set; }
        public decimal RPLSum { get; set; }
        public decimal ClickPriceSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GSAllocationDetail> GSAllocationDetails { get; set; }
    }
}
