//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.SEOAllocation.Console.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GSAllocationContextContainer : DbContext
    {
        public GSAllocationContextContainer()
            : base("name=GSAllocationContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GSAllocationDetail> GSAllocationDetails { get; set; }
        public virtual DbSet<GSAllocationMaster> GSAllocationMasters { get; set; }
    }
}
