//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.MatchingEngine.LeadPingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationRequest", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ValidationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.InstitutionConfig[] InsitutionConfigsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.ProspectInfo ProspectInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.InstitutionConfig[] InsitutionConfigs {
            get {
                return this.InsitutionConfigsField;
            }
            set {
                if ((object.ReferenceEquals(this.InsitutionConfigsField, value) != true)) {
                    this.InsitutionConfigsField = value;
                    this.RaisePropertyChanged("InsitutionConfigs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.ProspectInfo ProspectInfo {
            get {
                return this.ProspectInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProspectInfoField, value) != true)) {
                    this.ProspectInfoField = value;
                    this.RaisePropertyChanged("ProspectInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectInfo", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ProspectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallCenterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignCECLeadScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CampaignTrackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DesiredStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationLevelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalLeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormLeadUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighSchoolGradyearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitiatingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeadCreationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MilitaryAffiliationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MilitaryStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSource1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubSource2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionFormUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionLeadInitiatingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionLeadSourceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingSessionGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AffiliateId {
            get {
                return this.AffiliateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliateIdField, value) != true)) {
                    this.AffiliateIdField = value;
                    this.RaisePropertyChanged("AffiliateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallCenterUrl {
            get {
                return this.CallCenterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallCenterUrlField, value) != true)) {
                    this.CallCenterUrlField = value;
                    this.RaisePropertyChanged("CallCenterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignCECLeadScore {
            get {
                return this.CampaignCECLeadScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignCECLeadScoreField, value) != true)) {
                    this.CampaignCECLeadScoreField = value;
                    this.RaisePropertyChanged("CampaignCECLeadScore");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CampaignTrackId {
            get {
                return this.CampaignTrackIdField;
            }
            set {
                if ((this.CampaignTrackIdField.Equals(value) != true)) {
                    this.CampaignTrackIdField = value;
                    this.RaisePropertyChanged("CampaignTrackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DesiredStartDate {
            get {
                return this.DesiredStartDateField;
            }
            set {
                if ((this.DesiredStartDateField.Equals(value) != true)) {
                    this.DesiredStartDateField = value;
                    this.RaisePropertyChanged("DesiredStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationLevelID {
            get {
                return this.EducationLevelIDField;
            }
            set {
                if ((this.EducationLevelIDField.Equals(value) != true)) {
                    this.EducationLevelIDField = value;
                    this.RaisePropertyChanged("EducationLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalLeadId {
            get {
                return this.ExternalLeadIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalLeadIdField, value) != true)) {
                    this.ExternalLeadIdField = value;
                    this.RaisePropertyChanged("ExternalLeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormLeadUrl {
            get {
                return this.FormLeadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.FormLeadUrlField, value) != true)) {
                    this.FormLeadUrlField = value;
                    this.RaisePropertyChanged("FormLeadUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HighSchoolGradyear {
            get {
                return this.HighSchoolGradyearField;
            }
            set {
                if ((this.HighSchoolGradyearField.Equals(value) != true)) {
                    this.HighSchoolGradyearField = value;
                    this.RaisePropertyChanged("HighSchoolGradyear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiatingUrl {
            get {
                return this.InitiatingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiatingUrlField, value) != true)) {
                    this.InitiatingUrlField = value;
                    this.RaisePropertyChanged("InitiatingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LandingUrl {
            get {
                return this.LandingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LandingUrlField, value) != true)) {
                    this.LandingUrlField = value;
                    this.RaisePropertyChanged("LandingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeadCreationTypeId {
            get {
                return this.LeadCreationTypeIdField;
            }
            set {
                if ((this.LeadCreationTypeIdField.Equals(value) != true)) {
                    this.LeadCreationTypeIdField = value;
                    this.RaisePropertyChanged("LeadCreationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MilitaryAffiliation {
            get {
                return this.MilitaryAffiliationField;
            }
            set {
                if ((this.MilitaryAffiliationField.Equals(value) != true)) {
                    this.MilitaryAffiliationField = value;
                    this.RaisePropertyChanged("MilitaryAffiliation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MilitaryStatusId {
            get {
                return this.MilitaryStatusIdField;
            }
            set {
                if ((this.MilitaryStatusIdField.Equals(value) != true)) {
                    this.MilitaryStatusIdField = value;
                    this.RaisePropertyChanged("MilitaryStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSource1 {
            get {
                return this.SubSource1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubSource1Field, value) != true)) {
                    this.SubSource1Field = value;
                    this.RaisePropertyChanged("SubSource1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubSource2 {
            get {
                return this.SubSource2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SubSource2Field, value) != true)) {
                    this.SubSource2Field = value;
                    this.RaisePropertyChanged("SubSource2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionFormUrl {
            get {
                return this.SubmissionFormUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionFormUrlField, value) != true)) {
                    this.SubmissionFormUrlField = value;
                    this.RaisePropertyChanged("SubmissionFormUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionLeadInitiatingUrl {
            get {
                return this.SubmissionLeadInitiatingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionLeadInitiatingUrlField, value) != true)) {
                    this.SubmissionLeadInitiatingUrlField = value;
                    this.RaisePropertyChanged("SubmissionLeadInitiatingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionLeadSourceUrl {
            get {
                return this.SubmissionLeadSourceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionLeadSourceUrlField, value) != true)) {
                    this.SubmissionLeadSourceUrlField = value;
                    this.RaisePropertyChanged("SubmissionLeadSourceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingSessionGUID {
            get {
                return this.TrackingSessionGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingSessionGUIDField, value) != true)) {
                    this.TrackingSessionGUIDField = value;
                    this.RaisePropertyChanged("TrackingSessionGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoUrl {
            get {
                return this.VideoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoUrlField, value) != true)) {
                    this.VideoUrlField = value;
                    this.RaisePropertyChanged("VideoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstitutionConfig", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class InstitutionConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BachelorsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.CampusConfig[] CampusConfigsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientrelationshipIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BachelorsAvailable {
            get {
                return this.BachelorsAvailableField;
            }
            set {
                if ((this.BachelorsAvailableField.Equals(value) != true)) {
                    this.BachelorsAvailableField = value;
                    this.RaisePropertyChanged("BachelorsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.CampusConfig[] CampusConfigs {
            get {
                return this.CampusConfigsField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusConfigsField, value) != true)) {
                    this.CampusConfigsField = value;
                    this.RaisePropertyChanged("CampusConfigs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientrelationshipID {
            get {
                return this.ClientrelationshipIDField;
            }
            set {
                if ((this.ClientrelationshipIDField.Equals(value) != true)) {
                    this.ClientrelationshipIDField = value;
                    this.RaisePropertyChanged("ClientrelationshipID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampusConfig", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class CampusConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MilesFromUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampusID {
            get {
                return this.CampusIDField;
            }
            set {
                if ((this.CampusIDField.Equals(value) != true)) {
                    this.CampusIDField = value;
                    this.RaisePropertyChanged("CampusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MilesFromUser {
            get {
                return this.MilesFromUserField;
            }
            set {
                if ((this.MilesFromUserField.Equals(value) != true)) {
                    this.MilesFromUserField = value;
                    this.RaisePropertyChanged("MilesFromUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ValidationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.FailedInstitutionResponse[] ImmediateResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.FailedInstitutionResponse[] RelatedResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.ScoreInstitutionResponse[] ScoreResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.ServiceCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.FailedInstitutionResponse[] ImmediateResponses {
            get {
                return this.ImmediateResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmediateResponsesField, value) != true)) {
                    this.ImmediateResponsesField = value;
                    this.RaisePropertyChanged("ImmediateResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.FailedInstitutionResponse[] RelatedResponses {
            get {
                return this.RelatedResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedResponsesField, value) != true)) {
                    this.RelatedResponsesField = value;
                    this.RaisePropertyChanged("RelatedResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.ScoreInstitutionResponse[] ScoreResponses {
            get {
                return this.ScoreResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreResponsesField, value) != true)) {
                    this.ScoreResponsesField = value;
                    this.RaisePropertyChanged("ScoreResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerMessage {
            get {
                return this.ServerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerMessageField, value) != true)) {
                    this.ServerMessageField = value;
                    this.RaisePropertyChanged("ServerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.ServiceCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailedInstitutionResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class FailedInstitutionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientRelationshipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsEdmcWtDupeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProductIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProgramLevelIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.Type TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CampusID {
            get {
                return this.CampusIDField;
            }
            set {
                if ((this.CampusIDField.Equals(value) != true)) {
                    this.CampusIDField = value;
                    this.RaisePropertyChanged("CampusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientRelationshipId {
            get {
                return this.ClientRelationshipIdField;
            }
            set {
                if ((this.ClientRelationshipIdField.Equals(value) != true)) {
                    this.ClientRelationshipIdField = value;
                    this.RaisePropertyChanged("ClientRelationshipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEdmcWtDupe {
            get {
                return this.IsEdmcWtDupeField;
            }
            set {
                if ((this.IsEdmcWtDupeField.Equals(value) != true)) {
                    this.IsEdmcWtDupeField = value;
                    this.RaisePropertyChanged("IsEdmcWtDupe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInternal {
            get {
                return this.IsInternalField;
            }
            set {
                if ((this.IsInternalField.Equals(value) != true)) {
                    this.IsInternalField = value;
                    this.RaisePropertyChanged("IsInternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProductIDs {
            get {
                return this.ProductIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDsField, value) != true)) {
                    this.ProductIDsField = value;
                    this.RaisePropertyChanged("ProductIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProgramLevelIDs {
            get {
                return this.ProgramLevelIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramLevelIDsField, value) != true)) {
                    this.ProgramLevelIDsField = value;
                    this.RaisePropertyChanged("ProgramLevelIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.Type Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoreInstitutionResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ScoreInstitutionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProductIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ScoreIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CampusID {
            get {
                return this.CampusIDField;
            }
            set {
                if ((this.CampusIDField.Equals(value) != true)) {
                    this.CampusIDField = value;
                    this.RaisePropertyChanged("CampusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProductIDs {
            get {
                return this.ProductIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDsField, value) != true)) {
                    this.ProductIDsField = value;
                    this.RaisePropertyChanged("ProductIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreField, value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ScoreId {
            get {
                return this.ScoreIdField;
            }
            set {
                if ((this.ScoreIdField.Equals(value) != true)) {
                    this.ScoreIdField = value;
                    this.RaisePropertyChanged("ScoreId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCallStatus", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    public enum ServiceCallStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    public enum Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScoreCheck = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationCheck = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MpicProspectInfo", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class MpicProspectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCode {
            get {
                return this.StateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCodeField, value) != true)) {
                    this.StateCodeField = value;
                    this.RaisePropertyChanged("StateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CecoPingRequest", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class CecoPingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AffiliateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallCenterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> CampaignTrackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InitiatingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] InstituionIdListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LandingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeadCreationTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionFormUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionLeadInitiatingUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmissionLeadSourceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackingSessionGUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AffiliateId {
            get {
                return this.AffiliateIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AffiliateIdField, value) != true)) {
                    this.AffiliateIdField = value;
                    this.RaisePropertyChanged("AffiliateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallCenterUrl {
            get {
                return this.CallCenterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallCenterUrlField, value) != true)) {
                    this.CallCenterUrlField = value;
                    this.RaisePropertyChanged("CallCenterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CampaignTrackId {
            get {
                return this.CampaignTrackIdField;
            }
            set {
                if ((this.CampaignTrackIdField.Equals(value) != true)) {
                    this.CampaignTrackIdField = value;
                    this.RaisePropertyChanged("CampaignTrackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InitiatingUrl {
            get {
                return this.InitiatingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.InitiatingUrlField, value) != true)) {
                    this.InitiatingUrlField = value;
                    this.RaisePropertyChanged("InitiatingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] InstituionIdList {
            get {
                return this.InstituionIdListField;
            }
            set {
                if ((object.ReferenceEquals(this.InstituionIdListField, value) != true)) {
                    this.InstituionIdListField = value;
                    this.RaisePropertyChanged("InstituionIdList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LandingUrl {
            get {
                return this.LandingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.LandingUrlField, value) != true)) {
                    this.LandingUrlField = value;
                    this.RaisePropertyChanged("LandingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeadCreationTypeId {
            get {
                return this.LeadCreationTypeIdField;
            }
            set {
                if ((this.LeadCreationTypeIdField.Equals(value) != true)) {
                    this.LeadCreationTypeIdField = value;
                    this.RaisePropertyChanged("LeadCreationTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionFormUrl {
            get {
                return this.SubmissionFormUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionFormUrlField, value) != true)) {
                    this.SubmissionFormUrlField = value;
                    this.RaisePropertyChanged("SubmissionFormUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionLeadInitiatingUrl {
            get {
                return this.SubmissionLeadInitiatingUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionLeadInitiatingUrlField, value) != true)) {
                    this.SubmissionLeadInitiatingUrlField = value;
                    this.RaisePropertyChanged("SubmissionLeadInitiatingUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmissionLeadSourceUrl {
            get {
                return this.SubmissionLeadSourceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmissionLeadSourceUrlField, value) != true)) {
                    this.SubmissionLeadSourceUrlField = value;
                    this.RaisePropertyChanged("SubmissionLeadSourceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingSessionGUID {
            get {
                return this.TrackingSessionGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingSessionGUIDField, value) != true)) {
                    this.TrackingSessionGUIDField = value;
                    this.RaisePropertyChanged("TrackingSessionGUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CecoPingResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class CecoPingResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.MatchingEngine.LeadPingService.CecoInstitutionResponse[] InstitutionResponseListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.MatchingEngine.LeadPingService.CecoInstitutionResponse[] InstitutionResponseList {
            get {
                return this.InstitutionResponseListField;
            }
            set {
                if ((object.ReferenceEquals(this.InstitutionResponseListField, value) != true)) {
                    this.InstitutionResponseListField = value;
                    this.RaisePropertyChanged("InstitutionResponseList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CecoInstitutionResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class CecoInstitutionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionId {
            get {
                return this.InstitutionIdField;
            }
            set {
                if ((this.InstitutionIdField.Equals(value) != true)) {
                    this.InstitutionIdField = value;
                    this.RaisePropertyChanged("InstitutionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueId {
            get {
                return this.UniqueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIdField, value) != true)) {
                    this.UniqueIdField = value;
                    this.RaisePropertyChanged("UniqueId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadPingService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RetrieveInstitutionValidationErrors", ReplyAction="http://tempuri.org/IService/RetrieveInstitutionValidationErrorsResponse")]
        EDDY.IS.MatchingEngine.LeadPingService.ValidationResponse RetrieveInstitutionValidationErrors(EDDY.IS.MatchingEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RetrieveInstitutionValidationErrors", ReplyAction="http://tempuri.org/IService/RetrieveInstitutionValidationErrorsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.LeadPingService.ValidationResponse> RetrieveInstitutionValidationErrorsAsync(EDDY.IS.MatchingEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcessMPICSubmission", ReplyAction="http://tempuri.org/IService/ProcessMPICSubmissionResponse")]
        void ProcessMPICSubmission(EDDY.IS.MatchingEngine.LeadPingService.MpicProspectInfo ProspectData, int SubmissionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ProcessMPICSubmission", ReplyAction="http://tempuri.org/IService/ProcessMPICSubmissionResponse")]
        System.Threading.Tasks.Task ProcessMPICSubmissionAsync(EDDY.IS.MatchingEngine.LeadPingService.MpicProspectInfo ProspectData, int SubmissionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FireEmailDupeCheck", ReplyAction="http://tempuri.org/IService/FireEmailDupeCheckResponse")]
        void FireEmailDupeCheck(string Email, string LeadID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FireEmailDupeCheck", ReplyAction="http://tempuri.org/IService/FireEmailDupeCheckResponse")]
        System.Threading.Tasks.Task FireEmailDupeCheckAsync(string Email, string LeadID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FirePhoneDupeCheck", ReplyAction="http://tempuri.org/IService/FirePhoneDupeCheckResponse")]
        void FirePhoneDupeCheck(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FirePhoneDupeCheck", ReplyAction="http://tempuri.org/IService/FirePhoneDupeCheckResponse")]
        System.Threading.Tasks.Task FirePhoneDupeCheckAsync(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsMobile", ReplyAction="http://tempuri.org/IService/IsMobileResponse")]
        bool IsMobile(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsMobile", ReplyAction="http://tempuri.org/IService/IsMobileResponse")]
        System.Threading.Tasks.Task<bool> IsMobileAsync(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearCache", ReplyAction="http://tempuri.org/IService/ClearCacheResponse")]
        string ClearCache(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearCache", ReplyAction="http://tempuri.org/IService/ClearCacheResponse")]
        System.Threading.Tasks.Task<string> ClearCacheAsync(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PingCeco", ReplyAction="http://tempuri.org/IService/PingCecoResponse")]
        EDDY.IS.MatchingEngine.LeadPingService.CecoPingResponse PingCeco(EDDY.IS.MatchingEngine.LeadPingService.CecoPingRequest CecoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PingCeco", ReplyAction="http://tempuri.org/IService/PingCecoResponse")]
        System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.LeadPingService.CecoPingResponse> PingCecoAsync(EDDY.IS.MatchingEngine.LeadPingService.CecoPingRequest CecoRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : EDDY.IS.MatchingEngine.LeadPingService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EDDY.IS.MatchingEngine.LeadPingService.IService>, EDDY.IS.MatchingEngine.LeadPingService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDDY.IS.MatchingEngine.LeadPingService.ValidationResponse RetrieveInstitutionValidationErrors(EDDY.IS.MatchingEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey) {
            return base.Channel.RetrieveInstitutionValidationErrors(ValidationRequest, ServiceKey);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.LeadPingService.ValidationResponse> RetrieveInstitutionValidationErrorsAsync(EDDY.IS.MatchingEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey) {
            return base.Channel.RetrieveInstitutionValidationErrorsAsync(ValidationRequest, ServiceKey);
        }
        
        public void ProcessMPICSubmission(EDDY.IS.MatchingEngine.LeadPingService.MpicProspectInfo ProspectData, int SubmissionID) {
            base.Channel.ProcessMPICSubmission(ProspectData, SubmissionID);
        }
        
        public System.Threading.Tasks.Task ProcessMPICSubmissionAsync(EDDY.IS.MatchingEngine.LeadPingService.MpicProspectInfo ProspectData, int SubmissionID) {
            return base.Channel.ProcessMPICSubmissionAsync(ProspectData, SubmissionID);
        }
        
        public void FireEmailDupeCheck(string Email, string LeadID) {
            base.Channel.FireEmailDupeCheck(Email, LeadID);
        }
        
        public System.Threading.Tasks.Task FireEmailDupeCheckAsync(string Email, string LeadID) {
            return base.Channel.FireEmailDupeCheckAsync(Email, LeadID);
        }
        
        public void FirePhoneDupeCheck(string Phone) {
            base.Channel.FirePhoneDupeCheck(Phone);
        }
        
        public System.Threading.Tasks.Task FirePhoneDupeCheckAsync(string Phone) {
            return base.Channel.FirePhoneDupeCheckAsync(Phone);
        }
        
        public bool IsMobile(string Phone) {
            return base.Channel.IsMobile(Phone);
        }
        
        public System.Threading.Tasks.Task<bool> IsMobileAsync(string Phone) {
            return base.Channel.IsMobileAsync(Phone);
        }
        
        public string ClearCache(string ServiceKey) {
            return base.Channel.ClearCache(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> ClearCacheAsync(string ServiceKey) {
            return base.Channel.ClearCacheAsync(ServiceKey);
        }
        
        public EDDY.IS.MatchingEngine.LeadPingService.CecoPingResponse PingCeco(EDDY.IS.MatchingEngine.LeadPingService.CecoPingRequest CecoRequest) {
            return base.Channel.PingCeco(CecoRequest);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.MatchingEngine.LeadPingService.CecoPingResponse> PingCecoAsync(EDDY.IS.MatchingEngine.LeadPingService.CecoPingRequest CecoRequest) {
            return base.Channel.PingCecoAsync(CecoRequest);
        }
    }
}
