//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Five9Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessRequest", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.ABEA.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class ProcessRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaofInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DialerListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalSystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> OptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProspectFlowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProspectFlowTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProspectRouteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProspectStatusIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaofInterest {
            get {
                return this.AreaofInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaofInterestField, value) != true)) {
                    this.AreaofInterestField = value;
                    this.RaisePropertyChanged("AreaofInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DialerListName {
            get {
                return this.DialerListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DialerListNameField, value) != true)) {
                    this.DialerListNameField = value;
                    this.RaisePropertyChanged("DialerListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalSystemId {
            get {
                return this.ExternalSystemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalSystemIdField, value) != true)) {
                    this.ExternalSystemIdField = value;
                    this.RaisePropertyChanged("ExternalSystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Options {
            get {
                return this.OptionsField;
            }
            set {
                if ((object.ReferenceEquals(this.OptionsField, value) != true)) {
                    this.OptionsField = value;
                    this.RaisePropertyChanged("Options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProspectFlowId {
            get {
                return this.ProspectFlowIdField;
            }
            set {
                if ((this.ProspectFlowIdField.Equals(value) != true)) {
                    this.ProspectFlowIdField = value;
                    this.RaisePropertyChanged("ProspectFlowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProspectFlowTypeId {
            get {
                return this.ProspectFlowTypeIdField;
            }
            set {
                if ((this.ProspectFlowTypeIdField.Equals(value) != true)) {
                    this.ProspectFlowTypeIdField = value;
                    this.RaisePropertyChanged("ProspectFlowTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProspectRouteId {
            get {
                return this.ProspectRouteIdField;
            }
            set {
                if ((this.ProspectRouteIdField.Equals(value) != true)) {
                    this.ProspectRouteIdField = value;
                    this.RaisePropertyChanged("ProspectRouteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProspectStatusId {
            get {
                return this.ProspectStatusIdField;
            }
            set {
                if ((this.ProspectStatusIdField.Equals(value) != true)) {
                    this.ProspectStatusIdField = value;
                    this.RaisePropertyChanged("ProspectStatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Five9Request", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.ABEA.Service.DTO")]
    [System.SerializableAttribute()]
    public partial class Five9Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DegreeInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducationLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalLeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Number1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Number2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramInterestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProspectFlowIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrackIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DegreeInterest {
            get {
                return this.DegreeInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.DegreeInterestField, value) != true)) {
                    this.DegreeInterestField = value;
                    this.RaisePropertyChanged("DegreeInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducationLevel {
            get {
                return this.EducationLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.EducationLevelField, value) != true)) {
                    this.EducationLevelField = value;
                    this.RaisePropertyChanged("EducationLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalLeadId {
            get {
                return this.ExternalLeadIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalLeadIdField, value) != true)) {
                    this.ExternalLeadIdField = value;
                    this.RaisePropertyChanged("ExternalLeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradYear {
            get {
                return this.GradYearField;
            }
            set {
                if ((object.ReferenceEquals(this.GradYearField, value) != true)) {
                    this.GradYearField = value;
                    this.RaisePropertyChanged("GradYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListName {
            get {
                return this.ListNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ListNameField, value) != true)) {
                    this.ListNameField = value;
                    this.RaisePropertyChanged("ListName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number1 {
            get {
                return this.Number1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Number1Field, value) != true)) {
                    this.Number1Field = value;
                    this.RaisePropertyChanged("Number1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number2 {
            get {
                return this.Number2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Number2Field, value) != true)) {
                    this.Number2Field = value;
                    this.RaisePropertyChanged("Number2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramInterest {
            get {
                return this.ProgramInterestField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramInterestField, value) != true)) {
                    this.ProgramInterestField = value;
                    this.RaisePropertyChanged("ProgramInterest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProspectFlowId {
            get {
                return this.ProspectFlowIdField;
            }
            set {
                if ((this.ProspectFlowIdField.Equals(value) != true)) {
                    this.ProspectFlowIdField = value;
                    this.RaisePropertyChanged("ProspectFlowId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackId {
            get {
                return this.TrackIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackIdField, value) != true)) {
                    this.TrackIdField = value;
                    this.RaisePropertyChanged("TrackId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Five9Service.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Process", ReplyAction="http://tempuri.org/IService/ProcessResponse")]
        bool Process(EDDY.IS.FormsEngine.Five9Service.ProcessRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/Process", ReplyAction="http://tempuri.org/IService/ProcessResponse")]
        System.Threading.Tasks.Task<bool> ProcessAsync(EDDY.IS.FormsEngine.Five9Service.ProcessRequest Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendToFive9", ReplyAction="http://tempuri.org/IService/SendToFive9Response")]
        void SendToFive9(EDDY.IS.FormsEngine.Five9Service.Five9Request Request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/SendToFive9", ReplyAction="http://tempuri.org/IService/SendToFive9Response")]
        System.Threading.Tasks.Task SendToFive9Async(EDDY.IS.FormsEngine.Five9Service.Five9Request Request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : EDDY.IS.FormsEngine.Five9Service.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EDDY.IS.FormsEngine.Five9Service.IService>, EDDY.IS.FormsEngine.Five9Service.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Process(EDDY.IS.FormsEngine.Five9Service.ProcessRequest Request) {
            return base.Channel.Process(Request);
        }
        
        public System.Threading.Tasks.Task<bool> ProcessAsync(EDDY.IS.FormsEngine.Five9Service.ProcessRequest Request) {
            return base.Channel.ProcessAsync(Request);
        }
        
        public void SendToFive9(EDDY.IS.FormsEngine.Five9Service.Five9Request Request) {
            base.Channel.SendToFive9(Request);
        }
        
        public System.Threading.Tasks.Task SendToFive9Async(EDDY.IS.FormsEngine.Five9Service.Five9Request Request) {
            return base.Channel.SendToFive9Async(Request);
        }
    }
}
