using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace EDDY.IS.MatchingEngine.DataModel
{
    public static class StaticInternalObject
    {
        public static Dictionary<int, string> Countries =
            new Dictionary<int, string>() {
                { 4, "United States"},
                { 5, "Canada" },
                { 6, "Andorra" },
                { 7, "United Arab Emirates"},
                { 8, "Afghanistan"},
                { 9, "Antigua and Barbuda"},
                { 10, "Anguilla"},
                { 11, "Albania"},
                { 12, "Armenia"},
                { 13, "Netherlands Antilles"},
                { 14, "Angola"},
                { 15, "Antarctica"},
                { 16, "Argentina"},
                { 17, "American Samoa"},
                { 18, "Austria"},
                { 19, "Australia"},
                { 20, "Aruba"},
                { 21, "Aland Islands"},
                { 22, "Azerbaijan"},
                { 23, "Bosnia and Herzegovina"},
                { 24, "Barbados"},
                { 25, "Bangladesh"},
                { 26, "Belgium"},
                { 27, "Burkina Faso"},
                { 28, "Bulgaria"},
                { 29, "Bahrain"},
                { 30, "Burundi"},
                { 31, "Benin"},
                { 32, "Saint Barthlemy"},
                { 33, "Bermuda"},
                { 34, "Brunei Darussalam"},
                { 35, "Bolivia"},
                { 36, "Brazil"},
                { 37, "Bahamas"},
                { 38, "Bhutan"},
                { 39, "Bouvet island"},
                { 40, "Botswana"},
                { 41, "Belarus"},
                { 42, "Belize"},
                { 43, "Cocos (Keeling) Islands"},
                { 44, "Congo, The Democratic Republic of the"},
                { 45, "Central African Republic"},
                { 46, "Congo"},
                { 47, "Switzerland"},
                { 48, "Cote Divoire"},
                { 49, "Cook Islands"},
                { 50, "Chile"},
                { 51, "Cameroon"},
                { 52, "China"},
                { 53, "Colombia"},
                { 54, "Costa Rica"},
                { 55, "Cuba"},
                { 56, "Cape Verde"},
                { 57, "Christmas Island"},
                { 58, "Cyprus"},
                { 59, "Czech Republic"},
                { 60, "Germany"},
                { 61, "Djibouti"},
                { 62, "Denmark"},
                { 63, "Dominica"},
                { 64, "Dominican Republic"},
                { 65, "Algeria"},
                { 66, "Ecuador"},
                { 67, "Estonia"},
                { 68, "Egypt"},
                { 69, "Western Sahara"},
                { 70, "Eritrea"},
                { 71, "Spain"},
                { 72, "Ethiopia"},
                { 73, "Finland"},
                { 74, "Fiji"},
                { 75, "Falkland Islands (Malvinas)"},
                { 76, "Micronesia, Federated States of"},
                { 77, "Faroe Islands"},
                { 78, "France"},
                { 79, "Gabon"},
                { 80, "United Kingdom"},
                { 81, "Grenada"},
                { 82, "Georgia (Country)"},
                { 83, "French Guiana"},
                { 84, "Guernsey"},
                { 85, "Ghana"},
                { 86, "Gibraltar"},
                { 87, "Greenland"},
                { 88, "Gambia"},
                { 89, "Guinea"},
                { 90, "Guadeloupe"},
                { 91, "Equatorial Guinea"},
                { 92, "Greece"},
                { 93, "South Georgia and the South Sandwich Isl"},
                { 94, "Guatemala"},
                { 95, "Guam"},
                { 96, "Guinea-Bissau"},
                { 97, "Guyana"},
                { 98, "Hong Kong"},
                { 99, "Heard Island and McDonald Islands"},
                { 100, "Honduras"},
                { 101, "Croatia"},
                { 102, "Haiti"},
                { 103, "Hungary"},
                { 104, "Indonesia"},
                { 105, "Ireland"},
                { 106, "Israel"},
                { 107, "Isle of man"},
                { 108, "India"},
                { 109, "British Indian Ocean Territory"},
                { 110, "Iraq"},
                { 111, "Iran, Islamic Republic of"},
                { 112, "Iceland"},
                { 113, "Italy"},
                { 114, "Jersey"},
                { 115, "Jamaica"},
                { 116, "Jordan"},
                { 117, "Japan"},
                { 118, "Kenya"},
                { 119, "Kyrgyzstan"},
                { 120, "Cambodia"},
                { 121, "Kiribati"},
                { 122, "Comoros"},
                { 123, "Saint Kitts and Nevis"},
                { 124, "Korea, Democratic People's Republic of"},
                { 125, "Korea"},
                { 126, "Kuwait"},
                { 127, "Cayman Islands"},
                { 128, "Kazakhstan"},
                { 129, "Lao People's Democratic Republic"},
                { 130, "Lebanon"},
                { 131, "Saint Lucia"},
                { 132, "Liechtenstein"},
                { 133, "Sri Lanka"},
                { 134, "Liberia"},
                { 135, "Lesotho"},
                { 136, "Lithuania"},
                { 137, "Luxembourg"},
                { 138, "Latvia"},
                { 139, "Libyan Arab Jamahiriya"},
                { 140, "Morocco"},
                { 141, "Monaco"},
                { 142, "Moldova, Republic of"},
                { 143, "Montenegro"},
                { 144, "Saint Martin"},
                { 145, "Madagascar"},
                { 146, "Marshall Islands"},
                { 147, "Macedonia"},
                { 148, "Mali"},
                { 149, "Myanmar"},
                { 150, "Mongolia"},
                { 151, "Macao"},
                { 152, "Northern Mariana Islands"},
                { 153, "Martinique"},
                { 154, "Mauritania"},
                { 155, "Montserrat"},
                { 156, "Malta"},
                { 157, "Mauritius"},
                { 158, "Maldives"},
                { 159, "Malawi"},
                { 160, "Mexico"},
                { 161, "Malaysia"},
                { 162, "Mozambique"},
                { 163, "Namibia"},
                { 164, "New Caledonia"},
                { 165, "Niger"},
                { 166, "Norfolk island"},
                { 167, "Nigeria"},
                { 168, "Nicaragua"},
                { 169, "Netherlands"},
                { 170, "Norway"},
                { 171, "Nepal"},
                { 172, "Nauru"},
                { 173, "Niue"},
                { 174, "New Zealand"},
                { 175, "Oman"},
                { 176, "Panama"},
                { 177, "Peru"},
                { 178, "French Polynesia"},
                { 179, "Papua New Guinea"},
                { 180, "Philippines"},
                { 181, "Pakistan"},
                { 182, "Poland"},
                { 183, "Saint Pierre and Miquelon"},
                { 184, "Pitcairn"},
                { 185, "Palestine"},
                { 186, "Portugal"},
                { 187, "Palau"},
                { 188, "Paraguay"},
                { 189, "Qatar"},
                { 190, "Reunion"},
                { 191, "Romania"},
                { 192, "Serbia"},
                { 193, "Russia"},
                { 194, "Rwanda"},
                { 195, "Saudi Arabia"},
                { 196, "Solomon Islands"},
                { 197, "Seychelles"},
                { 198, "Sudan"},
                { 199, "Sweden"},
                { 200, "Singapore"},
                { 201, "Saint Helena"},
                { 202, "Slovenia"},
                { 203, "Svalbard and Jan Mayen"},
                { 204, "Slovakia"},
                { 205, "Sierra leone"},
                { 206, "San Marino"},
                { 207, "Senegal"},
                { 208, "Somalia"},
                { 209, "Suriname"},
                { 210, "Sao Tome and Principe"},
                { 211, "El Salvador"},
                { 212, "Syrian Arab Republic"},
                { 213, "Swaziland"},
                { 214, "Turks and Caicos Islands"},
                { 215, "Chad"},
                { 216, "French Southern Territories"},
                { 217, "Togo"},
                { 218, "Thailand"},
                { 219, "Tajikistan"},
                { 220, "Tokelau"},
                { 221, "Timor-Leste"},
                { 222, "Turkmenistan"},
                { 223, "Tunisia"},
                { 224, "Tonga"},
                { 225, "Turkey"},
                { 226, "Trinidad and Tobago"},
                { 227, "Tuvalu"},
                { 228, "Taiwan, P.R.O.C."},
                { 229, "Tanzania, United Republic of"},
                { 230, "Ukraine"},
                { 231, "Uganda"},
                { 232, "United States (minor outlying islands)"},
                { 233, "Uruguay"},
                { 234, "Uzbekistan"},
                { 235, "Holy see (vatican city state)"},
                { 236, "Saint Vincent and the Grenadines"},
                { 237, "Venezuela"},
                { 238, "Virgin Island (British)"},
                { 239, "Virgin Islands, U.S."},
                { 240, "Viet Nam"},
                { 241, "Vanuatu"},
                { 242, "Wallis and Futuna"},
                { 243, "Samoa"},
                { 244, "Yemen"},
                { 245, "Mayotte"},
                { 246, "South Africa"},
                { 247, "Zambia"},
                { 248, "Zimbabwe"},
                { 249, "Bonaire"},
                { 250, "Curacao"},
                { 251, "Europe (generic)"},
                { 252, "Puerto Rico"},
                { 253, "Sint Maarten"}
            };

        public static Dictionary<int, string> States
            = new Dictionary<int, string>()
            {
                { 1, "Alabama"},
                { 3, "Alaska"},
                { 4, "Arizona"},
                { 5, "Arkansas"},
                { 6, "California"},
                { 7, "Colorado"},
                { 8, "Connecticut"},
                { 9, "Delaware"},
                { 10, "District of Columbia"},
                { 11, "Florida"},
                { 12, "Georgia"},
                { 13, "Hawaii"},
                { 14, "Idaho"},
                { 15, "Illinois"},
                { 16, "Indiana"},
                { 17, "Iowa"},
                { 18, "Kansas"},
                { 19, "Kentucky"},
                { 20, "Louisiana"},
                { 21, "Maine"},
                { 22, "Maryland"},
                { 23, "Massachusetts"},
                { 24, "Michigan"},
                { 25, "Minnesota"},
                { 26, "Mississippi"},
                { 27, "Missouri"},
                { 28, "Montana"},
                { 29, "Nebraska"},
                { 30, "Nevada"},
                { 31, "New Hampshire"},
                { 32, "New Jersey"},
                { 33, "New Mexico"},
                { 34, "New York"},
                { 35, "North Carolina"},
                { 36, "North Dakota"},
                { 37, "Ohio"},
                { 38, "Oklahoma"},
                { 39, "Oregon"},
                { 40, "Pennsylvania"},
                { 41, "Rhode Island"},
                { 42, "South Carolina"},
                { 43, "South Dakota"},
                { 44, "Tennessee"},
                { 45, "Texas"},
                { 46, "Utah"},
                { 47, "Vermont"},
                { 48, "Virginia"},
                { 49, "Washington"},
                { 50, "West Virginia"},
                { 51, "Wisconsin"},
                { 52, "Wyoming"},
                { 53, "Alberta"},
                { 54, "British Columbia"},
                { 55, "Manitoba"},
                { 56, "New Brunswick"},
                { 57, "Newfoundland"},
                { 58, "Northwest Territories"},
                { 59, "Nova Scotia"},
                { 60, "Nunavut"},
                { 61, "Ontario"},
                { 62, "Prince Edward Island"},
                { 63, "Quebec"},
                { 64, "Saskatchewan"},
                { 65, "Yukon Territory"},
                { 66, "Puerto Rico"},
                { 67, "Armed Forces"},
                { 68, "Armed Forces - Americas"},
                { 69, "Armed Forces - Pacific"},
                { 70, "American Samoa"},
                { 71, "Federated States of Micronesia"},
                { 72, "Guam"},
                { 73, "Marshall Islands"},
                { 74, "Northern Mariana Islands"},
                { 75, "Palau"},
                { 76, "Virgin Islands"},
                { 1029, "England"},
                { 1030, "Northern Ireland"},
                { 1031, "Scotland"},
                { 1032, "Wales"}
            };

        public static Dictionary<int, int> States_GradSchools_Priority
            = new Dictionary<int, int>()
            {
                { 1,  26}, //"Alabama",
                { 3,  50}, //"Alaska",
                { 4,  26}, //"Arizona",
                { 5,  36}, //"Arkansas",
                { 6,  1}, //"California",
                { 7,  15}, //"Colorado",
                { 8,  18}, //"Connecticut",
                { 9,  45}, //"Delaware",
                { 10, 22}, //"District of Columbia",
                { 11, 4}, // "Florida", 
                { 12, 8}, //"Georgia",
                { 13, 44}, //"Hawaii",
                { 14, 42}, //"Idaho", 
                { 15, 7}, //"Illinois",
                { 16, 20}, //"Indiana", 
                { 17, 31}, //"Iowa", 
                { 18, 32}, //"Kansas", 
                { 19, 30}, //"Kentucky",
                { 20, 27}, // "Louisiana",
                { 21, 43}, //"Maine", 
                { 22, 14}, //"Maryland",
                { 23, 10}, //"Massachusetts", 
                { 24, 13}, //"Michigan", 
                { 25, 16}, //"Minnesota",
                { 26, 33}, //"Mississippi",
                { 27, 21}, //"Missouri",
                { 28, 47}, //"Montana",
                { 29, 40}, //"Nebraska",
                { 30, 35}, //"Nevada",
                { 31, 39}, //"New Hampshire",
                { 32, 6}, //"New Jersey",
                { 33, 38}, //"New Mexico",
                { 34, 2}, //"New York", 
                { 35, 9}, //"North Carolina",
                { 36, 49}, //"North Dakota", 
                { 37, 12}, // "Ohio", 
                { 38, 34}, //"Oklahoma",
                { 39, 28}, //"Oregon",
                { 40, 5}, // "Pennsylvania",
                { 41, 37}, //"Rhode Island",
                { 42, 23}, //"South Carolina",
                { 43, 48}, //"South Dakota",
                { 44, 17}, //"Tennessee",
                { 45, 3}, //"Texas",
                { 46, 29}, //"Utah", 
                { 47, 46}, //"Vermont",
                { 48, 11}, //"Virginia",
                { 49, 19}, //"Washington", 
                { 50, 41}, //"West Virginia",
                { 51, 24}, //"Wisconsin",
                { 52, 51},  //"Wyoming",
            };
    }
}
