//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.LeadScoringService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoringRequest", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class ScoringRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CampaignTrackGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadScoringService.CriteriaInput CriteriaInputField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadScoringService.ProspectInput ProspectInputField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CampaignTrackGuid {
            get {
                return this.CampaignTrackGuidField;
            }
            set {
                if ((this.CampaignTrackGuidField.Equals(value) != true)) {
                    this.CampaignTrackGuidField = value;
                    this.RaisePropertyChanged("CampaignTrackGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadScoringService.CriteriaInput CriteriaInput {
            get {
                return this.CriteriaInputField;
            }
            set {
                if ((object.ReferenceEquals(this.CriteriaInputField, value) != true)) {
                    this.CriteriaInputField = value;
                    this.RaisePropertyChanged("CriteriaInput");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadScoringService.ProspectInput ProspectInput {
            get {
                return this.ProspectInputField;
            }
            set {
                if ((object.ReferenceEquals(this.ProspectInputField, value) != true)) {
                    this.ProspectInputField = value;
                    this.RaisePropertyChanged("ProspectInput");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CriteriaInput", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class CriteriaInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] CategoryListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProgramLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] SubjectListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] CategoryList {
            get {
                return this.CategoryListField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryListField, value) != true)) {
                    this.CategoryListField = value;
                    this.RaisePropertyChanged("CategoryList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProgramLevelId {
            get {
                return this.ProgramLevelIdField;
            }
            set {
                if ((this.ProgramLevelIdField.Equals(value) != true)) {
                    this.ProgramLevelIdField = value;
                    this.RaisePropertyChanged("ProgramLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] SubjectList {
            get {
                return this.SubjectListField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectListField, value) != true)) {
                    this.SubjectListField = value;
                    this.RaisePropertyChanged("SubjectList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectInput", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class ProspectInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EducationLevelIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HSGraduationYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsCitizenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsMilitaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MilitaryStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StateIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EducationLevelId {
            get {
                return this.EducationLevelIdField;
            }
            set {
                if ((this.EducationLevelIdField.Equals(value) != true)) {
                    this.EducationLevelIdField = value;
                    this.RaisePropertyChanged("EducationLevelId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HSGraduationYear {
            get {
                return this.HSGraduationYearField;
            }
            set {
                if ((this.HSGraduationYearField.Equals(value) != true)) {
                    this.HSGraduationYearField = value;
                    this.RaisePropertyChanged("HSGraduationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsCitizen {
            get {
                return this.IsCitizenField;
            }
            set {
                if ((this.IsCitizenField.Equals(value) != true)) {
                    this.IsCitizenField = value;
                    this.RaisePropertyChanged("IsCitizen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsMilitary {
            get {
                return this.IsMilitaryField;
            }
            set {
                if ((this.IsMilitaryField.Equals(value) != true)) {
                    this.IsMilitaryField = value;
                    this.RaisePropertyChanged("IsMilitary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MilitaryStatusId {
            get {
                return this.MilitaryStatusIdField;
            }
            set {
                if ((this.MilitaryStatusIdField.Equals(value) != true)) {
                    this.MilitaryStatusIdField = value;
                    this.RaisePropertyChanged("MilitaryStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCode {
            get {
                return this.StateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCodeField, value) != true)) {
                    this.StateCodeField = value;
                    this.RaisePropertyChanged("StateCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StateId {
            get {
                return this.StateIdField;
            }
            set {
                if ((this.StateIdField.Equals(value) != true)) {
                    this.StateIdField = value;
                    this.RaisePropertyChanged("StateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoringResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class ScoringResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid LeadScoringGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LeadScoringTierLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadScoringService.ProductAssignment ProductAssignmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadScoringService.ScoringResponseType ScoringResponseTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid LeadScoringGuid {
            get {
                return this.LeadScoringGuidField;
            }
            set {
                if ((this.LeadScoringGuidField.Equals(value) != true)) {
                    this.LeadScoringGuidField = value;
                    this.RaisePropertyChanged("LeadScoringGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LeadScoringTierLevel {
            get {
                return this.LeadScoringTierLevelField;
            }
            set {
                if ((this.LeadScoringTierLevelField.Equals(value) != true)) {
                    this.LeadScoringTierLevelField = value;
                    this.RaisePropertyChanged("LeadScoringTierLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadScoringService.ProductAssignment ProductAssignment {
            get {
                return this.ProductAssignmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductAssignmentField, value) != true)) {
                    this.ProductAssignmentField = value;
                    this.RaisePropertyChanged("ProductAssignment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadScoringService.ScoringResponseType ScoringResponseType {
            get {
                return this.ScoringResponseTypeField;
            }
            set {
                if ((this.ScoringResponseTypeField.Equals(value) != true)) {
                    this.ScoringResponseTypeField = value;
                    this.RaisePropertyChanged("ScoringResponseType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductAssignment", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class ProductAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChosenModelProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadScoringService.CrProductAssignment[] CrProductAssignmentListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChosenModelProductId {
            get {
                return this.ChosenModelProductIdField;
            }
            set {
                if ((this.ChosenModelProductIdField.Equals(value) != true)) {
                    this.ChosenModelProductIdField = value;
                    this.RaisePropertyChanged("ChosenModelProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadScoringService.CrProductAssignment[] CrProductAssignmentList {
            get {
                return this.CrProductAssignmentListField;
            }
            set {
                if ((object.ReferenceEquals(this.CrProductAssignmentListField, value) != true)) {
                    this.CrProductAssignmentListField = value;
                    this.RaisePropertyChanged("CrProductAssignmentList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ScoringResponseType", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    public enum ScoringResponseType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CampaignNotActive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCampaign = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoValidUniverse = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniverseProductAssignmentOff = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorServiceCallFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VendorServiceCallTimeout = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScoringNotAllowedForCampaign = 8,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CrProductAssignment", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadScoring.DTO")]
    [System.SerializableAttribute()]
    public partial class CrProductAssignment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrId {
            get {
                return this.CrIdField;
            }
            set {
                if ((this.CrIdField.Equals(value) != true)) {
                    this.CrIdField = value;
                    this.RaisePropertyChanged("CrId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadScoringService.ILeadScoringService")]
    public interface ILeadScoringService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILeadScoringService/GetLeadScore", ReplyAction="http://tempuri.org/ILeadScoringService/GetLeadScoreResponse")]
        EDDY.IS.FormsEngine.LeadScoringService.ScoringResponse GetLeadScore(EDDY.IS.FormsEngine.LeadScoringService.ScoringRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILeadScoringServiceChannel : EDDY.IS.FormsEngine.LeadScoringService.ILeadScoringService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LeadScoringServiceClient : System.ServiceModel.ClientBase<EDDY.IS.FormsEngine.LeadScoringService.ILeadScoringService>, EDDY.IS.FormsEngine.LeadScoringService.ILeadScoringService {
        
        public LeadScoringServiceClient() {
        }
        
        public LeadScoringServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LeadScoringServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadScoringServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LeadScoringServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDDY.IS.FormsEngine.LeadScoringService.ScoringResponse GetLeadScore(EDDY.IS.FormsEngine.LeadScoringService.ScoringRequest request) {
            return base.Channel.GetLeadScore(request);
        }
    }
}
