//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientCampusProgramRelationship
    {
        public int ClientCampusProgramRelationshipId { get; set; }
        public int ClientCampusRelationshipId { get; set; }
        public int CampusProgramId { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid Rowguid { get; set; }
        public Nullable<bool> IsImported { get; set; }
        public Nullable<int> ECProgramId { get; set; }
        public Nullable<int> GSProgramId { get; set; }
        public string RevenueType { get; set; }
    
        public virtual CampusProgram CampusProgram { get; set; }
    }
}
