//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorMessage
    {
        public int ErrorMessageId { get; set; }
        public int StandardControlTypeId { get; set; }
        public int ErrorCodeId { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<int> TemplateTypeId { get; set; }
    
        public virtual ErrorCode ErrorCode { get; set; }
        public virtual TemplateType TemplateType { get; set; }
    }
}
