//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FEEntitiesContainer : DbContext
    {
        public FEEntitiesContainer()
            : base("name=FEEntitiesContainer")
        {
    		Type _Hack = typeof(System.Data.Entity.SqlServer.SqlProviderServices); //Hack to make sure EntityFramework.SqlServer assembly is loaded
        	string stringSeconds = ConfigurationManager.AppSettings["EntityFrameworkCommandTimeout"];
                    
            if (stringSeconds != null)
            {
                int seconds;
                if(int.TryParse(stringSeconds, out seconds))
    			{
                    this.Database.CommandTimeout = seconds;
    		    }
            }
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
    		this.Configuration.ValidateOnSaveEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SubmissionDetail> SubmissionDetails { get; set; }
        public virtual DbSet<SubmissionDetailAdditional> SubmissionDetailAdditionals { get; set; }
        public virtual DbSet<SubmissionMatchResponse> SubmissionMatchResponses { get; set; }
        public virtual DbSet<SubmissionValidationError> SubmissionValidationErrors { get; set; }
        public virtual DbSet<ErrorCode> ErrorCodes { get; set; }
        public virtual DbSet<ErrorMessage> ErrorMessages { get; set; }
        public virtual DbSet<ResourceMetaData> ResourceMetaDatas { get; set; }
        public virtual DbSet<StandardControl> StandardControls { get; set; }
        public virtual DbSet<StandardControlCode> StandardControlCodes { get; set; }
        public virtual DbSet<StandardControlCodeFilter> StandardControlCodeFilters { get; set; }
        public virtual DbSet<StandardControlDataType> StandardControlDataTypes { get; set; }
        public virtual DbSet<StandardControlType> StandardControlTypes { get; set; }
        public virtual DbSet<StandardControlValidation> StandardControlValidations { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateAssignment> TemplateAssignments { get; set; }
        public virtual DbSet<TemplateControl> TemplateControls { get; set; }
        public virtual DbSet<TemplateControlDefault> TemplateControlDefaults { get; set; }
        public virtual DbSet<TemplateSection> TemplateSections { get; set; }
        public virtual DbSet<TemplateStep> TemplateSteps { get; set; }
        public virtual DbSet<TemplateType> TemplateTypes { get; set; }
        public virtual DbSet<ValidationLibrary> ValidationLibraries { get; set; }
        public virtual DbSet<ValueList> ValueLists { get; set; }
        public virtual DbSet<ProgramTemplateMessage> ProgramTemplateMessages { get; set; }
        public virtual DbSet<HTMLRenderingStrategy> HTMLRenderingStrategies { get; set; }
        public virtual DbSet<HTMLRenderingStrategyAssignment> HTMLRenderingStrategyAssignments { get; set; }
        public virtual DbSet<PreDefinedValueList> PreDefinedValueLists { get; set; }
        public virtual DbSet<VW_ProgramProductTemplate> VW_ProgramProductTemplate { get; set; }
        public virtual DbSet<SubmissionLeadScoringResponse> SubmissionLeadScoringResponses { get; set; }
        public virtual DbSet<StandardControlGroup> StandardControlGroups { get; set; }
        public virtual DbSet<TemplateApplicationOverride> TemplateApplicationOverrides { get; set; }
        public virtual DbSet<VW_EMSInstitutionTCPAMessages> VW_EMSInstitutionTCPAMessages { get; set; }
        public virtual DbSet<Campaign> Campaigns { get; set; }
        public virtual DbSet<KVCode> KVCodes { get; set; }
        public virtual DbSet<KVCodeData> KVCodeDatas { get; set; }
        public virtual DbSet<ProgramLevel> ProgramLevels { get; set; }
        public virtual DbSet<Submission> Submissions { get; set; }
        public virtual DbSet<VW_ProspectResubmissions> VW_ProspectResubmissions { get; set; }
        public virtual DbSet<OpenMailProfile> OpenMailProfiles { get; set; }
        public virtual DbSet<OpenMailRule> OpenMailRules { get; set; }
        public virtual DbSet<VW_LandingPageSettings> VW_LandingPageSettings { get; set; }
    
        public virtual ObjectResult<EDDY_FE_GetCreativeURLs_Result> EDDY_FE_GetCreativeURLs(string urlStart, Nullable<System.Guid> campaignTrackId, Nullable<int> leadCreationTypeId, string submissionFormUrl, string submissionLeadSourceUrl, string submissionLeadInitiatingUrl, string firstName, string phone, string emailAddress, string videoUrl)
        {
            var urlStartParameter = urlStart != null ?
                new ObjectParameter("UrlStart", urlStart) :
                new ObjectParameter("UrlStart", typeof(string));
    
            var campaignTrackIdParameter = campaignTrackId.HasValue ?
                new ObjectParameter("CampaignTrackId", campaignTrackId) :
                new ObjectParameter("CampaignTrackId", typeof(System.Guid));
    
            var leadCreationTypeIdParameter = leadCreationTypeId.HasValue ?
                new ObjectParameter("LeadCreationTypeId", leadCreationTypeId) :
                new ObjectParameter("LeadCreationTypeId", typeof(int));
    
            var submissionFormUrlParameter = submissionFormUrl != null ?
                new ObjectParameter("SubmissionFormUrl", submissionFormUrl) :
                new ObjectParameter("SubmissionFormUrl", typeof(string));
    
            var submissionLeadSourceUrlParameter = submissionLeadSourceUrl != null ?
                new ObjectParameter("SubmissionLeadSourceUrl", submissionLeadSourceUrl) :
                new ObjectParameter("SubmissionLeadSourceUrl", typeof(string));
    
            var submissionLeadInitiatingUrlParameter = submissionLeadInitiatingUrl != null ?
                new ObjectParameter("SubmissionLeadInitiatingUrl", submissionLeadInitiatingUrl) :
                new ObjectParameter("SubmissionLeadInitiatingUrl", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var emailAddressParameter = emailAddress != null ?
                new ObjectParameter("EmailAddress", emailAddress) :
                new ObjectParameter("EmailAddress", typeof(string));

            var videoUrlParameter = videoUrl != null ?
                new ObjectParameter("VideoUrlPassed", videoUrl) :
                new ObjectParameter("VideoUrlPassed", typeof(string));

            var fullFormLandingUrlParameter = submissionFormUrl != null ?
                new ObjectParameter("FullFormLandingUrl", submissionFormUrl) :
                new ObjectParameter("FullFormLandingUrl", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EDDY_FE_GetCreativeURLs_Result>("EDDY_FE_GetCreativeURLs", urlStartParameter, campaignTrackIdParameter, leadCreationTypeIdParameter, submissionFormUrlParameter, submissionLeadSourceUrlParameter, submissionLeadInitiatingUrlParameter, firstNameParameter, phoneParameter, emailAddressParameter, videoUrlParameter, fullFormLandingUrlParameter);
        }
    }
}
