//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenMailRule
    {
        public int OpenMailRuleId { get; set; }
        public int OpenMailProfileId { get; set; }
        public int StandardControlCodeId { get; set; }
        public int GroupId { get; set; }
        public string RuleType { get; set; }
        public string Value { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual OpenMailProfile OpenMailProfile { get; set; }
        public virtual StandardControlCode StandardControlCode { get; set; }
    }
}
