//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenMailProfile
    {
        public OpenMailProfile()
        {
            this.OpenMailRules = new HashSet<OpenMailRule>();
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public int OpenMailProfileId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<OpenMailRule> OpenMailRules { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
