//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreDefinedValueList
    {
        public PreDefinedValueList()
        {
            this.ValueListItems = new HashSet<ValueList>();
        }
    
        public int PreDefinedValueListId { get; set; }
        public string PreDefinedValueListName { get; set; }
        public string StoredProcedureName { get; set; }
        public bool IsMatchingEngineAdditionalField { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
    
        public virtual ICollection<ValueList> ValueListItems { get; set; }
    }
}
