//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramLevel
    {
        public int ProgramLevelId { get; set; }
        public string ProgramLevelName { get; set; }
        public string ProgramLevelDescription { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid RowGuid { get; set; }
        public bool CanSmartmatch { get; set; }
        public Nullable<int> ProgramLevelGroupId { get; set; }
        public Nullable<bool> FullDegreeAllowed { get; set; }
        public Nullable<bool> NonFullDegreeAllowed { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    }
}
