//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramProduct
    {
        public int ProgramProductId { get; set; }
        public int ClientCampusProgramRelationshipID { get; set; }
        public int ProductId { get; set; }
        public string ProgramCode { get; set; }
        public Nullable<int> AllowableRadius { get; set; }
        public string RadiusZipCode { get; set; }
        public Nullable<bool> IsZipCodeInclusionExclusionActive { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid rowguid { get; set; }
        public Nullable<bool> UseCCRGeoInfo { get; set; }
        public Nullable<bool> IncludeAllZipCodes { get; set; }
        public Nullable<bool> strategic { get; set; }
        public Nullable<bool> IsImported { get; set; }
        public Nullable<int> ecprogramid { get; set; }
        public Nullable<bool> IsZipCodeInclusion { get; set; }
        public Nullable<bool> IsZipCodeExclusion { get; set; }
        public bool CanSmartmatch { get; set; }
        public string DeliveryEmailRoutingAddress { get; set; }
    
        public virtual ClientCampusProgramRelationship ClientCampusProgramRelationship { get; set; }
    }
}
