//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardControlCodeFilter
    {
        public int StandardControlCodeFilterId { get; set; }
        public int StandardControlCodeId { get; set; }
        public int StandardControlCodeIdFilter { get; set; }
    
        public virtual StandardControlCode StandardControlCodeFilterEntity { get; set; }
    }
}
