//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardControl
    {
        public StandardControl()
        {
            this.StandardControlValidations = new HashSet<StandardControlValidation>();
        }
    
        public int StandardControlId { get; set; }
        public int StandardControlTypeId { get; set; }
        public string DefaultLabel { get; set; }
        public string FieldName { get; set; }
        public string DefaultValue { get; set; }
        public Nullable<int> PreDefinedValueListId { get; set; }
        public Nullable<bool> IsLabelHidden { get; set; }
        public Nullable<int> MinLength { get; set; }
        public Nullable<int> MaxLength { get; set; }
        public int StandardControlDataTypeId { get; set; }
        public int StandardControlCodeId { get; set; }
        public string JavaScriptDataBind { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<bool> TransformOnMobile { get; set; }
        public string ControlFriendlyName { get; set; }
        public string Mask { get; set; }
        public string AutoCompleteName { get; set; }
        public Nullable<bool> SearchablePredefinedValueList { get; set; }
    
        public virtual StandardControlCode StandardControlCode { get; set; }
        public virtual StandardControlDataType StandardControlDataType { get; set; }
        public virtual StandardControlType StandardControlType { get; set; }
        public virtual ICollection<StandardControlValidation> StandardControlValidations { get; set; }
        public virtual PreDefinedValueList PreDefinedValueList { get; set; }
    }
}
