//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionMatchResponse
    {
        public int SubmissionMatchResponseId { get; set; }
        public int SubmissionId { get; set; }
        public System.Guid MatchResponseGuid { get; set; }
        public int MatchResponseTypeId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Submission Submission { get; set; }
    }
}
