//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionDetail
    {
        public int SubmissionDetailId { get; set; }
        public int SubmissionId { get; set; }
        public int StandardControlCodeId { get; set; }
        public string SubmissionDetailValue { get; set; }
    
        public virtual Submission Submission { get; set; }
    }
}
