//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateControl
    {
        public TemplateControl()
        {
            this.TemplateControlDefaults = new HashSet<TemplateControlDefault>();
        }
    
        public int TemplateControlId { get; set; }
        public int TemplateSectionId { get; set; }
        public int TemplateId { get; set; }
        public int StandardControlId { get; set; }
        public int RowSequence { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public string InstanceLabel { get; set; }
        public string InstanceWaterMark { get; set; }
        public string InstanceToolTip { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<bool> HideLabelOnMobile { get; set; }
        public string InstanceMobileWaterMark { get; set; }
        public int TransformOnMobileType { get; set; }
        public int TransformOnDesktopType { get; set; }
        public Nullable<bool> IsTypeAhead { get; set; }
        public string ExtendedProperties { get; set; }
        public string InstanceTemplateLabel { get; set; }
        public bool ShowInEddyApi { get; set; }
    
        public virtual StandardControl StandardControl { get; set; }
        public virtual ICollection<TemplateControlDefault> TemplateControlDefaults { get; set; }
    }
}
