//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateStep
    {
        public TemplateStep()
        {
            this.TemplateSections = new HashSet<TemplateSection>();
        }
    
        public int TemplateStepId { get; set; }
        public int TemplateId { get; set; }
        public string Name { get; set; }
        public int Sequence { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public string TemplateName { get; set; }
    
        public virtual ICollection<TemplateSection> TemplateSections { get; set; }
    }
}
