//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateSection
    {
        public TemplateSection()
        {
            this.TemplateControls = new HashSet<TemplateControl>();
        }
    
        public int TemplateSectionId { get; set; }
        public int TemplateStepId { get; set; }
        public string Name { get; set; }
        public int Sequence { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<int> StandardControlGroupId { get; set; }
        public string TemplateName { get; set; }
    
        public virtual ICollection<TemplateControl> TemplateControls { get; set; }
        public virtual StandardControlGroup StandardControlGroup { get; set; }
    }
}
