//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValueList
    {
        public int ValueListId { get; set; }
        public string Key { get; set; }
        public string Text { get; set; }
        public string Value { get; set; }
        public bool IsDefault { get; set; }
        public int PreDefinedValueListId { get; set; }
    }
}
