//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_LandingPageSettings
    {
        public int LandingPageId { get; set; }
        public string Directory { get; set; }
        public string PageTitle { get; set; }
        public string RenderingStrategyName { get; set; }
        public int WizardFormTemplateId { get; set; }
        public int QDFFormTemplateId { get; set; }
        public Nullable<System.Guid> QDFPlacementToken { get; set; }
        public Nullable<int> InstitutionId { get; set; }
        public string InstitutionName { get; set; }
        public string FormCustomAttributes { get; set; }
        public bool ShowArrowsInMobileHeader { get; set; }
        public bool ShowSelectClearAllButton { get; set; }
        public Nullable<System.Guid> LandingPageTrackId { get; set; }
        public bool AllowsMinification { get; set; }
        public int WebsiteId { get; set; }
        public string DomainName { get; set; }
        public string DirectoryRoot { get; set; }
        public Nullable<System.Guid> WebsiteTrackId { get; set; }
        public int ApplicationId { get; set; }
        public string WebsiteJavascript { get; set; }
        public string GoogleTagManagerId { get; set; }
        public string ABTestingCode { get; set; }
        public bool SelectAllSmartMatchTCPA { get; set; }
        public bool IsNewTCPAExperience { get; set; }
        public bool LoadJornayaFirstStep { get; set; }
    }
}
