//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProspectResubmissions
    {
        public int SubmissionId { get; set; }
        public Nullable<int> ProspectId { get; set; }
        public string RequestInput { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string DesiredStartDate { get; set; }
        public int Templateid { get; set; }
        public Nullable<System.Guid> CampaignTrackId { get; set; }
        public System.Guid MatchResponseGUID { get; set; }
        public Nullable<System.Guid> TrackingSessionGuid { get; set; }
    }
}
