//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ProgramProductTemplate
    {
        public int TemplateId { get; set; }
        public int ProgramProductId { get; set; }
        public int ProgramId { get; set; }
        public int ProductId { get; set; }
    }
}
