//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.LeadEngine.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Nexus_Lead_Entities : DbContext
    {
        public Nexus_Lead_Entities()
            : base("name=Nexus_Lead_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BetaLead> BetaLeads { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<RawPostData> RawPostDatas { get; set; }
    }
}
