//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APILog
    {
        public int APILogId { get; set; }
        public Nullable<System.Guid> TrackID { get; set; }
        public string MethodName { get; set; }
        public string IPAddress { get; set; }
        public string BrowserInfo { get; set; }
        public string Referer { get; set; }
        public string RequestType { get; set; }
        public string PostData { get; set; }
        public string Response { get; set; }
        public int ResultCount { get; set; }
        public Nullable<System.DateTime> RequestTimeStamp { get; set; }
        public Nullable<System.DateTime> ResponseTimeStamp { get; set; }
        public Nullable<int> TotalResponseTime { get; set; }
        public Nullable<System.Guid> ResponseGuid { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public string OperationType { get; set; }
        public string ResponseBody { get; set; }
        public string OperationValue { get; set; }
    }
}
