//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCenter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallCenter()
        {
            this.CallCenterLeads = new HashSet<CallCenterLead>();
        }
    
        public int CallCenterId { get; set; }
        public string Name { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string CallCenterCode { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<bool> IsInternal { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallCenterLead> CallCenterLeads { get; set; }
    }
}
