//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCenterLead
    {
        public int CallCenterLeadId { get; set; }
        public decimal LeadId { get; set; }
        public Nullable<int> AgentId { get; set; }
        public string TSR { get; set; }
        public string DialerKey { get; set; }
        public Nullable<int> StoreFrontId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<int> CallCenterId { get; set; }
        public Nullable<int> ProspectFlowId { get; set; }
    
        public virtual StoreFront StoreFront { get; set; }
        public virtual CallCenter CallCenter { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
