//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignPeriod
    {
        public long CampaignPeriodId { get; set; }
        public long CampaignId { get; set; }
        public Nullable<System.DateTime> CampaignStartDate { get; set; }
        public Nullable<System.DateTime> CampaignEndDate { get; set; }
        public Nullable<short> PeriodTypeId { get; set; }
        public short CampaignStatusId { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid RowGuid { get; set; }
        public string Reason { get; set; }
    
        public virtual Campaign Campaign { get; set; }
        public virtual CampaignStatu CampaignStatu { get; set; }
    }
}
