//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Campaign()
        {
            this.CampaignPeriods = new HashSet<CampaignPeriod>();
        }
    
        public long CampaignId { get; set; }
        public System.Guid TrackId { get; set; }
        public string CampaignName { get; set; }
        public bool AutoRenewal { get; set; }
        public int ChannelId { get; set; }
        public Nullable<int> SubChannelId { get; set; }
        public Nullable<int> CostingModelId { get; set; }
        public Nullable<int> VendorId { get; set; }
        public bool UseDefaultProfiles { get; set; }
        public Nullable<int> LegacyCampaignID { get; set; }
        public int IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public string BaseLandingPageURL { get; set; }
        public bool IsOverrideDefaultValues { get; set; }
        public Nullable<int> ListingResultCount { get; set; }
        public int SubmissionCount { get; set; }
        public Nullable<int> BusinessModelId { get; set; }
        public Nullable<int> CampaignCoordinatorId { get; set; }
        public Nullable<int> PrimaryBuyerId { get; set; }
        public int ScrubRate { get; set; }
        public string Notes { get; set; }
        public int CampaignTypeId { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public bool HasExitPop { get; set; }
        public bool OverrideManualRating { get; set; }
        public Nullable<int> MarketingUnitId { get; set; }
        public int AdditionalQuestionsFlowTypeID { get; set; }
        public Nullable<int> LeadScoringTierLevel { get; set; }
        public bool LeadScoringProductSelectionEnabled { get; set; }
        public bool HasPreCheck { get; set; }
        public Nullable<int> MasterProfileID { get; set; }
        public Nullable<bool> LeadScoringProductUpsellEnabled { get; set; }
        public bool IsCrossSellALternateList { get; set; }
        public Nullable<bool> LeadScoringAddAdditionalSmartMatch { get; set; }
        public Nullable<bool> CampusAddAdditionalSmartMatch { get; set; }
        public Nullable<int> MaxNonFullDegreeCrossSell { get; set; }
        public int BusinessUnitId { get; set; }
        public string SubDeal { get; set; }
        public Nullable<decimal> VendorFee { get; set; }
        public bool BillByProspect { get; set; }
        public string CampaignTCPAMessageName { get; set; }
        public int ProgramWizardAdditionalQuestionsFlowTypeID { get; set; }
        public bool APIRateExceeded { get; set; }
        public bool HasLeaveBehind { get; set; }
        public Nullable<int> CampaignAPIMatchBehaviorId { get; set; }
        public Nullable<int> NumberOfOnlineBackfillOnGeoPages { get; set; }
        public bool HasXVerify { get; set; }
        public Nullable<bool> IsStep1 { get; set; }
        public Nullable<bool> IsInternalTransfer { get; set; }
        public Nullable<bool> JobSite { get; set; }
        public Nullable<bool> BPOTransfer { get; set; }
        public Nullable<bool> CECEligible { get; set; }
        public string CECLeadScore { get; set; }
        public bool CalculateRevShareByERPL { get; set; }
        public Nullable<int> RevenueSharePercentage { get; set; }
        public bool AllowRevShareRPL { get; set; }
        public bool ValidateTCPA { get; set; }
        public Nullable<int> OpenMailProfileId { get; set; }
    
        public virtual CampaignType CampaignType { get; set; }
        public virtual CampaignDetail CampaignDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignPeriod> CampaignPeriods { get; set; }
    }
}
