//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campus
    {
        public int CampusId { get; set; }
        public string Name { get; set; }
        public int InstitutionId { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public int CampusTypeId { get; set; }
        public Nullable<int> AllowableRadius { get; set; }
        public bool ProcessByRadius { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid Rowguid { get; set; }
        public Nullable<bool> IsImported { get; set; }
        public Nullable<int> OldId { get; set; }
        public string ECCampusId { get; set; }
        public Nullable<bool> ChangesToBePushed { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> InstitutionZoneId { get; set; }
        public Nullable<bool> NonFullDegreeCampus { get; set; }
        public string ClientCampusName { get; set; }
    
        public virtual Institution Institution { get; set; }
    }
}
