//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EddyApiLog
    {
        public int EddyApiLogId { get; set; }
        public Nullable<System.Guid> TrackID { get; set; }
        public string IPAddress { get; set; }
        public string Request { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> RequestTimeStamp { get; set; }
        public Nullable<System.DateTime> ResponseTimeStamp { get; set; }
        public Nullable<int> TotalResponseTime { get; set; }
        public Nullable<System.Guid> ResponseGuid { get; set; }
        public bool IsSuccessful { get; set; }
        public string ApiEndpoint { get; set; }
        public string FormattedMessage { get; set; }
        public Nullable<decimal> LeadId { get; set; }
        public Nullable<int> ProspectFlowId { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> EstimatedRevShare { get; set; }
    }
}
