//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostAndPostOptionFieldLog
    {
        public int HostAndPostOptionFieldLogId { get; set; }
        public int HostAndPostLogId { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
    
        public virtual HostAndPostLog HostAndPostLog { get; set; }
    }
}
