//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostAndPostLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostAndPostLog()
        {
            this.HostAndPostOptionFieldLogs = new HashSet<HostAndPostOptionFieldLog>();
        }
    
        public int HostAndPostLogId { get; set; }
        public string IPAddress { get; set; }
        public string BrowserInfo { get; set; }
        public string Referer { get; set; }
        public string RequestType { get; set; }
        public string PostData { get; set; }
        public string Response { get; set; }
        public bool IsSuccess { get; set; }
        public bool IsBeta { get; set; }
        public string UID { get; set; }
        public Nullable<System.DateTime> RequestTimeStamp { get; set; }
        public Nullable<System.DateTime> ResponseTimeStamp { get; set; }
        public Nullable<int> TotalResponseTime { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<System.Guid> TrackID { get; set; }
        public Nullable<int> LogTypeId { get; set; }
        public string ExternalSystemId { get; set; }
        public string ServerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HostAndPostOptionFieldLog> HostAndPostOptionFieldLogs { get; set; }
    }
}
