//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Institution()
        {
            this.Programs = new HashSet<Program>();
            this.Campus = new HashSet<Campus>();
            this.ClientRelationships = new HashSet<ClientRelationship>();
        }
    
        public int InstitutionId { get; set; }
        public string PartnerCode { get; set; }
        public string Name { get; set; }
        public string RegistrationDetails { get; set; }
        public string OnCampusRequirements { get; set; }
        public string CalendarTypeOnline { get; set; }
        public string ComputerRequirement { get; set; }
        public string LearningFormatOnline { get; set; }
        public Nullable<bool> FinancialAid { get; set; }
        public Nullable<bool> Scholarships { get; set; }
        public string LoansOffered { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid RowGuid { get; set; }
        public string GeographicComments { get; set; }
        public Nullable<int> CarnegieClassificationId { get; set; }
        public string ComplianceType { get; set; }
        public string ComplianceContent { get; set; }
        public string FinancialAidDescription { get; set; }
        public string ScholarshipDescription { get; set; }
        public string TotalEnrollmentTotal { get; set; }
        public Nullable<int> GreatPlainsInstitutionID { get; set; }
        public Nullable<int> AccreditationTypeId { get; set; }
        public Nullable<int> InstitutionIncorporationTypeId { get; set; }
        public Nullable<int> InstitutionLeadTypeId { get; set; }
        public bool ThirdPartyContactAllowed { get; set; }
        public Nullable<double> LocaleID { get; set; }
        public string AcademicYearBeginMonth { get; set; }
        public string AcademicYearBeginDay { get; set; }
        public Nullable<bool> IsFaithBased { get; set; }
        public string AccreditationDescription { get; set; }
        public Nullable<bool> HasAdditionalScript { get; set; }
        public Nullable<bool> IsMilitaryFriendly { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campus> Campus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRelationship> ClientRelationships { get; set; }
    }
}
