//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryStatus
    {
        public int MilitaryStatusId { get; set; }
        public string MilitaryStatusName { get; set; }
        public string MilitaryStatusDescription { get; set; }
        public string LegacyMilitaryStatusName { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.Guid RowGuid { get; set; }
        public Nullable<bool> IsForEddyForms { get; set; }
    }
}
