//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class USZipCodeAreaCodeMerge
    {
        public int USZipCodeAreaCodeMergeID { get; set; }
        public string ZipCode { get; set; }
        public string ZipCodeType { get; set; }
        public string City { get; set; }
        public string CityType { get; set; }
        public string County { get; set; }
        public string CountyFIPS { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string TimeZone { get; set; }
        public string UTC { get; set; }
        public string DST { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string NPA { get; set; }
        public string NXX { get; set; }
        public string MSA { get; set; }
        public string PMSA { get; set; }
        public string LATA { get; set; }
        public string CELL { get; set; }
    }
}
