//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorAPISetting
    {
        public int VendorAPISettingId { get; set; }
        public string Setting_Key { get; set; }
        public string Setting_Value { get; set; }
        public string Setting_Type { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
