//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_EDDY_GET_ZipCodes
    {
        public string ZipCodes { get; set; }
        public int CampusId { get; set; }
    }
}
