//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_EMSLead
    {
        public long LeadId { get; set; }
        public Nullable<decimal> ISLeadId { get; set; }
        public string ExternalId { get; set; }
        public string FirstName { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public System.Guid LeadGUID { get; set; }
        public int InstitutionId { get; set; }
        public int LeadStateId { get; set; }
        public string ClosedReasonCode { get; set; }
        public string ClientApplicationDegreeName { get; set; }
        public string CustomFields { get; set; }
        public string ClientRegistered { get; set; }
        public string ClientInitialStartTerm { get; set; }
        public string ClientNotes { get; set; }
        public string ClientStatus { get; set; }
        public string ClientApplicationStartTerm { get; set; }
        public string PendingApplicationChecklistItems { get; set; }
        public string CompletedApplicationChecklistItems { get; set; }
        public Nullable<System.DateTime> ClientApplicationDate { get; set; }
        public Nullable<System.DateTime> ClientInterviewDate { get; set; }
        public Nullable<System.DateTime> ClientStartDate { get; set; }
        public Nullable<System.DateTime> ClientStartReceivedDate { get; set; }
        public Nullable<System.DateTime> ClientContactDate { get; set; }
        public Nullable<System.DateTime> ClientEnrollDate { get; set; }
        public Nullable<System.DateTime> ClientApplicationStartDate { get; set; }
        public Nullable<System.DateTime> ClientAdmitDate { get; set; }
        public Nullable<System.DateTime> ClientAppointmentDate { get; set; }
        public Nullable<System.DateTime> ClientQualifiedDate { get; set; }
        public Nullable<System.DateTime> ClientGraduateDate { get; set; }
        public Nullable<System.DateTime> ClientFirstTermPersistDate { get; set; }
        public Nullable<System.DateTime> ClientFAFSAReceivedDate { get; set; }
        public Nullable<System.DateTime> ClientApplicationSubmittedDate { get; set; }
        public Nullable<System.DateTime> ClientDepositDate { get; set; }
        public Nullable<System.DateTime> ClientApplicationDeniedDate { get; set; }
        public string LastName { get; set; }
    }
}
