//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.Vendor.DataAccess.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Matching_ProgramProduct_Prod
    {
        public int ProgramProductId { get; set; }
        public int InstitutionId { get; set; }
        public int CampusId { get; set; }
        public int ProgramId { get; set; }
        public int ClientRelationshipId { get; set; }
        public int ProductId { get; set; }
        public int ClientRelationProductMappingId { get; set; }
        public int ClientCampusRelationshipId { get; set; }
        public int ClientCampusProductMappingId { get; set; }
        public int PsiId { get; set; }
        public int ProgramLevelId { get; set; }
        public int ProgramTypeId { get; set; }
        public int ProgramCampusTypeId { get; set; }
        public int CampusCampusTypeId { get; set; }
        public Nullable<bool> IncludeAllZipCodes { get; set; }
        public Nullable<bool> ProgramProductUseZipCodeRules { get; set; }
        public Nullable<int> ProgramProductAllowableRadius { get; set; }
        public string ProgramProductRadiusZipCode { get; set; }
        public Nullable<bool> ProgramProductZipCodeInclusion { get; set; }
        public Nullable<bool> ProgramProductZipCodeExclusion { get; set; }
        public bool CanSmartMatch { get; set; }
        public bool IsHybrid { get; set; }
        public bool InquiryDisabled { get; set; }
        public Nullable<int> ProgramDisplayGroupId { get; set; }
        public string ClickThroughURL { get; set; }
        public bool ShowLeadShareTwoU { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> IntensiveProgramLanguageId { get; set; }
        public Nullable<int> SABSRAPosition_PSI { get; set; }
        public Nullable<bool> ExcludeMatch1plusForFinAid { get; set; }
        public int IsNonProfit { get; set; }
        public Nullable<int> DegreeAcronymId { get; set; }
        public bool AllowCrossSell { get; set; }
        public Nullable<int> CampusOptionGroupId { get; set; }
        public string AdvertiserId { get; set; }
        public Nullable<bool> UpsellOutboundTitanium { get; set; }
        public string CustomTCPA { get; set; }
        public string CustomContactCenterTCPA { get; set; }
    }
}
