//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.ValidationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultItemDTO", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.Validation.DTO.Extended")]
    [System.SerializableAttribute()]
    public partial class ResultItemDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelectedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Selected {
            get {
                return this.SelectedField;
            }
            set {
                if ((this.SelectedField.Equals(value) != true)) {
                    this.SelectedField = value;
                    this.RaisePropertyChanged("Selected");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.Validation.IPUtils")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IPEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IPStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IPEnd {
            get {
                return this.IPEndField;
            }
            set {
                if ((this.IPEndField.Equals(value) != true)) {
                    this.IPEndField = value;
                    this.RaisePropertyChanged("IPEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IPStart {
            get {
                return this.IPStartField;
            }
            set {
                if ((this.IPStartField.Equals(value) != true)) {
                    this.IPStartField = value;
                    this.RaisePropertyChanged("IPStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateCode {
            get {
                return this.StateCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StateCodeField, value) != true)) {
                    this.StateCodeField = value;
                    this.RaisePropertyChanged("StateCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidationService.IValidationService")]
    public interface IValidationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCityStateCountry", ReplyAction="http://tempuri.org/IValidationService/GetCityStateCountryResponse")]
        System.Collections.Generic.KeyValuePair<string, string>[] GetCityStateCountry(string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCityStateCountry", ReplyAction="http://tempuri.org/IValidationService/GetCityStateCountryResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, string>[]> GetCityStateCountryAsync(string ZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ZipCodeStateCountryCheck", ReplyAction="http://tempuri.org/IValidationService/ZipCodeStateCountryCheckResponse")]
        bool ZipCodeStateCountryCheck(string ZipCode, string CountryCode, string StateCode, bool ZipOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ZipCodeStateCountryCheck", ReplyAction="http://tempuri.org/IValidationService/ZipCodeStateCountryCheckResponse")]
        System.Threading.Tasks.Task<bool> ZipCodeStateCountryCheckAsync(string ZipCode, string CountryCode, string StateCode, bool ZipOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ProfanityCheck", ReplyAction="http://tempuri.org/IValidationService/ProfanityCheckResponse")]
        bool ProfanityCheck(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/ProfanityCheck", ReplyAction="http://tempuri.org/IValidationService/ProfanityCheckResponse")]
        System.Threading.Tasks.Task<bool> ProfanityCheckAsync(string Value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/PhoneCheck", ReplyAction="http://tempuri.org/IValidationService/PhoneCheckResponse")]
        bool PhoneCheck(string PhoneNumber, string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/PhoneCheck", ReplyAction="http://tempuri.org/IValidationService/PhoneCheckResponse")]
        System.Threading.Tasks.Task<bool> PhoneCheckAsync(string PhoneNumber, string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/EmailCheck", ReplyAction="http://tempuri.org/IValidationService/EmailCheckResponse")]
        bool EmailCheck(string EmailAddress, int EmailVerificationLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/EmailCheck", ReplyAction="http://tempuri.org/IValidationService/EmailCheckResponse")]
        System.Threading.Tasks.Task<bool> EmailCheckAsync(string EmailAddress, int EmailVerificationLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetStatesByCountry", ReplyAction="http://tempuri.org/IValidationService/GetStatesByCountryResponse")]
        System.Tuple<int, string, string>[] GetStatesByCountry(string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetStatesByCountry", ReplyAction="http://tempuri.org/IValidationService/GetStatesByCountryResponse")]
        System.Threading.Tasks.Task<System.Tuple<int, string, string>[]> GetStatesByCountryAsync(string CountryCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetISMapping", ReplyAction="http://tempuri.org/IValidationService/GetISMappingResponse")]
        string GetISMapping(string set, string category, string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetISMapping", ReplyAction="http://tempuri.org/IValidationService/GetISMappingResponse")]
        System.Threading.Tasks.Task<string> GetISMappingAsync(string set, string category, string source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCity", ReplyAction="http://tempuri.org/IValidationService/GetCityResponse")]
        string GetCity(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCity", ReplyAction="http://tempuri.org/IValidationService/GetCityResponse")]
        System.Threading.Tasks.Task<string> GetCityAsync(string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountriesResult", ReplyAction="http://tempuri.org/IValidationService/GetCountriesResultResponse")]
        EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[] GetCountriesResult(string state, string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountriesResult", ReplyAction="http://tempuri.org/IValidationService/GetCountriesResultResponse")]
        System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[]> GetCountriesResultAsync(string state, string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetStatesResult", ReplyAction="http://tempuri.org/IValidationService/GetStatesResultResponse")]
        EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[] GetStatesResult(string country, string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetStatesResult", ReplyAction="http://tempuri.org/IValidationService/GetStatesResultResponse")]
        System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[]> GetStatesResultAsync(string country, string zipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountryIdStateId", ReplyAction="http://tempuri.org/IValidationService/GetCountryIdStateIdResponse")]
        System.Tuple<System.Nullable<int>, System.Nullable<int>> GetCountryIdStateId(string countryCode, string stateShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountryIdStateId", ReplyAction="http://tempuri.org/IValidationService/GetCountryIdStateIdResponse")]
        System.Threading.Tasks.Task<System.Tuple<System.Nullable<int>, System.Nullable<int>>> GetCountryIdStateIdAsync(string countryCode, string stateShortName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountryCodeByIP", ReplyAction="http://tempuri.org/IValidationService/GetCountryCodeByIPResponse")]
        string GetCountryCodeByIP(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetCountryCodeByIP", ReplyAction="http://tempuri.org/IValidationService/GetCountryCodeByIPResponse")]
        System.Threading.Tasks.Task<string> GetCountryCodeByIPAsync(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetLocationByIP", ReplyAction="http://tempuri.org/IValidationService/GetLocationByIPResponse")]
        EDDY.IS.FormsEngine.ValidationService.Location GetLocationByIP(string ip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValidationService/GetLocationByIP", ReplyAction="http://tempuri.org/IValidationService/GetLocationByIPResponse")]
        System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.Location> GetLocationByIPAsync(string ip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValidationServiceChannel : EDDY.IS.FormsEngine.ValidationService.IValidationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidationServiceClient : System.ServiceModel.ClientBase<EDDY.IS.FormsEngine.ValidationService.IValidationService>, EDDY.IS.FormsEngine.ValidationService.IValidationService {
        
        public ValidationServiceClient() {
        }
        
        public ValidationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] GetCityStateCountry(string ZipCode) {
            return base.Channel.GetCityStateCountry(ZipCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, string>[]> GetCityStateCountryAsync(string ZipCode) {
            return base.Channel.GetCityStateCountryAsync(ZipCode);
        }
        
        public bool ZipCodeStateCountryCheck(string ZipCode, string CountryCode, string StateCode, bool ZipOnly) {
            return base.Channel.ZipCodeStateCountryCheck(ZipCode, CountryCode, StateCode, ZipOnly);
        }
        
        public System.Threading.Tasks.Task<bool> ZipCodeStateCountryCheckAsync(string ZipCode, string CountryCode, string StateCode, bool ZipOnly) {
            return base.Channel.ZipCodeStateCountryCheckAsync(ZipCode, CountryCode, StateCode, ZipOnly);
        }
        
        public bool ProfanityCheck(string Value) {
            return base.Channel.ProfanityCheck(Value);
        }
        
        public System.Threading.Tasks.Task<bool> ProfanityCheckAsync(string Value) {
            return base.Channel.ProfanityCheckAsync(Value);
        }
        
        public bool PhoneCheck(string PhoneNumber, string CountryCode) {
            return base.Channel.PhoneCheck(PhoneNumber, CountryCode);
        }
        
        public System.Threading.Tasks.Task<bool> PhoneCheckAsync(string PhoneNumber, string CountryCode) {
            return base.Channel.PhoneCheckAsync(PhoneNumber, CountryCode);
        }
        
        public bool EmailCheck(string EmailAddress, int EmailVerificationLevel) {
            return base.Channel.EmailCheck(EmailAddress, EmailVerificationLevel);
        }
        
        public System.Threading.Tasks.Task<bool> EmailCheckAsync(string EmailAddress, int EmailVerificationLevel) {
            return base.Channel.EmailCheckAsync(EmailAddress, EmailVerificationLevel);
        }
        
        public System.Tuple<int, string, string>[] GetStatesByCountry(string CountryCode) {
            return base.Channel.GetStatesByCountry(CountryCode);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<int, string, string>[]> GetStatesByCountryAsync(string CountryCode) {
            return base.Channel.GetStatesByCountryAsync(CountryCode);
        }
        
        public string GetISMapping(string set, string category, string source) {
            return base.Channel.GetISMapping(set, category, source);
        }
        
        public System.Threading.Tasks.Task<string> GetISMappingAsync(string set, string category, string source) {
            return base.Channel.GetISMappingAsync(set, category, source);
        }
        
        public string GetCity(string zipCode) {
            return base.Channel.GetCity(zipCode);
        }
        
        public System.Threading.Tasks.Task<string> GetCityAsync(string zipCode) {
            return base.Channel.GetCityAsync(zipCode);
        }
        
        public EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[] GetCountriesResult(string state, string zipCode) {
            return base.Channel.GetCountriesResult(state, zipCode);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[]> GetCountriesResultAsync(string state, string zipCode) {
            return base.Channel.GetCountriesResultAsync(state, zipCode);
        }
        
        public EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[] GetStatesResult(string country, string zipCode) {
            return base.Channel.GetStatesResult(country, zipCode);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.ResultItemDTO[]> GetStatesResultAsync(string country, string zipCode) {
            return base.Channel.GetStatesResultAsync(country, zipCode);
        }
        
        public System.Tuple<System.Nullable<int>, System.Nullable<int>> GetCountryIdStateId(string countryCode, string stateShortName) {
            return base.Channel.GetCountryIdStateId(countryCode, stateShortName);
        }
        
        public System.Threading.Tasks.Task<System.Tuple<System.Nullable<int>, System.Nullable<int>>> GetCountryIdStateIdAsync(string countryCode, string stateShortName) {
            return base.Channel.GetCountryIdStateIdAsync(countryCode, stateShortName);
        }
        
        public string GetCountryCodeByIP(string ip) {
            return base.Channel.GetCountryCodeByIP(ip);
        }
        
        public System.Threading.Tasks.Task<string> GetCountryCodeByIPAsync(string ip) {
            return base.Channel.GetCountryCodeByIPAsync(ip);
        }
        
        public EDDY.IS.FormsEngine.ValidationService.Location GetLocationByIP(string ip) {
            return base.Channel.GetLocationByIP(ip);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.FormsEngine.ValidationService.Location> GetLocationByIPAsync(string ip) {
            return base.Channel.GetLocationByIPAsync(ip);
        }
    }
}
