//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.LeadPingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationRequest", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ValidationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.InstitutionConfig[] InsitutionConfigsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.ProspectInfo ProspectInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.InstitutionConfig[] InsitutionConfigs {
            get {
                return this.InsitutionConfigsField;
            }
            set {
                if ((object.ReferenceEquals(this.InsitutionConfigsField, value) != true)) {
                    this.InsitutionConfigsField = value;
                    this.RaisePropertyChanged("InsitutionConfigs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.ProspectInfo ProspectInfo {
            get {
                return this.ProspectInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProspectInfoField, value) != true)) {
                    this.ProspectInfoField = value;
                    this.RaisePropertyChanged("ProspectInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProspectInfo", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ProspectInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CountryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EducationLevelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HighSchoolGradyearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MilitaryAffiliationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MilitaryStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Phone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountryID {
            get {
                return this.CountryIDField;
            }
            set {
                if ((this.CountryIDField.Equals(value) != true)) {
                    this.CountryIDField = value;
                    this.RaisePropertyChanged("CountryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EducationLevelID {
            get {
                return this.EducationLevelIDField;
            }
            set {
                if ((this.EducationLevelIDField.Equals(value) != true)) {
                    this.EducationLevelIDField = value;
                    this.RaisePropertyChanged("EducationLevelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HighSchoolGradyear {
            get {
                return this.HighSchoolGradyearField;
            }
            set {
                if ((this.HighSchoolGradyearField.Equals(value) != true)) {
                    this.HighSchoolGradyearField = value;
                    this.RaisePropertyChanged("HighSchoolGradyear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MilitaryAffiliation {
            get {
                return this.MilitaryAffiliationField;
            }
            set {
                if ((this.MilitaryAffiliationField.Equals(value) != true)) {
                    this.MilitaryAffiliationField = value;
                    this.RaisePropertyChanged("MilitaryAffiliation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MilitaryStatusId {
            get {
                return this.MilitaryStatusIdField;
            }
            set {
                if ((this.MilitaryStatusIdField.Equals(value) != true)) {
                    this.MilitaryStatusIdField = value;
                    this.RaisePropertyChanged("MilitaryStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone1 {
            get {
                return this.Phone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone1Field, value) != true)) {
                    this.Phone1Field = value;
                    this.RaisePropertyChanged("Phone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone2 {
            get {
                return this.Phone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Phone2Field, value) != true)) {
                    this.Phone2Field = value;
                    this.RaisePropertyChanged("Phone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StateID {
            get {
                return this.StateIDField;
            }
            set {
                if ((this.StateIDField.Equals(value) != true)) {
                    this.StateIDField = value;
                    this.RaisePropertyChanged("StateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress {
            get {
                return this.StreetAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAddressField, value) != true)) {
                    this.StreetAddressField = value;
                    this.RaisePropertyChanged("StreetAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InstitutionConfig", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class InstitutionConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.CampusConfig[] CampusConfigsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.CampusConfig[] CampusConfigs {
            get {
                return this.CampusConfigsField;
            }
            set {
                if ((object.ReferenceEquals(this.CampusConfigsField, value) != true)) {
                    this.CampusConfigsField = value;
                    this.RaisePropertyChanged("CampusConfigs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampusConfig", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class CampusConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MilesFromUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CampusID {
            get {
                return this.CampusIDField;
            }
            set {
                if ((this.CampusIDField.Equals(value) != true)) {
                    this.CampusIDField = value;
                    this.RaisePropertyChanged("CampusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MilesFromUser {
            get {
                return this.MilesFromUserField;
            }
            set {
                if ((this.MilesFromUserField.Equals(value) != true)) {
                    this.MilesFromUserField = value;
                    this.RaisePropertyChanged("MilesFromUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class ValidationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.FailedInstitutionResponse[] ImmediateResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.FailedInstitutionResponse[] RelatedResponsesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.ServiceCallStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.FailedInstitutionResponse[] ImmediateResponses {
            get {
                return this.ImmediateResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.ImmediateResponsesField, value) != true)) {
                    this.ImmediateResponsesField = value;
                    this.RaisePropertyChanged("ImmediateResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.FailedInstitutionResponse[] RelatedResponses {
            get {
                return this.RelatedResponsesField;
            }
            set {
                if ((object.ReferenceEquals(this.RelatedResponsesField, value) != true)) {
                    this.RelatedResponsesField = value;
                    this.RaisePropertyChanged("RelatedResponses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerMessage {
            get {
                return this.ServerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerMessageField, value) != true)) {
                    this.ServerMessageField = value;
                    this.RaisePropertyChanged("ServerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.ServiceCallStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailedInstitutionResponse", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    [System.SerializableAttribute()]
    public partial class FailedInstitutionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CampusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InstitutionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ProductIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EDDY.IS.FormsEngine.LeadPingService.Type TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CampusID {
            get {
                return this.CampusIDField;
            }
            set {
                if ((this.CampusIDField.Equals(value) != true)) {
                    this.CampusIDField = value;
                    this.RaisePropertyChanged("CampusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InstitutionID {
            get {
                return this.InstitutionIDField;
            }
            set {
                if ((this.InstitutionIDField.Equals(value) != true)) {
                    this.InstitutionIDField = value;
                    this.RaisePropertyChanged("InstitutionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInternal {
            get {
                return this.IsInternalField;
            }
            set {
                if ((this.IsInternalField.Equals(value) != true)) {
                    this.IsInternalField = value;
                    this.RaisePropertyChanged("IsInternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] ProductIDs {
            get {
                return this.ProductIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDsField, value) != true)) {
                    this.ProductIDsField = value;
                    this.RaisePropertyChanged("ProductIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EDDY.IS.FormsEngine.LeadPingService.Type Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCallStatus", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    public enum ServiceCallStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sucess = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Type", Namespace="http://schemas.datacontract.org/2004/07/EDDY.IS.LeadPing.Service.V3.DTO")]
    public enum Type : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScoreCheck = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ValidationCheck = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LeadPingService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RetrieveInstitutionValidationErrors", ReplyAction="http://tempuri.org/IService/RetrieveInstitutionValidationErrorsResponse")]
        EDDY.IS.FormsEngine.LeadPingService.ValidationResponse RetrieveInstitutionValidationErrors(EDDY.IS.FormsEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RetrieveInstitutionValidationErrors", ReplyAction="http://tempuri.org/IService/RetrieveInstitutionValidationErrorsResponse")]
        System.Threading.Tasks.Task<EDDY.IS.FormsEngine.LeadPingService.ValidationResponse> RetrieveInstitutionValidationErrorsAsync(EDDY.IS.FormsEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FireEmailDupeCheck", ReplyAction="http://tempuri.org/IService/FireEmailDupeCheckResponse")]
        void FireEmailDupeCheck(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FireEmailDupeCheck", ReplyAction="http://tempuri.org/IService/FireEmailDupeCheckResponse")]
        System.Threading.Tasks.Task FireEmailDupeCheckAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FirePhoneDupeCheck", ReplyAction="http://tempuri.org/IService/FirePhoneDupeCheckResponse")]
        void FirePhoneDupeCheck(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/FirePhoneDupeCheck", ReplyAction="http://tempuri.org/IService/FirePhoneDupeCheckResponse")]
        System.Threading.Tasks.Task FirePhoneDupeCheckAsync(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsMobile", ReplyAction="http://tempuri.org/IService/IsMobileResponse")]
        bool IsMobile(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/IsMobile", ReplyAction="http://tempuri.org/IService/IsMobileResponse")]
        System.Threading.Tasks.Task<bool> IsMobileAsync(string Phone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearCache", ReplyAction="http://tempuri.org/IService/ClearCacheResponse")]
        string ClearCache(string ServiceKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ClearCache", ReplyAction="http://tempuri.org/IService/ClearCacheResponse")]
        System.Threading.Tasks.Task<string> ClearCacheAsync(string ServiceKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : EDDY.IS.FormsEngine.LeadPingService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EDDY.IS.FormsEngine.LeadPingService.IService>, EDDY.IS.FormsEngine.LeadPingService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EDDY.IS.FormsEngine.LeadPingService.ValidationResponse RetrieveInstitutionValidationErrors(EDDY.IS.FormsEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey) {
            return base.Channel.RetrieveInstitutionValidationErrors(ValidationRequest, ServiceKey);
        }
        
        public System.Threading.Tasks.Task<EDDY.IS.FormsEngine.LeadPingService.ValidationResponse> RetrieveInstitutionValidationErrorsAsync(EDDY.IS.FormsEngine.LeadPingService.ValidationRequest ValidationRequest, string ServiceKey) {
            return base.Channel.RetrieveInstitutionValidationErrorsAsync(ValidationRequest, ServiceKey);
        }
        
        public void FireEmailDupeCheck(string Email) {
            base.Channel.FireEmailDupeCheck(Email);
        }
        
        public System.Threading.Tasks.Task FireEmailDupeCheckAsync(string Email) {
            return base.Channel.FireEmailDupeCheckAsync(Email);
        }
        
        public void FirePhoneDupeCheck(string Phone) {
            base.Channel.FirePhoneDupeCheck(Phone);
        }
        
        public System.Threading.Tasks.Task FirePhoneDupeCheckAsync(string Phone) {
            return base.Channel.FirePhoneDupeCheckAsync(Phone);
        }
        
        public bool IsMobile(string Phone) {
            return base.Channel.IsMobile(Phone);
        }
        
        public System.Threading.Tasks.Task<bool> IsMobileAsync(string Phone) {
            return base.Channel.IsMobileAsync(Phone);
        }
        
        public string ClearCache(string ServiceKey) {
            return base.Channel.ClearCache(ServiceKey);
        }
        
        public System.Threading.Tasks.Task<string> ClearCacheAsync(string ServiceKey) {
            return base.Channel.ClearCacheAsync(ServiceKey);
        }
    }
}
