//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class CampaignDTO
    {
        [DataMember]
    	public long CampaignId { get; set; }
        [DataMember]
    	public System.Guid TrackId { get; set; }
        [DataMember]
    	public string CampaignName { get; set; }
        [DataMember]
    	public bool AutoRenewal { get; set; }
        [DataMember]
    	public int ChannelId { get; set; }
        [DataMember]
    	public Nullable<int> SubChannelId { get; set; }
        [DataMember]
    	public Nullable<int> CostingModelId { get; set; }
        [DataMember]
    	public Nullable<int> VendorId { get; set; }
        [DataMember]
    	public bool UseDefaultProfiles { get; set; }
        [DataMember]
    	public Nullable<int> LegacyCampaignID { get; set; }
        [DataMember]
    	public int IsEnabled { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public System.Guid RowGuid { get; set; }
        [DataMember]
    	public Nullable<int> ApplicationId { get; set; }
        [DataMember]
    	public Nullable<int> OfferId { get; set; }
        [DataMember]
    	public string BaseLandingPageURL { get; set; }
        [DataMember]
    	public bool IsOverrideDefaultValues { get; set; }
        [DataMember]
    	public Nullable<int> ListingResultCount { get; set; }
        [DataMember]
    	public int SubmissionCount { get; set; }
        [DataMember]
    	public Nullable<int> BusinessModelId { get; set; }
        [DataMember]
    	public Nullable<int> CampaignCoordinatorId { get; set; }
        [DataMember]
    	public Nullable<int> PrimaryBuyerId { get; set; }
        [DataMember]
    	public int ScrubRate { get; set; }
        [DataMember]
    	public string Notes { get; set; }
        [DataMember]
    	public int CampaignTypeId { get; set; }
        [DataMember]
    	public Nullable<bool> IsDefault { get; set; }
        [DataMember]
    	public bool HasExitPop { get; set; }
        [DataMember]
    	public bool OverrideManualRating { get; set; }
        [DataMember]
    	public Nullable<int> MarketingUnitId { get; set; }
        [DataMember]
    	public int AdditionalQuestionsFlowTypeID { get; set; }
        [DataMember]
    	public Nullable<int> LeadScoringTierLevel { get; set; }
        [DataMember]
    	public bool LeadScoringProductSelectionEnabled { get; set; }
        [DataMember]
    	public bool HasPreCheck { get; set; }
        [DataMember]
    	public Nullable<int> MasterProfileID { get; set; }
        [DataMember]
    	public Nullable<bool> LeadScoringProductUpsellEnabled { get; set; }
        [DataMember]
    	public bool IsCrossSellALternateList { get; set; }
        [DataMember]
    	public Nullable<bool> LeadScoringAddAdditionalSmartMatch { get; set; }
        [DataMember]
    	public Nullable<bool> CampusAddAdditionalSmartMatch { get; set; }
        [DataMember]
    	public Nullable<int> MaxNonFullDegreeCrossSell { get; set; }
        [DataMember]
    	public int BusinessUnitId { get; set; }
        [DataMember]
    	public string SubDeal { get; set; }
        [DataMember]
    	public Nullable<decimal> VendorFee { get; set; }
        [DataMember]
    	public bool BillByProspect { get; set; }
        [DataMember]
    	public string CampaignTCPAMessageName { get; set; }
        [DataMember]
    	public int ProgramWizardAdditionalQuestionsFlowTypeID { get; set; }
        [DataMember]
    	public bool APIRateExceeded { get; set; }
        [DataMember]
    	public bool HasLeaveBehind { get; set; }
        [DataMember]
    	public Nullable<int> CampaignAPIMatchBehaviorId { get; set; }
        [DataMember]
    	public Nullable<int> NumberOfOnlineBackfillOnGeoPages { get; set; }
        [DataMember]
    	public bool HasXVerify { get; set; }
        [DataMember]
    	public string CECLeadScore { get; set; }
        [DataMember]
    	public Nullable<bool> IsStep1 { get; set; }
        [DataMember]
    	public Nullable<bool> IsInternalTransfer { get; set; }
        [DataMember]
    	public Nullable<bool> JobSite { get; set; }
        [DataMember]
    	public Nullable<bool> BPOTransfer { get; set; }
        [DataMember]
    	public Nullable<bool> CECEligible { get; set; }
        [DataMember]
    	public bool AllowRevShareRPL { get; set; }
        [DataMember]
    	public bool CalculateRevShareByERPL { get; set; }
        [DataMember]
    	public Nullable<int> RevenueSharePercentage { get; set; }
        [DataMember]
    	public bool ValidateTCPA { get; set; }
        [DataMember]
    	public Nullable<int> OpenMailProfileId { get; set; }
    
        [DataMember]
    	public virtual OpenMailProfileDTO OpenMailProfile { get; set; }
    }
}
