//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
        
    [Serializable]
    [DataContract]
    public partial class EDDY_FE_GetCreativeURLs_ResultDTO
    {
        [DataMember]
    	public string InitiatingURL { get; set; }
        [DataMember]
    	public string LandingURL { get; set; }
        [DataMember]
    	public string CallCenterURL { get; set; }
        [DataMember]
        public string VideoURL { get; set; }

    }
}
