//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class ErrorMessageDTO
    {
        [DataMember]
    	public int ErrorMessageId { get; set; }
        [DataMember]
    	public int StandardControlTypeId { get; set; }
        [DataMember]
    	public int ErrorCodeId { get; set; }
        [DataMember]
    	public string Message { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public Nullable<int> TemplateTypeId { get; set; }
    
        [DataMember]
    	public virtual ErrorCodeDTO ErrorCode { get; set; }
        [DataMember]
    	public virtual TemplateTypeDTO TemplateType { get; set; }
    }
}
