//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class KVCodeDataDTO
    {
        [DataMember]
    	public int KVCodeDataId { get; set; }
        [DataMember]
    	public int KVCodeId { get; set; }
        [DataMember]
    	public string Key { get; set; }
        [DataMember]
    	public string Value { get; set; }
        [DataMember]
    	public Nullable<decimal> StartRange { get; set; }
        [DataMember]
    	public Nullable<decimal> EndRange { get; set; }
        [DataMember]
    	public Nullable<int> Sequence { get; set; }
        [DataMember]
    	public bool IsEnabled { get; set; }
        [DataMember]
    	public bool IsDeleted { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public Nullable<int> InstitutionId { get; set; }
    
        [DataMember]
    	public virtual KVCodeDTO KVCode { get; set; }
    }
}
