//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class ProgramProductDTO
    {
        [DataMember]
    	public int ProgramProductId { get; set; }
        [DataMember]
    	public int ClientCampusProgramRelationshipID { get; set; }
        [DataMember]
    	public int ProductId { get; set; }
        [DataMember]
    	public string ProgramCode { get; set; }
        [DataMember]
    	public Nullable<int> AllowableRadius { get; set; }
        [DataMember]
    	public string RadiusZipCode { get; set; }
        [DataMember]
    	public Nullable<bool> IsZipCodeInclusionExclusionActive { get; set; }
        [DataMember]
    	public bool IsEnabled { get; set; }
        [DataMember]
    	public bool IsDeleted { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public System.Guid rowguid { get; set; }
        [DataMember]
    	public Nullable<bool> UseCCRGeoInfo { get; set; }
        [DataMember]
    	public Nullable<bool> IncludeAllZipCodes { get; set; }
        [DataMember]
    	public Nullable<bool> strategic { get; set; }
        [DataMember]
    	public Nullable<bool> IsImported { get; set; }
        [DataMember]
    	public Nullable<int> ecprogramid { get; set; }
        [DataMember]
    	public Nullable<bool> IsZipCodeInclusion { get; set; }
        [DataMember]
    	public Nullable<bool> IsZipCodeExclusion { get; set; }
        [DataMember]
    	public bool CanSmartmatch { get; set; }
        [DataMember]
    	public string DeliveryEmailRoutingAddress { get; set; }
    
        [DataMember]
    	public virtual ClientCampusProgramRelationshipDTO ClientCampusProgramRelationship { get; set; }
    }
}
