//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class ProgramLevelDTO
    {
        [DataMember]
    	public int ProgramLevelId { get; set; }
        [DataMember]
    	public string ProgramLevelName { get; set; }
        [DataMember]
    	public string ProgramLevelDescription { get; set; }
        [DataMember]
    	public bool IsEnabled { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public System.Guid RowGuid { get; set; }
        [DataMember]
    	public bool CanSmartmatch { get; set; }
        [DataMember]
    	public Nullable<int> ProgramLevelGroupId { get; set; }
        [DataMember]
    	public Nullable<bool> FullDegreeAllowed { get; set; }
        [DataMember]
    	public Nullable<bool> NonFullDegreeAllowed { get; set; }
        [DataMember]
    	public Nullable<int> DisplayOrder { get; set; }
    }
}
