//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class StandardControlCodeDTO
    {
        [DataMember]
    	public int StandardControlCodeId { get; set; }
        [DataMember]
    	public string Code { get; set; }
        [DataMember]
    	public string CSVCodeAlias { get; set; }
        [DataMember]
    	public bool IsSystemControl { get; set; }
        [DataMember]
    	public bool IsReportControl { get; set; }
        [DataMember]
    	public bool IsEnabled { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
    
        [DataMember]
    	public virtual ICollection<StandardControlCodeFilterDTO> StandardControlCodeFilters { get; set; }
        [DataMember]
    	public virtual ICollection<SubmissionDetailDTO> SubmissionDetails { get; set; }
        [DataMember]
    	public virtual ICollection<OpenMailRuleDTO> OpenMailRules { get; set; }
    }
}
