//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class StandardControlCodeFilterDTO
    {
        [DataMember]
    	public int StandardControlCodeFilterId { get; set; }
        [DataMember]
    	public int StandardControlCodeId { get; set; }
        [DataMember]
    	public int StandardControlCodeIdFilter { get; set; }
    
        [DataMember]
    	public virtual StandardControlCodeDTO StandardControlCodeFilterEntity { get; set; }
    }
}
