//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class SubmissionMatchResponseDTO
    {
        [DataMember]
    	public int SubmissionMatchResponseId { get; set; }
        [DataMember]
    	public int SubmissionId { get; set; }
        [DataMember]
    	public System.Guid MatchResponseGuid { get; set; }
        [DataMember]
    	public int MatchResponseTypeId { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
    
        [DataMember]
    	public virtual SubmissionDTO Submission { get; set; }
    }
}
