//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class TemplateDTO
    {
        [DataMember]
    	public int TemplateId { get; set; }
        [DataMember]
    	public string TemplateName { get; set; }
        [DataMember]
    	public string TemplateDescription { get; set; }
        [DataMember]
    	public bool IsDefaultTemplate { get; set; }
        [DataMember]
    	public bool IsSystemTemplate { get; set; }
        [DataMember]
    	public int TemplateTypeId { get; set; }
        [DataMember]
    	public bool IsEnabled { get; set; }
        [DataMember]
    	public System.DateTime CreatedDate { get; set; }
        [DataMember]
    	public int CreatedBy { get; set; }
        [DataMember]
    	public System.DateTime UpdatedDate { get; set; }
        [DataMember]
    	public int UpdatedBy { get; set; }
        [DataMember]
    	public bool InlineDropDowns { get; set; }
        [DataMember]
    	public bool ShowAllQuestionsOnFirstStep { get; set; }
        [DataMember]
    	public int BusinessDivisionId { get; set; }
        [DataMember]
    	public Nullable<int> InstitutionId { get; set; }
        [DataMember]
    	public bool SystemAllowedDoBTemplate { get; set; }
    
        [DataMember]
    	public virtual TemplateTypeDTO TemplateType { get; set; }
        [DataMember]
    	public virtual ICollection<TemplateAssignmentDTO> TemplateAssignments { get; set; }
        [DataMember]
    	public virtual ICollection<TemplateStepDTO> TemplateSteps { get; set; }
    }
}
