//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class TemplateApplicationOverrideDTO
    {
        [DataMember]
    	public int TemplateApplicationOverrideId { get; set; }
        [DataMember]
    	public int ApplicationId { get; set; }
        [DataMember]
    	public Nullable<int> PaidStatusTypeId { get; set; }
        [DataMember]
    	public int TemplateId { get; set; }
        [DataMember]
    	public Nullable<bool> IsEnabled { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> CreatedDate { get; set; }
        [DataMember]
    	public Nullable<int> CreatedBy { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> UpdatedDate { get; set; }
        [DataMember]
    	public Nullable<int> UpdatedBy { get; set; }
    }
}
