//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.DTO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    
    [Serializable]
    [DataContract]
    public partial class VW_ProspectResubmissionsDTO
    {
        [DataMember]
    	public int SubmissionId { get; set; }
        [DataMember]
    	public Nullable<int> ProspectId { get; set; }
        [DataMember]
    	public string RequestInput { get; set; }
        [DataMember]
    	public string State { get; set; }
        [DataMember]
    	public string Country { get; set; }
        [DataMember]
    	public string DesiredStartDate { get; set; }
        [DataMember]
    	public int Templateid { get; set; }
        [DataMember]
    	public Nullable<System.Guid> CampaignTrackId { get; set; }
        [DataMember]
    	public System.Guid MatchResponseGUID { get; set; }
        [DataMember]
    	public Nullable<System.Guid> TrackingSessionGuid { get; set; }
    }
}
