//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class CampaignMapper
    {
    	public static CampaignDTO ConvertToDTO(this Campaign Me){
    		return new CampaignDTO() {
    
    			CampaignId = Me.CampaignId,
    			TrackId = Me.TrackId,
    			CampaignName = Me.CampaignName,
    			AutoRenewal = Me.AutoRenewal,
    			ChannelId = Me.ChannelId,
    			SubChannelId = Me.SubChannelId,
    			CostingModelId = Me.CostingModelId,
    			VendorId = Me.VendorId,
    			UseDefaultProfiles = Me.UseDefaultProfiles,
    			LegacyCampaignID = Me.LegacyCampaignID,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			RowGuid = Me.RowGuid,
    			ApplicationId = Me.ApplicationId,
    			OfferId = Me.OfferId,
    			BaseLandingPageURL = Me.BaseLandingPageURL,
    			IsOverrideDefaultValues = Me.IsOverrideDefaultValues,
    			ListingResultCount = Me.ListingResultCount,
    			SubmissionCount = Me.SubmissionCount,
    			BusinessModelId = Me.BusinessModelId,
    			CampaignCoordinatorId = Me.CampaignCoordinatorId,
    			PrimaryBuyerId = Me.PrimaryBuyerId,
    			ScrubRate = Me.ScrubRate,
    			Notes = Me.Notes,
    			CampaignTypeId = Me.CampaignTypeId,
    			IsDefault = Me.IsDefault,
    			HasExitPop = Me.HasExitPop,
    			OverrideManualRating = Me.OverrideManualRating,
    			MarketingUnitId = Me.MarketingUnitId,
    			AdditionalQuestionsFlowTypeID = Me.AdditionalQuestionsFlowTypeID,
    			LeadScoringTierLevel = Me.LeadScoringTierLevel,
    			LeadScoringProductSelectionEnabled = Me.LeadScoringProductSelectionEnabled,
    			HasPreCheck = Me.HasPreCheck,
    			MasterProfileID = Me.MasterProfileID,
    			LeadScoringProductUpsellEnabled = Me.LeadScoringProductUpsellEnabled,
    			IsCrossSellALternateList = Me.IsCrossSellALternateList,
    			LeadScoringAddAdditionalSmartMatch = Me.LeadScoringAddAdditionalSmartMatch,
    			CampusAddAdditionalSmartMatch = Me.CampusAddAdditionalSmartMatch,
    			MaxNonFullDegreeCrossSell = Me.MaxNonFullDegreeCrossSell,
    			BusinessUnitId = Me.BusinessUnitId,
    			SubDeal = Me.SubDeal,
    			VendorFee = Me.VendorFee,
    			BillByProspect = Me.BillByProspect,
    			CampaignTCPAMessageName = Me.CampaignTCPAMessageName,
    			ProgramWizardAdditionalQuestionsFlowTypeID = Me.ProgramWizardAdditionalQuestionsFlowTypeID,
    			APIRateExceeded = Me.APIRateExceeded,
    			HasLeaveBehind = Me.HasLeaveBehind,
    			CampaignAPIMatchBehaviorId = Me.CampaignAPIMatchBehaviorId,
    			NumberOfOnlineBackfillOnGeoPages = Me.NumberOfOnlineBackfillOnGeoPages,
    			HasXVerify = Me.HasXVerify,
    			CECLeadScore = Me.CECLeadScore,
    			IsStep1 = Me.IsStep1,
    			IsInternalTransfer = Me.IsInternalTransfer,
    			JobSite = Me.JobSite,
    			BPOTransfer = Me.BPOTransfer,
    			CECEligible = Me.CECEligible,
    			AllowRevShareRPL = Me.AllowRevShareRPL,
    			CalculateRevShareByERPL = Me.CalculateRevShareByERPL,
    			RevenueSharePercentage = Me.RevenueSharePercentage,
    			ValidateTCPA = Me.ValidateTCPA,
    			OpenMailProfileId = Me.OpenMailProfileId,
    			OpenMailProfile = Me.OpenMailProfile!=null?Me.OpenMailProfile.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<CampaignDTO> ConvertToDTO(this ICollection<Campaign> Me)
    	{
    		ICollection<CampaignDTO> Result = new List<CampaignDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static Campaign ConvertToDataModel(this CampaignDTO Me){
    		return new Campaign() {
    
    			CampaignId = Me.CampaignId,
    			TrackId = Me.TrackId,
    			CampaignName = Me.CampaignName,
    			AutoRenewal = Me.AutoRenewal,
    			ChannelId = Me.ChannelId,
    			SubChannelId = Me.SubChannelId,
    			CostingModelId = Me.CostingModelId,
    			VendorId = Me.VendorId,
    			UseDefaultProfiles = Me.UseDefaultProfiles,
    			LegacyCampaignID = Me.LegacyCampaignID,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			RowGuid = Me.RowGuid,
    			ApplicationId = Me.ApplicationId,
    			OfferId = Me.OfferId,
    			BaseLandingPageURL = Me.BaseLandingPageURL,
    			IsOverrideDefaultValues = Me.IsOverrideDefaultValues,
    			ListingResultCount = Me.ListingResultCount,
    			SubmissionCount = Me.SubmissionCount,
    			BusinessModelId = Me.BusinessModelId,
    			CampaignCoordinatorId = Me.CampaignCoordinatorId,
    			PrimaryBuyerId = Me.PrimaryBuyerId,
    			ScrubRate = Me.ScrubRate,
    			Notes = Me.Notes,
    			CampaignTypeId = Me.CampaignTypeId,
    			IsDefault = Me.IsDefault,
    			HasExitPop = Me.HasExitPop,
    			OverrideManualRating = Me.OverrideManualRating,
    			MarketingUnitId = Me.MarketingUnitId,
    			AdditionalQuestionsFlowTypeID = Me.AdditionalQuestionsFlowTypeID,
    			LeadScoringTierLevel = Me.LeadScoringTierLevel,
    			LeadScoringProductSelectionEnabled = Me.LeadScoringProductSelectionEnabled,
    			HasPreCheck = Me.HasPreCheck,
    			MasterProfileID = Me.MasterProfileID,
    			LeadScoringProductUpsellEnabled = Me.LeadScoringProductUpsellEnabled,
    			IsCrossSellALternateList = Me.IsCrossSellALternateList,
    			LeadScoringAddAdditionalSmartMatch = Me.LeadScoringAddAdditionalSmartMatch,
    			CampusAddAdditionalSmartMatch = Me.CampusAddAdditionalSmartMatch,
    			MaxNonFullDegreeCrossSell = Me.MaxNonFullDegreeCrossSell,
    			BusinessUnitId = Me.BusinessUnitId,
    			SubDeal = Me.SubDeal,
    			VendorFee = Me.VendorFee,
    			BillByProspect = Me.BillByProspect,
    			CampaignTCPAMessageName = Me.CampaignTCPAMessageName,
    			ProgramWizardAdditionalQuestionsFlowTypeID = Me.ProgramWizardAdditionalQuestionsFlowTypeID,
    			APIRateExceeded = Me.APIRateExceeded,
    			HasLeaveBehind = Me.HasLeaveBehind,
    			CampaignAPIMatchBehaviorId = Me.CampaignAPIMatchBehaviorId,
    			NumberOfOnlineBackfillOnGeoPages = Me.NumberOfOnlineBackfillOnGeoPages,
    			HasXVerify = Me.HasXVerify,
    			CECLeadScore = Me.CECLeadScore,
    			IsStep1 = Me.IsStep1,
    			IsInternalTransfer = Me.IsInternalTransfer,
    			JobSite = Me.JobSite,
    			BPOTransfer = Me.BPOTransfer,
    			CECEligible = Me.CECEligible,
    			AllowRevShareRPL = Me.AllowRevShareRPL,
    			CalculateRevShareByERPL = Me.CalculateRevShareByERPL,
    			RevenueSharePercentage = Me.RevenueSharePercentage,
    			ValidateTCPA = Me.ValidateTCPA,
    			OpenMailProfileId = Me.OpenMailProfileId,
    			OpenMailProfile = Me.OpenMailProfile!=null?Me.OpenMailProfile.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<Campaign> ConvertToDataModel(this ICollection<CampaignDTO> Me)
    	{
    		ICollection<Campaign> Result = new List<Campaign>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
