//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public static class EDDY_FE_GetCreativeURLs_ResultMapper
    {
    	public static EDDY_FE_GetCreativeURLs_ResultDTO ConvertToDTO(this EDDY_FE_GetCreativeURLs_Result Me){
    		return new EDDY_FE_GetCreativeURLs_ResultDTO() {
    
    			InitiatingURL = Me.InitiatingURL,
    			LandingURL = Me.LandingURL,
    			CallCenterURL = Me.CallCenterURL,
                VideoURL = Me.VideoURL
    		};
    	}
    
    	public static ICollection<EDDY_FE_GetCreativeURLs_ResultDTO> ConvertToDTO(this ICollection<EDDY_FE_GetCreativeURLs_Result> Me)
    	{
    		ICollection<EDDY_FE_GetCreativeURLs_ResultDTO> Result = new List<EDDY_FE_GetCreativeURLs_ResultDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static EDDY_FE_GetCreativeURLs_Result ConvertToDataModel(this EDDY_FE_GetCreativeURLs_ResultDTO Me){
    		return new EDDY_FE_GetCreativeURLs_Result() {
    
    			InitiatingURL = Me.InitiatingURL,
    			LandingURL = Me.LandingURL,
    			CallCenterURL = Me.CallCenterURL,
                VideoURL = Me.VideoURL
    		};
    	}
    
    	public static ICollection<EDDY_FE_GetCreativeURLs_Result> ConvertToDataModel(this ICollection<EDDY_FE_GetCreativeURLs_ResultDTO> Me)
    	{
    		ICollection<EDDY_FE_GetCreativeURLs_Result> Result = new List<EDDY_FE_GetCreativeURLs_Result>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
