//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class HTMLRenderingStrategyAssignmentMapper
    {
    	public static HTMLRenderingStrategyAssignmentDTO ConvertToDTO(this HTMLRenderingStrategyAssignment Me){
    		return new HTMLRenderingStrategyAssignmentDTO() {
    
    			HTMRenderingStrategyId = Me.HTMRenderingStrategyId,
    			TemplateTypeId = Me.TemplateTypeId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HTMLRenderingStrategy = Me.HTMLRenderingStrategy!=null?Me.HTMLRenderingStrategy.ConvertToDTO():null,
    			TemplateType = Me.TemplateType!=null?Me.TemplateType.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<HTMLRenderingStrategyAssignmentDTO> ConvertToDTO(this ICollection<HTMLRenderingStrategyAssignment> Me)
    	{
    		ICollection<HTMLRenderingStrategyAssignmentDTO> Result = new List<HTMLRenderingStrategyAssignmentDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static HTMLRenderingStrategyAssignment ConvertToDataModel(this HTMLRenderingStrategyAssignmentDTO Me){
    		return new HTMLRenderingStrategyAssignment() {
    
    			HTMRenderingStrategyId = Me.HTMRenderingStrategyId,
    			TemplateTypeId = Me.TemplateTypeId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HTMLRenderingStrategy = Me.HTMLRenderingStrategy!=null?Me.HTMLRenderingStrategy.ConvertToDataModel():null,
    			TemplateType = Me.TemplateType!=null?Me.TemplateType.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<HTMLRenderingStrategyAssignment> ConvertToDataModel(this ICollection<HTMLRenderingStrategyAssignmentDTO> Me)
    	{
    		ICollection<HTMLRenderingStrategyAssignment> Result = new List<HTMLRenderingStrategyAssignment>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
