//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class HTMLRenderingStrategyMapper
    {
    	public static HTMLRenderingStrategyDTO ConvertToDTO(this HTMLRenderingStrategy Me){
    		return new HTMLRenderingStrategyDTO() {
    
    			HTMLRenderingStrategyId = Me.HTMLRenderingStrategyId,
    			Name = Me.Name,
    			CSSPath = Me.CSSPath,
    			FormTemplateView = Me.FormTemplateView,
    			ManagedChoiceTemplateView = Me.ManagedChoiceTemplateView,
    			NoMatchTemplateView = Me.NoMatchTemplateView,
    			ThankYouTemplateView = Me.ThankYouTemplateView,
    			NoThankYouTemplateView = Me.NoThankYouTemplateView,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			CrossSellTemplateView = Me.CrossSellTemplateView,
    			CrossSellMaxProgramsToDisplay = Me.CrossSellMaxProgramsToDisplay
    		};
    	}
    
    	public static ICollection<HTMLRenderingStrategyDTO> ConvertToDTO(this ICollection<HTMLRenderingStrategy> Me)
    	{
    		ICollection<HTMLRenderingStrategyDTO> Result = new List<HTMLRenderingStrategyDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static HTMLRenderingStrategy ConvertToDataModel(this HTMLRenderingStrategyDTO Me){
    		return new HTMLRenderingStrategy() {
    
    			HTMLRenderingStrategyId = Me.HTMLRenderingStrategyId,
    			Name = Me.Name,
    			CSSPath = Me.CSSPath,
    			FormTemplateView = Me.FormTemplateView,
    			ManagedChoiceTemplateView = Me.ManagedChoiceTemplateView,
    			NoMatchTemplateView = Me.NoMatchTemplateView,
    			ThankYouTemplateView = Me.ThankYouTemplateView,
    			NoThankYouTemplateView = Me.NoThankYouTemplateView,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			CrossSellTemplateView = Me.CrossSellTemplateView,
    			CrossSellMaxProgramsToDisplay = Me.CrossSellMaxProgramsToDisplay
    		};
    	}
    
    	public static ICollection<HTMLRenderingStrategy> ConvertToDataModel(this ICollection<HTMLRenderingStrategyDTO> Me)
    	{
    		ICollection<HTMLRenderingStrategy> Result = new List<HTMLRenderingStrategy>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
