//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class KVCodeMapper
    {
    	public static KVCodeDTO ConvertToDTO(this KVCode Me){
    		return new KVCodeDTO() {
    
    			KVCodeId = Me.KVCodeId,
    			Name = Me.Name,
    			Description = Me.Description,
    			IsEnabled = Me.IsEnabled,
    			IsDeleted = Me.IsDeleted,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			KVCodeDatas = Me.KVCodeDatas!=null?Me.KVCodeDatas.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<KVCodeDTO> ConvertToDTO(this ICollection<KVCode> Me)
    	{
    		ICollection<KVCodeDTO> Result = new List<KVCodeDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static KVCode ConvertToDataModel(this KVCodeDTO Me){
    		return new KVCode() {
    
    			KVCodeId = Me.KVCodeId,
    			Name = Me.Name,
    			Description = Me.Description,
    			IsEnabled = Me.IsEnabled,
    			IsDeleted = Me.IsDeleted,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			KVCodeDatas = Me.KVCodeDatas!=null?Me.KVCodeDatas.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<KVCode> ConvertToDataModel(this ICollection<KVCodeDTO> Me)
    	{
    		ICollection<KVCode> Result = new List<KVCode>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
