//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class OpenMailProfileMapper
    {
    	public static OpenMailProfileDTO ConvertToDTO(this OpenMailProfile Me){
    		return new OpenMailProfileDTO() {
    
    			OpenMailProfileId = Me.OpenMailProfileId,
    			Name = Me.Name,
    			IsActive = Me.IsActive,
    			CreatedBy = Me.CreatedBy,
    			CreatedDate = Me.CreatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			OpenMailRules = Me.OpenMailRules!=null?Me.OpenMailRules.ConvertToDTO():null,
    			Campaigns = Me.Campaigns!=null?Me.Campaigns.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<OpenMailProfileDTO> ConvertToDTO(this ICollection<OpenMailProfile> Me)
    	{
    		ICollection<OpenMailProfileDTO> Result = new List<OpenMailProfileDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static OpenMailProfile ConvertToDataModel(this OpenMailProfileDTO Me){
    		return new OpenMailProfile() {
    
    			OpenMailProfileId = Me.OpenMailProfileId,
    			Name = Me.Name,
    			IsActive = Me.IsActive,
    			CreatedBy = Me.CreatedBy,
    			CreatedDate = Me.CreatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			OpenMailRules = Me.OpenMailRules!=null?Me.OpenMailRules.ConvertToDataModel():null,
    			Campaigns = Me.Campaigns!=null?Me.Campaigns.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<OpenMailProfile> ConvertToDataModel(this ICollection<OpenMailProfileDTO> Me)
    	{
    		ICollection<OpenMailProfile> Result = new List<OpenMailProfile>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
