//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class OpenMailRuleMapper
    {
    	public static OpenMailRuleDTO ConvertToDTO(this OpenMailRule Me){
    		return new OpenMailRuleDTO() {
    
    			OpenMailRuleId = Me.OpenMailRuleId,
    			OpenMailProfileId = Me.OpenMailProfileId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			GroupId = Me.GroupId,
    			RuleType = Me.RuleType,
    			Value = Me.Value,
    			CreatedBy = Me.CreatedBy,
    			CreatedDate = Me.CreatedDate,
    			OpenMailProfile = Me.OpenMailProfile!=null?Me.OpenMailProfile.ConvertToDTO():null,
    			StandardControlCode = Me.StandardControlCode!=null?Me.StandardControlCode.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<OpenMailRuleDTO> ConvertToDTO(this ICollection<OpenMailRule> Me)
    	{
    		ICollection<OpenMailRuleDTO> Result = new List<OpenMailRuleDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static OpenMailRule ConvertToDataModel(this OpenMailRuleDTO Me){
    		return new OpenMailRule() {
    
    			OpenMailRuleId = Me.OpenMailRuleId,
    			OpenMailProfileId = Me.OpenMailProfileId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			GroupId = Me.GroupId,
    			RuleType = Me.RuleType,
    			Value = Me.Value,
    			CreatedBy = Me.CreatedBy,
    			CreatedDate = Me.CreatedDate,
    			OpenMailProfile = Me.OpenMailProfile!=null?Me.OpenMailProfile.ConvertToDataModel():null,
    			StandardControlCode = Me.StandardControlCode!=null?Me.StandardControlCode.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<OpenMailRule> ConvertToDataModel(this ICollection<OpenMailRuleDTO> Me)
    	{
    		ICollection<OpenMailRule> Result = new List<OpenMailRule>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
