//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public static class PreDefinedListBaseResultMapper
    {
    	public static PreDefinedListBaseResultDTO ConvertToDTO(this PreDefinedListBaseResult Me){
    		return new PreDefinedListBaseResultDTO() {
    
    			Value = Me.Value,
    			Text = Me.Text,
    			Key = Me.Key
    		};
    	}
    
    	public static ICollection<PreDefinedListBaseResultDTO> ConvertToDTO(this ICollection<PreDefinedListBaseResult> Me)
    	{
    		ICollection<PreDefinedListBaseResultDTO> Result = new List<PreDefinedListBaseResultDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static PreDefinedListBaseResult ConvertToDataModel(this PreDefinedListBaseResultDTO Me){
    		return new PreDefinedListBaseResult() {
    
    			Value = Me.Value,
    			Text = Me.Text,
    			Key = Me.Key
    		};
    	}
    
    	public static ICollection<PreDefinedListBaseResult> ConvertToDataModel(this ICollection<PreDefinedListBaseResultDTO> Me)
    	{
    		ICollection<PreDefinedListBaseResult> Result = new List<PreDefinedListBaseResult>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
