//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class PreDefinedValueListMapper
    {
    	public static PreDefinedValueListDTO ConvertToDTO(this PreDefinedValueList Me){
    		return new PreDefinedValueListDTO() {
    
    			PreDefinedValueListId = Me.PreDefinedValueListId,
    			PreDefinedValueListName = Me.PreDefinedValueListName,
    			StoredProcedureName = Me.StoredProcedureName,
    			IsMatchingEngineAdditionalField = Me.IsMatchingEngineAdditionalField,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ValueListItems = Me.ValueListItems!=null?Me.ValueListItems.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<PreDefinedValueListDTO> ConvertToDTO(this ICollection<PreDefinedValueList> Me)
    	{
    		ICollection<PreDefinedValueListDTO> Result = new List<PreDefinedValueListDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static PreDefinedValueList ConvertToDataModel(this PreDefinedValueListDTO Me){
    		return new PreDefinedValueList() {
    
    			PreDefinedValueListId = Me.PreDefinedValueListId,
    			PreDefinedValueListName = Me.PreDefinedValueListName,
    			StoredProcedureName = Me.StoredProcedureName,
    			IsMatchingEngineAdditionalField = Me.IsMatchingEngineAdditionalField,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ValueListItems = Me.ValueListItems!=null?Me.ValueListItems.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<PreDefinedValueList> ConvertToDataModel(this ICollection<PreDefinedValueListDTO> Me)
    	{
    		ICollection<PreDefinedValueList> Result = new List<PreDefinedValueList>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
