//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class ProgramProductMapper
    {
    	public static ProgramProductDTO ConvertToDTO(this ProgramProduct Me){
    		return new ProgramProductDTO() {
    
    			ProgramProductId = Me.ProgramProductId,
    			ClientCampusProgramRelationshipID = Me.ClientCampusProgramRelationshipID,
    			ProductId = Me.ProductId,
    			ProgramCode = Me.ProgramCode,
    			AllowableRadius = Me.AllowableRadius,
    			RadiusZipCode = Me.RadiusZipCode,
    			IsZipCodeInclusionExclusionActive = Me.IsZipCodeInclusionExclusionActive,
    			IsEnabled = Me.IsEnabled,
    			IsDeleted = Me.IsDeleted,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			rowguid = Me.rowguid,
    			UseCCRGeoInfo = Me.UseCCRGeoInfo,
    			IncludeAllZipCodes = Me.IncludeAllZipCodes,
    			strategic = Me.strategic,
    			IsImported = Me.IsImported,
    			ecprogramid = Me.ecprogramid,
    			IsZipCodeInclusion = Me.IsZipCodeInclusion,
    			IsZipCodeExclusion = Me.IsZipCodeExclusion,
    			CanSmartmatch = Me.CanSmartmatch,
    			DeliveryEmailRoutingAddress = Me.DeliveryEmailRoutingAddress,
    			ClientCampusProgramRelationship = Me.ClientCampusProgramRelationship!=null?Me.ClientCampusProgramRelationship.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<ProgramProductDTO> ConvertToDTO(this ICollection<ProgramProduct> Me)
    	{
    		ICollection<ProgramProductDTO> Result = new List<ProgramProductDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static ProgramProduct ConvertToDataModel(this ProgramProductDTO Me){
    		return new ProgramProduct() {
    
    			ProgramProductId = Me.ProgramProductId,
    			ClientCampusProgramRelationshipID = Me.ClientCampusProgramRelationshipID,
    			ProductId = Me.ProductId,
    			ProgramCode = Me.ProgramCode,
    			AllowableRadius = Me.AllowableRadius,
    			RadiusZipCode = Me.RadiusZipCode,
    			IsZipCodeInclusionExclusionActive = Me.IsZipCodeInclusionExclusionActive,
    			IsEnabled = Me.IsEnabled,
    			IsDeleted = Me.IsDeleted,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			rowguid = Me.rowguid,
    			UseCCRGeoInfo = Me.UseCCRGeoInfo,
    			IncludeAllZipCodes = Me.IncludeAllZipCodes,
    			strategic = Me.strategic,
    			IsImported = Me.IsImported,
    			ecprogramid = Me.ecprogramid,
    			IsZipCodeInclusion = Me.IsZipCodeInclusion,
    			IsZipCodeExclusion = Me.IsZipCodeExclusion,
    			CanSmartmatch = Me.CanSmartmatch,
    			DeliveryEmailRoutingAddress = Me.DeliveryEmailRoutingAddress,
    			ClientCampusProgramRelationship = Me.ClientCampusProgramRelationship!=null?Me.ClientCampusProgramRelationship.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<ProgramProduct> ConvertToDataModel(this ICollection<ProgramProductDTO> Me)
    	{
    		ICollection<ProgramProduct> Result = new List<ProgramProduct>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
