//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class ProgramLevelMapper
    {
    	public static ProgramLevelDTO ConvertToDTO(this ProgramLevel Me){
    		return new ProgramLevelDTO() {
    
    			ProgramLevelId = Me.ProgramLevelId,
    			ProgramLevelName = Me.ProgramLevelName,
    			ProgramLevelDescription = Me.ProgramLevelDescription,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			RowGuid = Me.RowGuid,
    			CanSmartmatch = Me.CanSmartmatch,
    			ProgramLevelGroupId = Me.ProgramLevelGroupId,
    			FullDegreeAllowed = Me.FullDegreeAllowed,
    			NonFullDegreeAllowed = Me.NonFullDegreeAllowed,
    			DisplayOrder = Me.DisplayOrder
    		};
    	}
    
    	public static ICollection<ProgramLevelDTO> ConvertToDTO(this ICollection<ProgramLevel> Me)
    	{
    		ICollection<ProgramLevelDTO> Result = new List<ProgramLevelDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static ProgramLevel ConvertToDataModel(this ProgramLevelDTO Me){
    		return new ProgramLevel() {
    
    			ProgramLevelId = Me.ProgramLevelId,
    			ProgramLevelName = Me.ProgramLevelName,
    			ProgramLevelDescription = Me.ProgramLevelDescription,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			RowGuid = Me.RowGuid,
    			CanSmartmatch = Me.CanSmartmatch,
    			ProgramLevelGroupId = Me.ProgramLevelGroupId,
    			FullDegreeAllowed = Me.FullDegreeAllowed,
    			NonFullDegreeAllowed = Me.NonFullDegreeAllowed,
    			DisplayOrder = Me.DisplayOrder
    		};
    	}
    
    	public static ICollection<ProgramLevel> ConvertToDataModel(this ICollection<ProgramLevelDTO> Me)
    	{
    		ICollection<ProgramLevel> Result = new List<ProgramLevel>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
