//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class ResourceMetaDataMapper
    {
    	public static ResourceMetaDataDTO ConvertToDTO(this ResourceMetaData Me){
    		return new ResourceMetaDataDTO() {
    
    			ResourceMetaDataID = Me.ResourceMetaDataID,
    			ResourceMetaDataKey = Me.ResourceMetaDataKey,
    			ResourceMetaDataText = Me.ResourceMetaDataText,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			IsTCPAMessage = Me.IsTCPAMessage
    		};
    	}
    
    	public static ICollection<ResourceMetaDataDTO> ConvertToDTO(this ICollection<ResourceMetaData> Me)
    	{
    		ICollection<ResourceMetaDataDTO> Result = new List<ResourceMetaDataDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static ResourceMetaData ConvertToDataModel(this ResourceMetaDataDTO Me){
    		return new ResourceMetaData() {
    
    			ResourceMetaDataID = Me.ResourceMetaDataID,
    			ResourceMetaDataKey = Me.ResourceMetaDataKey,
    			ResourceMetaDataText = Me.ResourceMetaDataText,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			IsTCPAMessage = Me.IsTCPAMessage
    		};
    	}
    
    	public static ICollection<ResourceMetaData> ConvertToDataModel(this ICollection<ResourceMetaDataDTO> Me)
    	{
    		ICollection<ResourceMetaData> Result = new List<ResourceMetaData>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
