//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class StandardControlDataTypeMapper
    {
    	public static StandardControlDataTypeDTO ConvertToDTO(this StandardControlDataType Me){
    		return new StandardControlDataTypeDTO() {
    
    			StandardControlDataTypeId = Me.StandardControlDataTypeId,
    			Name = Me.Name
    		};
    	}
    
    	public static ICollection<StandardControlDataTypeDTO> ConvertToDTO(this ICollection<StandardControlDataType> Me)
    	{
    		ICollection<StandardControlDataTypeDTO> Result = new List<StandardControlDataTypeDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static StandardControlDataType ConvertToDataModel(this StandardControlDataTypeDTO Me){
    		return new StandardControlDataType() {
    
    			StandardControlDataTypeId = Me.StandardControlDataTypeId,
    			Name = Me.Name
    		};
    	}
    
    	public static ICollection<StandardControlDataType> ConvertToDataModel(this ICollection<StandardControlDataTypeDTO> Me)
    	{
    		ICollection<StandardControlDataType> Result = new List<StandardControlDataType>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
