//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class StandardControlValidationMapper
    {
    	public static StandardControlValidationDTO ConvertToDTO(this StandardControlValidation Me){
    		return new StandardControlValidationDTO() {
    
    			StandardControlValidationId = Me.StandardControlValidationId,
    			StandardControlId = Me.StandardControlId,
    			ValidationLibraryId = Me.ValidationLibraryId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ValidationLibrary = Me.ValidationLibrary!=null?Me.ValidationLibrary.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<StandardControlValidationDTO> ConvertToDTO(this ICollection<StandardControlValidation> Me)
    	{
    		ICollection<StandardControlValidationDTO> Result = new List<StandardControlValidationDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static StandardControlValidation ConvertToDataModel(this StandardControlValidationDTO Me){
    		return new StandardControlValidation() {
    
    			StandardControlValidationId = Me.StandardControlValidationId,
    			StandardControlId = Me.StandardControlId,
    			ValidationLibraryId = Me.ValidationLibraryId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ValidationLibrary = Me.ValidationLibrary!=null?Me.ValidationLibrary.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<StandardControlValidation> ConvertToDataModel(this ICollection<StandardControlValidationDTO> Me)
    	{
    		ICollection<StandardControlValidation> Result = new List<StandardControlValidation>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
