//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class StandardControlMapper
    {
    	public static StandardControlDTO ConvertToDTO(this StandardControl Me){
    		return new StandardControlDTO() {
    
    			StandardControlId = Me.StandardControlId,
    			StandardControlTypeId = Me.StandardControlTypeId,
    			DefaultLabel = Me.DefaultLabel,
    			FieldName = Me.FieldName,
    			DefaultValue = Me.DefaultValue,
    			PreDefinedValueListId = Me.PreDefinedValueListId,
    			IsLabelHidden = Me.IsLabelHidden,
    			MinLength = Me.MinLength,
    			MaxLength = Me.MaxLength,
    			StandardControlDataTypeId = Me.StandardControlDataTypeId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			JavaScriptDataBind = Me.JavaScriptDataBind,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			TransformOnMobile = Me.TransformOnMobile,
    			ControlFriendlyName = Me.ControlFriendlyName,
    			Mask = Me.Mask,
    			AutoCompleteName = Me.AutoCompleteName,
    			SearchablePredefinedValueList = Me.SearchablePredefinedValueList,
    			StandardControlCode = Me.StandardControlCode!=null?Me.StandardControlCode.ConvertToDTO():null,
    			StandardControlDataType = Me.StandardControlDataType!=null?Me.StandardControlDataType.ConvertToDTO():null,
    			StandardControlType = Me.StandardControlType!=null?Me.StandardControlType.ConvertToDTO():null,
    			StandardControlValidations = Me.StandardControlValidations!=null?Me.StandardControlValidations.ConvertToDTO():null,
    			PreDefinedValueList = Me.PreDefinedValueList!=null?Me.PreDefinedValueList.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<StandardControlDTO> ConvertToDTO(this ICollection<StandardControl> Me)
    	{
    		ICollection<StandardControlDTO> Result = new List<StandardControlDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static StandardControl ConvertToDataModel(this StandardControlDTO Me){
    		return new StandardControl() {
    
    			StandardControlId = Me.StandardControlId,
    			StandardControlTypeId = Me.StandardControlTypeId,
    			DefaultLabel = Me.DefaultLabel,
    			FieldName = Me.FieldName,
    			DefaultValue = Me.DefaultValue,
    			PreDefinedValueListId = Me.PreDefinedValueListId,
    			IsLabelHidden = Me.IsLabelHidden,
    			MinLength = Me.MinLength,
    			MaxLength = Me.MaxLength,
    			StandardControlDataTypeId = Me.StandardControlDataTypeId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			JavaScriptDataBind = Me.JavaScriptDataBind,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			TransformOnMobile = Me.TransformOnMobile,
    			ControlFriendlyName = Me.ControlFriendlyName,
    			Mask = Me.Mask,
    			AutoCompleteName = Me.AutoCompleteName,
    			SearchablePredefinedValueList = Me.SearchablePredefinedValueList,
    			StandardControlCode = Me.StandardControlCode!=null?Me.StandardControlCode.ConvertToDataModel():null,
    			StandardControlDataType = Me.StandardControlDataType!=null?Me.StandardControlDataType.ConvertToDataModel():null,
    			StandardControlType = Me.StandardControlType!=null?Me.StandardControlType.ConvertToDataModel():null,
    			StandardControlValidations = Me.StandardControlValidations!=null?Me.StandardControlValidations.ConvertToDataModel():null,
    			PreDefinedValueList = Me.PreDefinedValueList!=null?Me.PreDefinedValueList.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<StandardControl> ConvertToDataModel(this ICollection<StandardControlDTO> Me)
    	{
    		ICollection<StandardControl> Result = new List<StandardControl>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
