//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class StandardControlGroupMapper
    {
    	public static StandardControlGroupDTO ConvertToDTO(this StandardControlGroup Me){
    		return new StandardControlGroupDTO() {
    
    			StandardControlGroupId = Me.StandardControlGroupId,
    			StandardControlGroupName = Me.StandardControlGroupName,
    			SortOrder = Me.SortOrder,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			LockControlsInGroup = Me.LockControlsInGroup
    		};
    	}
    
    	public static ICollection<StandardControlGroupDTO> ConvertToDTO(this ICollection<StandardControlGroup> Me)
    	{
    		ICollection<StandardControlGroupDTO> Result = new List<StandardControlGroupDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static StandardControlGroup ConvertToDataModel(this StandardControlGroupDTO Me){
    		return new StandardControlGroup() {
    
    			StandardControlGroupId = Me.StandardControlGroupId,
    			StandardControlGroupName = Me.StandardControlGroupName,
    			SortOrder = Me.SortOrder,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			LockControlsInGroup = Me.LockControlsInGroup
    		};
    	}
    
    	public static ICollection<StandardControlGroup> ConvertToDataModel(this ICollection<StandardControlGroupDTO> Me)
    	{
    		ICollection<StandardControlGroup> Result = new List<StandardControlGroup>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
