//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class StandardControlCodeFilterMapper
    {
    	public static StandardControlCodeFilterDTO ConvertToDTO(this StandardControlCodeFilter Me){
    		return new StandardControlCodeFilterDTO() {
    
    			StandardControlCodeFilterId = Me.StandardControlCodeFilterId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			StandardControlCodeIdFilter = Me.StandardControlCodeIdFilter,
    			StandardControlCodeFilterEntity = Me.StandardControlCodeFilterEntity!=null?Me.StandardControlCodeFilterEntity.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<StandardControlCodeFilterDTO> ConvertToDTO(this ICollection<StandardControlCodeFilter> Me)
    	{
    		ICollection<StandardControlCodeFilterDTO> Result = new List<StandardControlCodeFilterDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static StandardControlCodeFilter ConvertToDataModel(this StandardControlCodeFilterDTO Me){
    		return new StandardControlCodeFilter() {
    
    			StandardControlCodeFilterId = Me.StandardControlCodeFilterId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			StandardControlCodeIdFilter = Me.StandardControlCodeIdFilter,
    			StandardControlCodeFilterEntity = Me.StandardControlCodeFilterEntity!=null?Me.StandardControlCodeFilterEntity.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<StandardControlCodeFilter> ConvertToDataModel(this ICollection<StandardControlCodeFilterDTO> Me)
    	{
    		ICollection<StandardControlCodeFilter> Result = new List<StandardControlCodeFilter>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
