//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class SubmissionDetailAdditionalMapper
    {
    	public static SubmissionDetailAdditionalDTO ConvertToDTO(this SubmissionDetailAdditional Me){
    		return new SubmissionDetailAdditionalDTO() {
    
    			SubmissionDetailAdditionalId = Me.SubmissionDetailAdditionalId,
    			SubmissionId = Me.SubmissionId,
    			SubmissionDetailAdditionalKey = Me.SubmissionDetailAdditionalKey,
    			SubmissionDetailAdditionalValue = Me.SubmissionDetailAdditionalValue,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<SubmissionDetailAdditionalDTO> ConvertToDTO(this ICollection<SubmissionDetailAdditional> Me)
    	{
    		ICollection<SubmissionDetailAdditionalDTO> Result = new List<SubmissionDetailAdditionalDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static SubmissionDetailAdditional ConvertToDataModel(this SubmissionDetailAdditionalDTO Me){
    		return new SubmissionDetailAdditional() {
    
    			SubmissionDetailAdditionalId = Me.SubmissionDetailAdditionalId,
    			SubmissionId = Me.SubmissionId,
    			SubmissionDetailAdditionalKey = Me.SubmissionDetailAdditionalKey,
    			SubmissionDetailAdditionalValue = Me.SubmissionDetailAdditionalValue,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<SubmissionDetailAdditional> ConvertToDataModel(this ICollection<SubmissionDetailAdditionalDTO> Me)
    	{
    		ICollection<SubmissionDetailAdditional> Result = new List<SubmissionDetailAdditional>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
