//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class SubmissionLeadScoringResponseMapper
    {
    	public static SubmissionLeadScoringResponseDTO ConvertToDTO(this SubmissionLeadScoringResponse Me){
    		return new SubmissionLeadScoringResponseDTO() {
    
    			SubmissionId = Me.SubmissionId,
    			LeadScoringGuid = Me.LeadScoringGuid,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<SubmissionLeadScoringResponseDTO> ConvertToDTO(this ICollection<SubmissionLeadScoringResponse> Me)
    	{
    		ICollection<SubmissionLeadScoringResponseDTO> Result = new List<SubmissionLeadScoringResponseDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static SubmissionLeadScoringResponse ConvertToDataModel(this SubmissionLeadScoringResponseDTO Me){
    		return new SubmissionLeadScoringResponse() {
    
    			SubmissionId = Me.SubmissionId,
    			LeadScoringGuid = Me.LeadScoringGuid,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<SubmissionLeadScoringResponse> ConvertToDataModel(this ICollection<SubmissionLeadScoringResponseDTO> Me)
    	{
    		ICollection<SubmissionLeadScoringResponse> Result = new List<SubmissionLeadScoringResponse>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
