//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class SubmissionDetailMapper
    {
    	public static SubmissionDetailDTO ConvertToDTO(this SubmissionDetail Me){
    		return new SubmissionDetailDTO() {
    
    			SubmissionDetailId = Me.SubmissionDetailId,
    			SubmissionId = Me.SubmissionId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			SubmissionDetailValue = Me.SubmissionDetailValue,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<SubmissionDetailDTO> ConvertToDTO(this ICollection<SubmissionDetail> Me)
    	{
    		ICollection<SubmissionDetailDTO> Result = new List<SubmissionDetailDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static SubmissionDetail ConvertToDataModel(this SubmissionDetailDTO Me){
    		return new SubmissionDetail() {
    
    			SubmissionDetailId = Me.SubmissionDetailId,
    			SubmissionId = Me.SubmissionId,
    			StandardControlCodeId = Me.StandardControlCodeId,
    			SubmissionDetailValue = Me.SubmissionDetailValue,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<SubmissionDetail> ConvertToDataModel(this ICollection<SubmissionDetailDTO> Me)
    	{
    		ICollection<SubmissionDetail> Result = new List<SubmissionDetail>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
