//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class SubmissionMatchResponseMapper
    {
    	public static SubmissionMatchResponseDTO ConvertToDTO(this SubmissionMatchResponse Me){
    		return new SubmissionMatchResponseDTO() {
    
    			SubmissionMatchResponseId = Me.SubmissionMatchResponseId,
    			SubmissionId = Me.SubmissionId,
    			MatchResponseGuid = Me.MatchResponseGuid,
    			MatchResponseTypeId = Me.MatchResponseTypeId,
    			CreatedDate = Me.CreatedDate,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<SubmissionMatchResponseDTO> ConvertToDTO(this ICollection<SubmissionMatchResponse> Me)
    	{
    		ICollection<SubmissionMatchResponseDTO> Result = new List<SubmissionMatchResponseDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static SubmissionMatchResponse ConvertToDataModel(this SubmissionMatchResponseDTO Me){
    		return new SubmissionMatchResponse() {
    
    			SubmissionMatchResponseId = Me.SubmissionMatchResponseId,
    			SubmissionId = Me.SubmissionId,
    			MatchResponseGuid = Me.MatchResponseGuid,
    			MatchResponseTypeId = Me.MatchResponseTypeId,
    			CreatedDate = Me.CreatedDate,
    			Submission = Me.Submission!=null?Me.Submission.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<SubmissionMatchResponse> ConvertToDataModel(this ICollection<SubmissionMatchResponseDTO> Me)
    	{
    		ICollection<SubmissionMatchResponse> Result = new List<SubmissionMatchResponse>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
