//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateStepMapper
    {
    	public static TemplateStepDTO ConvertToDTO(this TemplateStep Me){
    		return new TemplateStepDTO() {
    
    			TemplateStepId = Me.TemplateStepId,
    			TemplateId = Me.TemplateId,
    			Name = Me.Name,
    			Sequence = Me.Sequence,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			TemplateName = Me.TemplateName,
    			TemplateSections = Me.TemplateSections!=null?Me.TemplateSections.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateStepDTO> ConvertToDTO(this ICollection<TemplateStep> Me)
    	{
    		ICollection<TemplateStepDTO> Result = new List<TemplateStepDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateStep ConvertToDataModel(this TemplateStepDTO Me){
    		return new TemplateStep() {
    
    			TemplateStepId = Me.TemplateStepId,
    			TemplateId = Me.TemplateId,
    			Name = Me.Name,
    			Sequence = Me.Sequence,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			TemplateName = Me.TemplateName,
    			TemplateSections = Me.TemplateSections!=null?Me.TemplateSections.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<TemplateStep> ConvertToDataModel(this ICollection<TemplateStepDTO> Me)
    	{
    		ICollection<TemplateStep> Result = new List<TemplateStep>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
