//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateMapper
    {
    	public static TemplateDTO ConvertToDTO(this Template Me){
    		return new TemplateDTO() {
    
    			TemplateId = Me.TemplateId,
    			TemplateName = Me.TemplateName,
    			TemplateDescription = Me.TemplateDescription,
    			IsDefaultTemplate = Me.IsDefaultTemplate,
    			IsSystemTemplate = Me.IsSystemTemplate,
    			TemplateTypeId = Me.TemplateTypeId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			InlineDropDowns = Me.InlineDropDowns,
    			ShowAllQuestionsOnFirstStep = Me.ShowAllQuestionsOnFirstStep,
    			BusinessDivisionId = Me.BusinessDivisionId,
    			InstitutionId = Me.InstitutionId,
    			SystemAllowedDoBTemplate = Me.SystemAllowedDoBTemplate,
    			TemplateType = Me.TemplateType!=null?Me.TemplateType.ConvertToDTO():null,
    			TemplateAssignments = Me.TemplateAssignments!=null?Me.TemplateAssignments.ConvertToDTO():null,
    			TemplateSteps = Me.TemplateSteps!=null?Me.TemplateSteps.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateDTO> ConvertToDTO(this ICollection<Template> Me)
    	{
    		ICollection<TemplateDTO> Result = new List<TemplateDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static Template ConvertToDataModel(this TemplateDTO Me){
    		return new Template() {
    
    			TemplateId = Me.TemplateId,
    			TemplateName = Me.TemplateName,
    			TemplateDescription = Me.TemplateDescription,
    			IsDefaultTemplate = Me.IsDefaultTemplate,
    			IsSystemTemplate = Me.IsSystemTemplate,
    			TemplateTypeId = Me.TemplateTypeId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			InlineDropDowns = Me.InlineDropDowns,
    			ShowAllQuestionsOnFirstStep = Me.ShowAllQuestionsOnFirstStep,
    			BusinessDivisionId = Me.BusinessDivisionId,
    			InstitutionId = Me.InstitutionId,
    			SystemAllowedDoBTemplate = Me.SystemAllowedDoBTemplate,
    			TemplateType = Me.TemplateType!=null?Me.TemplateType.ConvertToDataModel():null,
    			TemplateAssignments = Me.TemplateAssignments!=null?Me.TemplateAssignments.ConvertToDataModel():null,
    			TemplateSteps = Me.TemplateSteps!=null?Me.TemplateSteps.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<Template> ConvertToDataModel(this ICollection<TemplateDTO> Me)
    	{
    		ICollection<Template> Result = new List<Template>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
