//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateSectionMapper
    {
    	public static TemplateSectionDTO ConvertToDTO(this TemplateSection Me){
    		return new TemplateSectionDTO() {
    
    			TemplateSectionId = Me.TemplateSectionId,
    			TemplateStepId = Me.TemplateStepId,
    			Name = Me.Name,
    			Sequence = Me.Sequence,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			StandardControlGroupId = Me.StandardControlGroupId,
    			TemplateName = Me.TemplateName,
    			TemplateControls = Me.TemplateControls!=null?Me.TemplateControls.ConvertToDTO():null,
    			StandardControlGroup = Me.StandardControlGroup!=null?Me.StandardControlGroup.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateSectionDTO> ConvertToDTO(this ICollection<TemplateSection> Me)
    	{
    		ICollection<TemplateSectionDTO> Result = new List<TemplateSectionDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateSection ConvertToDataModel(this TemplateSectionDTO Me){
    		return new TemplateSection() {
    
    			TemplateSectionId = Me.TemplateSectionId,
    			TemplateStepId = Me.TemplateStepId,
    			Name = Me.Name,
    			Sequence = Me.Sequence,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			StandardControlGroupId = Me.StandardControlGroupId,
    			TemplateName = Me.TemplateName,
    			TemplateControls = Me.TemplateControls!=null?Me.TemplateControls.ConvertToDataModel():null,
    			StandardControlGroup = Me.StandardControlGroup!=null?Me.StandardControlGroup.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<TemplateSection> ConvertToDataModel(this ICollection<TemplateSectionDTO> Me)
    	{
    		ICollection<TemplateSection> Result = new List<TemplateSection>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
