//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateControlMapper
    {
    	public static TemplateControlDTO ConvertToDTO(this TemplateControl Me){
    		return new TemplateControlDTO() {
    
    			TemplateControlId = Me.TemplateControlId,
    			TemplateSectionId = Me.TemplateSectionId,
    			TemplateId = Me.TemplateId,
    			StandardControlId = Me.StandardControlId,
    			RowSequence = Me.RowSequence,
    			IsRequired = Me.IsRequired,
    			InstanceLabel = Me.InstanceLabel,
    			InstanceWaterMark = Me.InstanceWaterMark,
    			InstanceToolTip = Me.InstanceToolTip,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HideLabelOnMobile = Me.HideLabelOnMobile,
    			InstanceMobileWaterMark = Me.InstanceMobileWaterMark,
    			TransformOnMobileType = Me.TransformOnMobileType,
    			TransformOnDesktopType = Me.TransformOnDesktopType,
    			IsTypeAhead = Me.IsTypeAhead,
    			ExtendedProperties = Me.ExtendedProperties,
    			InstanceTemplateLabel = Me.InstanceTemplateLabel,
    			ShowInEddyApi = Me.ShowInEddyApi,
    			StandardControl = Me.StandardControl!=null?Me.StandardControl.ConvertToDTO():null,
    			TemplateControlDefaults = Me.TemplateControlDefaults!=null?Me.TemplateControlDefaults.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateControlDTO> ConvertToDTO(this ICollection<TemplateControl> Me)
    	{
    		ICollection<TemplateControlDTO> Result = new List<TemplateControlDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateControl ConvertToDataModel(this TemplateControlDTO Me){
    		return new TemplateControl() {
    
    			TemplateControlId = Me.TemplateControlId,
    			TemplateSectionId = Me.TemplateSectionId,
    			TemplateId = Me.TemplateId,
    			StandardControlId = Me.StandardControlId,
    			RowSequence = Me.RowSequence,
    			IsRequired = Me.IsRequired,
    			InstanceLabel = Me.InstanceLabel,
    			InstanceWaterMark = Me.InstanceWaterMark,
    			InstanceToolTip = Me.InstanceToolTip,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HideLabelOnMobile = Me.HideLabelOnMobile,
    			InstanceMobileWaterMark = Me.InstanceMobileWaterMark,
    			TransformOnMobileType = Me.TransformOnMobileType,
    			TransformOnDesktopType = Me.TransformOnDesktopType,
    			IsTypeAhead = Me.IsTypeAhead,
    			ExtendedProperties = Me.ExtendedProperties,
    			InstanceTemplateLabel = Me.InstanceTemplateLabel,
    			ShowInEddyApi = Me.ShowInEddyApi,
    			StandardControl = Me.StandardControl!=null?Me.StandardControl.ConvertToDataModel():null,
    			TemplateControlDefaults = Me.TemplateControlDefaults!=null?Me.TemplateControlDefaults.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<TemplateControl> ConvertToDataModel(this ICollection<TemplateControlDTO> Me)
    	{
    		ICollection<TemplateControl> Result = new List<TemplateControl>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
