//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateAssignmentMapper
    {
    	public static TemplateAssignmentDTO ConvertToDTO(this TemplateAssignment Me){
    		return new TemplateAssignmentDTO() {
    
    			TemplateAssignmentId = Me.TemplateAssignmentId,
    			TemplateId = Me.TemplateId,
    			ProgramId = Me.ProgramId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ProductId = Me.ProductId,
    			Template = Me.Template!=null?Me.Template.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateAssignmentDTO> ConvertToDTO(this ICollection<TemplateAssignment> Me)
    	{
    		ICollection<TemplateAssignmentDTO> Result = new List<TemplateAssignmentDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateAssignment ConvertToDataModel(this TemplateAssignmentDTO Me){
    		return new TemplateAssignment() {
    
    			TemplateAssignmentId = Me.TemplateAssignmentId,
    			TemplateId = Me.TemplateId,
    			ProgramId = Me.ProgramId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ProductId = Me.ProductId,
    			Template = Me.Template!=null?Me.Template.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<TemplateAssignment> ConvertToDataModel(this ICollection<TemplateAssignmentDTO> Me)
    	{
    		ICollection<TemplateAssignment> Result = new List<TemplateAssignment>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
