//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateApplicationOverrideMapper
    {
    	public static TemplateApplicationOverrideDTO ConvertToDTO(this TemplateApplicationOverride Me){
    		return new TemplateApplicationOverrideDTO() {
    
    			TemplateApplicationOverrideId = Me.TemplateApplicationOverrideId,
    			ApplicationId = Me.ApplicationId,
    			PaidStatusTypeId = Me.PaidStatusTypeId,
    			TemplateId = Me.TemplateId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy
    		};
    	}
    
    	public static ICollection<TemplateApplicationOverrideDTO> ConvertToDTO(this ICollection<TemplateApplicationOverride> Me)
    	{
    		ICollection<TemplateApplicationOverrideDTO> Result = new List<TemplateApplicationOverrideDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateApplicationOverride ConvertToDataModel(this TemplateApplicationOverrideDTO Me){
    		return new TemplateApplicationOverride() {
    
    			TemplateApplicationOverrideId = Me.TemplateApplicationOverrideId,
    			ApplicationId = Me.ApplicationId,
    			PaidStatusTypeId = Me.PaidStatusTypeId,
    			TemplateId = Me.TemplateId,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy
    		};
    	}
    
    	public static ICollection<TemplateApplicationOverride> ConvertToDataModel(this ICollection<TemplateApplicationOverrideDTO> Me)
    	{
    		ICollection<TemplateApplicationOverride> Result = new List<TemplateApplicationOverride>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
