//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateTypeMapper
    {
    	public static TemplateTypeDTO ConvertToDTO(this TemplateType Me){
    		return new TemplateTypeDTO() {
    
    			TemplateTypeId = Me.TemplateTypeId,
    			Name = Me.Name,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HTMLRenderingStrategyAssignments = Me.HTMLRenderingStrategyAssignments!=null?Me.HTMLRenderingStrategyAssignments.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<TemplateTypeDTO> ConvertToDTO(this ICollection<TemplateType> Me)
    	{
    		ICollection<TemplateTypeDTO> Result = new List<TemplateTypeDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateType ConvertToDataModel(this TemplateTypeDTO Me){
    		return new TemplateType() {
    
    			TemplateTypeId = Me.TemplateTypeId,
    			Name = Me.Name,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			HTMLRenderingStrategyAssignments = Me.HTMLRenderingStrategyAssignments!=null?Me.HTMLRenderingStrategyAssignments.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<TemplateType> ConvertToDataModel(this ICollection<TemplateTypeDTO> Me)
    	{
    		ICollection<TemplateType> Result = new List<TemplateType>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
