//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class TemplateControlDefaultMapper
    {
    	public static TemplateControlDefaultDTO ConvertToDTO(this TemplateControlDefault Me){
    		return new TemplateControlDefaultDTO() {
    
    			TemplateControlDefaultId = Me.TemplateControlDefaultId,
    			TemplateControlId = Me.TemplateControlId,
    			Text = Me.Text,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			IsPopular = Me.IsPopular
    		};
    	}
    
    	public static ICollection<TemplateControlDefaultDTO> ConvertToDTO(this ICollection<TemplateControlDefault> Me)
    	{
    		ICollection<TemplateControlDefaultDTO> Result = new List<TemplateControlDefaultDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static TemplateControlDefault ConvertToDataModel(this TemplateControlDefaultDTO Me){
    		return new TemplateControlDefault() {
    
    			TemplateControlDefaultId = Me.TemplateControlDefaultId,
    			TemplateControlId = Me.TemplateControlId,
    			Text = Me.Text,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			IsPopular = Me.IsPopular
    		};
    	}
    
    	public static ICollection<TemplateControlDefault> ConvertToDataModel(this ICollection<TemplateControlDefaultDTO> Me)
    	{
    		ICollection<TemplateControlDefault> Result = new List<TemplateControlDefault>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
