//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class ValidationLibraryMapper
    {
    	public static ValidationLibraryDTO ConvertToDTO(this ValidationLibrary Me){
    		return new ValidationLibraryDTO() {
    
    			ValidationLibraryId = Me.ValidationLibraryId,
    			Name = Me.Name,
    			ErrorCodeId = Me.ErrorCodeId,
    			Expression = Me.Expression,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ErrorCode = Me.ErrorCode!=null?Me.ErrorCode.ConvertToDTO():null
    		};
    	}
    
    	public static ICollection<ValidationLibraryDTO> ConvertToDTO(this ICollection<ValidationLibrary> Me)
    	{
    		ICollection<ValidationLibraryDTO> Result = new List<ValidationLibraryDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static ValidationLibrary ConvertToDataModel(this ValidationLibraryDTO Me){
    		return new ValidationLibrary() {
    
    			ValidationLibraryId = Me.ValidationLibraryId,
    			Name = Me.Name,
    			ErrorCodeId = Me.ErrorCodeId,
    			Expression = Me.Expression,
    			IsEnabled = Me.IsEnabled,
    			CreatedDate = Me.CreatedDate,
    			CreatedBy = Me.CreatedBy,
    			UpdatedDate = Me.UpdatedDate,
    			UpdatedBy = Me.UpdatedBy,
    			ErrorCode = Me.ErrorCode!=null?Me.ErrorCode.ConvertToDataModel():null
    		};
    	}
    
    	public static ICollection<ValidationLibrary> ConvertToDataModel(this ICollection<ValidationLibraryDTO> Me)
    	{
    		ICollection<ValidationLibrary> Result = new List<ValidationLibrary>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
