//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class VW_EMSInstitutionTCPAMessagesMapper
    {
    	public static VW_EMSInstitutionTCPAMessagesDTO ConvertToDTO(this VW_EMSInstitutionTCPAMessages Me){
    		return new VW_EMSInstitutionTCPAMessagesDTO() {
    
    			InstitutionId = Me.InstitutionId,
    			TCPAMessage = Me.TCPAMessage
    		};
    	}
    
    	public static ICollection<VW_EMSInstitutionTCPAMessagesDTO> ConvertToDTO(this ICollection<VW_EMSInstitutionTCPAMessages> Me)
    	{
    		ICollection<VW_EMSInstitutionTCPAMessagesDTO> Result = new List<VW_EMSInstitutionTCPAMessagesDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static VW_EMSInstitutionTCPAMessages ConvertToDataModel(this VW_EMSInstitutionTCPAMessagesDTO Me){
    		return new VW_EMSInstitutionTCPAMessages() {
    
    			InstitutionId = Me.InstitutionId,
    			TCPAMessage = Me.TCPAMessage
    		};
    	}
    
    	public static ICollection<VW_EMSInstitutionTCPAMessages> ConvertToDataModel(this ICollection<VW_EMSInstitutionTCPAMessagesDTO> Me)
    	{
    		ICollection<VW_EMSInstitutionTCPAMessages> Result = new List<VW_EMSInstitutionTCPAMessages>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
