//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class VW_LandingPageSettingsMapper
    {
    	public static VW_LandingPageSettingsDTO ConvertToDTO(this VW_LandingPageSettings Me){
    		return new VW_LandingPageSettingsDTO() {
    
    			LandingPageId = Me.LandingPageId,
    			Directory = Me.Directory,
    			PageTitle = Me.PageTitle,
    			RenderingStrategyName = Me.RenderingStrategyName,
    			WizardFormTemplateId = Me.WizardFormTemplateId,
    			QDFFormTemplateId = Me.QDFFormTemplateId,
    			QDFPlacementToken = Me.QDFPlacementToken,
    			InstitutionId = Me.InstitutionId,
    			InstitutionName = Me.InstitutionName,
    			FormCustomAttributes = Me.FormCustomAttributes,
    			ShowArrowsInMobileHeader = Me.ShowArrowsInMobileHeader,
    			ShowSelectClearAllButton = Me.ShowSelectClearAllButton,
    			LandingPageTrackId = Me.LandingPageTrackId,
    			AllowsMinification = Me.AllowsMinification,
    			WebsiteId = Me.WebsiteId,
    			DomainName = Me.DomainName,
    			DirectoryRoot = Me.DirectoryRoot,
    			WebsiteTrackId = Me.WebsiteTrackId,
    			ApplicationId = Me.ApplicationId,
    			WebsiteJavascript = Me.WebsiteJavascript,
    			GoogleTagManagerId = Me.GoogleTagManagerId,
    			ABTestingCode = Me.ABTestingCode,
    			SelectAllSmartMatchTCPA = Me.SelectAllSmartMatchTCPA,
    			IsNewTCPAExperience = Me.IsNewTCPAExperience,
    			LoadJornayaFirstStep = Me.LoadJornayaFirstStep
    		};
    	}
    
    	public static ICollection<VW_LandingPageSettingsDTO> ConvertToDTO(this ICollection<VW_LandingPageSettings> Me)
    	{
    		ICollection<VW_LandingPageSettingsDTO> Result = new List<VW_LandingPageSettingsDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static VW_LandingPageSettings ConvertToDataModel(this VW_LandingPageSettingsDTO Me){
    		return new VW_LandingPageSettings() {
    
    			LandingPageId = Me.LandingPageId,
    			Directory = Me.Directory,
    			PageTitle = Me.PageTitle,
    			RenderingStrategyName = Me.RenderingStrategyName,
    			WizardFormTemplateId = Me.WizardFormTemplateId,
    			QDFFormTemplateId = Me.QDFFormTemplateId,
    			QDFPlacementToken = Me.QDFPlacementToken,
    			InstitutionId = Me.InstitutionId,
    			InstitutionName = Me.InstitutionName,
    			FormCustomAttributes = Me.FormCustomAttributes,
    			ShowArrowsInMobileHeader = Me.ShowArrowsInMobileHeader,
    			ShowSelectClearAllButton = Me.ShowSelectClearAllButton,
    			LandingPageTrackId = Me.LandingPageTrackId,
    			AllowsMinification = Me.AllowsMinification,
    			WebsiteId = Me.WebsiteId,
    			DomainName = Me.DomainName,
    			DirectoryRoot = Me.DirectoryRoot,
    			WebsiteTrackId = Me.WebsiteTrackId,
    			ApplicationId = Me.ApplicationId,
    			WebsiteJavascript = Me.WebsiteJavascript,
    			GoogleTagManagerId = Me.GoogleTagManagerId,
    			ABTestingCode = Me.ABTestingCode,
    			SelectAllSmartMatchTCPA = Me.SelectAllSmartMatchTCPA,
    			IsNewTCPAExperience = Me.IsNewTCPAExperience,
    			LoadJornayaFirstStep = Me.LoadJornayaFirstStep
    		};
    	}
    
    	public static ICollection<VW_LandingPageSettings> ConvertToDataModel(this ICollection<VW_LandingPageSettingsDTO> Me)
    	{
    		ICollection<VW_LandingPageSettings> Result = new List<VW_LandingPageSettings>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
