//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.Mapper
{
    using System;
    using EDDY.IS.FormsEngine.DataModel;
    using EDDY.IS.FormsEngine.DTO;
    using System.Collections.Generic;
    
    public  static class VW_ProspectResubmissionsMapper
    {
    	public static VW_ProspectResubmissionsDTO ConvertToDTO(this VW_ProspectResubmissions Me){
    		return new VW_ProspectResubmissionsDTO() {
    
    			SubmissionId = Me.SubmissionId,
    			ProspectId = Me.ProspectId,
    			RequestInput = Me.RequestInput,
    			State = Me.State,
    			Country = Me.Country,
    			DesiredStartDate = Me.DesiredStartDate,
    			Templateid = Me.Templateid,
    			CampaignTrackId = Me.CampaignTrackId,
    			MatchResponseGUID = Me.MatchResponseGUID,
    			TrackingSessionGuid = Me.TrackingSessionGuid
    		};
    	}
    
    	public static ICollection<VW_ProspectResubmissionsDTO> ConvertToDTO(this ICollection<VW_ProspectResubmissions> Me)
    	{
    		ICollection<VW_ProspectResubmissionsDTO> Result = new List<VW_ProspectResubmissionsDTO>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDTO());
    		}
    		return Result;
    	}
    	
    
    	public static VW_ProspectResubmissions ConvertToDataModel(this VW_ProspectResubmissionsDTO Me){
    		return new VW_ProspectResubmissions() {
    
    			SubmissionId = Me.SubmissionId,
    			ProspectId = Me.ProspectId,
    			RequestInput = Me.RequestInput,
    			State = Me.State,
    			Country = Me.Country,
    			DesiredStartDate = Me.DesiredStartDate,
    			Templateid = Me.Templateid,
    			CampaignTrackId = Me.CampaignTrackId,
    			MatchResponseGUID = Me.MatchResponseGUID,
    			TrackingSessionGuid = Me.TrackingSessionGuid
    		};
    	}
    
    	public static ICollection<VW_ProspectResubmissions> ConvertToDataModel(this ICollection<VW_ProspectResubmissionsDTO> Me)
    	{
    		ICollection<VW_ProspectResubmissions> Result = new List<VW_ProspectResubmissions>();
    		foreach (var item in Me)
    		{
    			Result.Add(item.ConvertToDataModel());
    		}
    		return Result;
    	}
    
    }
}
