using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EDDY.IS.LeadEngine.DTO;
using EDDY.IS.LeadEngine.DataModel;

namespace EDDY.IS.LeadEngine.Mapper
{
    public static partial class Converter
    {
        public static BetaLeadDTO ConvertToBetaLeadDTO(this BetaLead Me)
        {
            return new BetaLeadDTO()
            {

                LeadId = Me.LeadId,
                RawPostDataId = Me.RawPostDataId,
                SessionInternalId = Me.SessionInternalId,
                VisitorInternalId = Me.VisitorInternalId,
                FormUniqueId = Me.FormUniqueId,
                ChannelID = Me.ChannelID,
                VendorId = Me.VendorId,
                BusinessModelId = Me.BusinessModelId,
                ClientRelationshipId = Me.ClientRelationshipId,
                PSIId = Me.PSIId,
                ProgramProductId = Me.ProgramProductId,
                ProgramId = Me.ProgramId,
                ProgramTypeID = Me.ProgramTypeID,
                ProgramLevelID = Me.ProgramLevelID,
                ProductID = Me.ProductID,
                ApplicationID = Me.ApplicationID,
                CategoryId = Me.CategoryId,
                FirstName = Me.FirstName,
                MiddleName = Me.MiddleName,
                LastName = Me.LastName,
                Address1 = Me.Address1,
                Address2 = Me.Address2,
                City = Me.City,
                ZipCode = Me.ZipCode,
                StateProvince = Me.StateProvince,
                CountryCode = Me.CountryCode,
                EmailAddress = Me.EmailAddress,
                Phone1 = Me.Phone1,
                Phone2 = Me.Phone2,
                TimeToStartInWeeks = Me.TimeToStartInWeeks,
                AdditionalFields = Me.AdditionalFields,
                DeliveryDefinitionId = Me.DeliveryDefinitionId,
                RealtimeDeliveryStatusId = Me.RealtimeDeliveryStatusId,
                DeliveryEngineMachineKey = Me.DeliveryEngineMachineKey,
                IsEnabled = Me.IsEnabled,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                Prefix = Me.Prefix,
                Age = Me.Age,
                YearHighestEduCompleted = Me.YearHighestEduCompleted,
                HighestLevelOfEdu = Me.HighestLevelOfEdu,
                Military = Me.Military,
                MethodOfContact = Me.MethodOfContact,
                StartDate = Me.StartDate,
                LegacyLeadId = Me.LegacyLeadId,
                RowGuid = Me.RowGuid,
                TrackId = Me.TrackId,
                InitialLeadId = Me.InitialLeadId,
                CMID = Me.CMID,
                AffiliateId = Me.AffiliateId,
                UID = Me.UID,
                ExternalLeadId = Me.ExternalLeadId,
                Tsource = Me.Tsource,
                TrackingSessionGUID = Me.TrackingSessionGUID,
                DeliveryEngineMachineName = Me.DeliveryEngineMachineName,
                CampusApplicationId = Me.CampusApplicationId,
                CampusProgramId = Me.CampusProgramId,
                ClientCampusRelationshipId = Me.ClientCampusRelationshipId,
                InstitutionApplicationId = Me.InstitutionApplicationId,
                ProgramApplicationId = Me.ProgramApplicationId,
                CampusId = Me.CampusId,
                MatchResponseGuid = Me.MatchResponseGuid,
                SubmissionId = Me.SubmissionId,
                LeadCreationTypeId = Me.LeadCreationTypeId,
                ProspectId = Me.ProspectId,
                ClientRelationContactId = Me.ClientRelationContactId,
                ProspectFlowStatusHistoryId = Me.ProspectFlowStatusHistoryId,
                ChatIntegrationSessionId = Me.ChatIntegrationSessionId,
            };
        }
        
        public static BetaLead ConvertLeadTOToBetaDataModel(this LeadDTO Me)
        {
            return new BetaLead()
            {

                LeadId = Me.LeadId,
                RawPostDataId = Me.RawPostDataId,
                SessionInternalId = Me.SessionInternalId,
                VisitorInternalId = Me.VisitorInternalId,
                FormUniqueId = Me.FormUniqueId,
                ChannelID = Me.ChannelID,
                VendorId = Me.VendorId,
                BusinessModelId = Me.BusinessModelId,
                ClientRelationshipId = Me.ClientRelationshipId,
                PSIId = Me.PSIId,
                ProgramProductId = Me.ProgramProductId,
                ProgramId = Me.ProgramId,
                ProgramTypeID = Me.ProgramTypeID,
                ProgramLevelID = Me.ProgramLevelID,
                ProductID = Me.ProductID,
                ApplicationID = Me.ApplicationID,
                CategoryId = Me.CategoryId,
                FirstName = Me.FirstName,
                MiddleName = Me.MiddleName,
                LastName = Me.LastName,
                Address1 = Me.Address1,
                Address2 = Me.Address2,
                City = Me.City,
                ZipCode = Me.ZipCode,
                StateProvince = Me.StateProvince,
                CountryCode = Me.CountryCode,
                EmailAddress = Me.EmailAddress,
                Phone1 = Me.Phone1,
                Phone2 = Me.Phone2,
                TimeToStartInWeeks = Me.TimeToStartInWeeks,
                AdditionalFields = Me.AdditionalFields,
                DeliveryDefinitionId = Me.DeliveryDefinitionId,
                RealtimeDeliveryStatusId = Me.RealtimeDeliveryStatusId,
                DeliveryEngineMachineKey = Me.DeliveryEngineMachineKey,
                IsEnabled = Me.IsEnabled,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                Prefix = Me.Prefix,
                Age = Me.Age,
                YearHighestEduCompleted = Me.YearHighestEduCompleted,
                HighestLevelOfEdu = Me.HighestLevelOfEdu,
                Military = Me.Military,
                MethodOfContact = Me.MethodOfContact,
                StartDate = Me.StartDate,
                LegacyLeadId = Me.LegacyLeadId,
                RowGuid = Me.RowGuid,
                TrackId = Me.TrackId,
                InitialLeadId = Me.InitialLeadId,
                CMID = Me.CMID,
                AffiliateId = Me.AffiliateId,
                UID = Me.UID,
                ExternalLeadId = Me.ExternalLeadId,
                Tsource = Me.Tsource,
                TrackingSessionGUID = Me.TrackingSessionGUID,
                DeliveryEngineMachineName = Me.DeliveryEngineMachineName,
                CampusApplicationId = Me.CampusApplicationId,
                CampusProgramId = Me.CampusProgramId,
                ClientCampusRelationshipId = Me.ClientCampusRelationshipId,
                InstitutionApplicationId = Me.InstitutionApplicationId,
                ProgramApplicationId = Me.ProgramApplicationId,
                CampusId = Me.CampusId,
                MatchResponseGuid = Me.MatchResponseGuid,
                SubmissionId = Me.SubmissionId,
                LeadCreationTypeId = Me.LeadCreationTypeId,
                ProspectId = Me.ProspectId,
                ClientRelationContactId = Me.ClientRelationContactId,
                ProspectFlowStatusHistoryId = Me.ProspectFlowStatusHistoryId,
                ChatIntegrationSessionId = Me.ChatIntegrationSessionId
            };
        }

        public static LeadDTO ConvertToLeadDTO(this Lead Me)
        {
            return new LeadDTO()
            {

                LeadId = Me.LeadId,
                RawPostDataId = Me.RawPostDataId,
                SessionInternalId = Me.SessionInternalId,
                VisitorInternalId = Me.VisitorInternalId,
                FormUniqueId = Me.FormUniqueId,
                ChannelID = Me.ChannelID,
                VendorId = Me.VendorId,
                BusinessModelId = Me.BusinessModelId,
                ClientRelationshipId = Me.ClientRelationshipId,
                PSIId = Me.PSIId,
                ProgramInstanceID = Me.ProgramInstanceID,
                ProgramId = Me.ProgramId,
                ProgramTypeID = Me.ProgramTypeID,
                ProgramLevelID = Me.ProgramLevelID,
                ProductID = Me.ProductID,
                ApplicationID = Me.ApplicationID,
                CategoryId = Me.CategoryId,
                FirstName = Me.FirstName,
                MiddleName = Me.MiddleName,
                LastName = Me.LastName,
                Address1 = Me.Address1,
                Address2 = Me.Address2,
                City = Me.City,
                ZipCode = Me.ZipCode,
                StateProvince = Me.StateProvince,
                CountryCode = Me.CountryCode,
                EmailAddress = Me.EmailAddress,
                Phone1 = Me.Phone1,
                Phone2 = Me.Phone2,
                TimeToStartInWeeks = Me.TimeToStartInWeeks,
                AdditionalFields = Me.AdditionalFields,
                DeliveryDefinitionId = Me.DeliveryDefinitionId,
                RealtimeDeliveryStatusId = Me.RealtimeDeliveryStatusId,
                DeliveryEngineMachineKey = Me.DeliveryEngineMachineKey,
                IsEnabled = Me.IsEnabled,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                RowGuid = Me.RowGuid,
                Prefix = Me.Prefix,
                Age = Me.Age,
                YearHighestEduCompleted = Me.YearHighestEduCompleted,
                HighestLevelOfEdu = Me.HighestLevelOfEdu,
                Military = Me.Military,
                MethodOfContact = Me.MethodOfContact,
                StartDate = Me.StartDate,
                LegacyLeadId = Me.LegacyLeadId,
                TrackId = Me.TrackId,
                InitialLeadId = Me.InitialLeadId,
                CMID = Me.CMID,
                AffiliateId = Me.AffiliateId,
                UID = Me.UID,
                ExternalLeadId = Me.ExternalLeadId,
                Tsource = Me.Tsource,
                TrackingSessionGUID = Me.TrackingSessionGUID,
                DeliveryEngineMachineName = Me.DeliveryEngineMachineName,
                CampusId = Me.CampusId,
                CampusApplicationId = Me.CampusApplicationId,
                CampusProgramId = Me.CampusProgramId,
                ClientCampusRelationshipId = Me.ClientCampusRelationshipId,
                InstitutionApplicationId = Me.InstitutionApplicationId,
                ProgramApplicationId = Me.ProgramApplicationId,
                ProgramProductId = Me.ProgramProductId,
                IsCapProcessed = Me.IsCapProcessed,
                CapProcessDate = Me.CapProcessDate,
                IsCallCenter = Me.IsCallCenter,
                MatchResponseGuid = Me.MatchResponseGuid,
                SubmissionId = Me.SubmissionId,
                LeadCreationTypeId = Me.LeadCreationTypeId,
                ProspectId = Me.ProspectId,
                ClientRelationContactId = Me.ClientRelationContactId,
                ProspectFlowStatusHistoryId = Me.ProspectFlowStatusHistoryId,
                ChatIntegrationSessionId = Me.ChatIntegrationSessionId,
                AllowedViaLeadScoringUpsell = Me.AllowedViaLeadScoringUpsell,
                ExternalMatchItemGuid = Me.ExternalMatchItemGuid,
                PlacementViewGuid = Me.PlacementViewGuid
            };
        }
        
        public static Lead ConvertLeadToDataModel(this LeadDTO Me)
        {
            return new Lead()
            {

                LeadId = Me.LeadId,
                RawPostDataId = Me.RawPostDataId,
                SessionInternalId = Me.SessionInternalId,
                VisitorInternalId = Me.VisitorInternalId,
                FormUniqueId = Me.FormUniqueId,
                ChannelID = Me.ChannelID,
                VendorId = Me.VendorId,
                BusinessModelId = Me.BusinessModelId,
                ClientRelationshipId = Me.ClientRelationshipId,
                PSIId = Me.PSIId,
                ProgramInstanceID = Me.ProgramInstanceID,
                ProgramId = Me.ProgramId,
                ProgramTypeID = Me.ProgramTypeID,
                ProgramLevelID = Me.ProgramLevelID,
                ProductID = Me.ProductID,
                ApplicationID = Me.ApplicationID,
                CategoryId = Me.CategoryId,
                FirstName = Me.FirstName,
                MiddleName = Me.MiddleName,
                LastName = Me.LastName,
                Address1 = Me.Address1,
                Address2 = Me.Address2,
                City = Me.City,
                ZipCode = Me.ZipCode,
                StateProvince = Me.StateProvince,
                CountryCode = Me.CountryCode,
                EmailAddress = Me.EmailAddress,
                Phone1 = Me.Phone1,
                Phone2 = Me.Phone2,
                TimeToStartInWeeks = Me.TimeToStartInWeeks,
                AdditionalFields = Me.AdditionalFields,
                DeliveryDefinitionId = Me.DeliveryDefinitionId,
                RealtimeDeliveryStatusId = Me.RealtimeDeliveryStatusId,
                DeliveryEngineMachineKey = Me.DeliveryEngineMachineKey,
                IsEnabled = Me.IsEnabled,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                RowGuid = Me.RowGuid,
                Prefix = Me.Prefix,
                Age = Me.Age,
                YearHighestEduCompleted = Me.YearHighestEduCompleted,
                HighestLevelOfEdu = Me.HighestLevelOfEdu,
                Military = Me.Military,
                MethodOfContact = Me.MethodOfContact,
                StartDate = Me.StartDate,
                LegacyLeadId = Me.LegacyLeadId,
                TrackId = Me.TrackId,
                InitialLeadId = Me.InitialLeadId,
                CMID = Me.CMID,
                AffiliateId = Me.AffiliateId,
                UID = Me.UID,
                ExternalLeadId = Me.ExternalLeadId,
                Tsource = Me.Tsource,
                TrackingSessionGUID = Me.TrackingSessionGUID,
                DeliveryEngineMachineName = Me.DeliveryEngineMachineName,
                CampusId = Me.CampusId,
                CampusApplicationId = Me.CampusApplicationId,
                CampusProgramId = Me.CampusProgramId,
                ClientCampusRelationshipId = Me.ClientCampusRelationshipId,
                InstitutionApplicationId = Me.InstitutionApplicationId,
                ProgramApplicationId = Me.ProgramApplicationId,
                ProgramProductId = Me.ProgramProductId,
                IsCapProcessed = Me.IsCapProcessed,
                CapProcessDate = Me.CapProcessDate,
                IsCallCenter = Me.IsCallCenter,
                MatchResponseGuid = Me.MatchResponseGuid,
                SubmissionId = Me.SubmissionId,
                LeadCreationTypeId = Me.LeadCreationTypeId,
                ProspectId = Me.ProspectId,
                ClientRelationContactId = Me.ClientRelationContactId,
                ProspectFlowStatusHistoryId = Me.ProspectFlowStatusHistoryId,
                ChatIntegrationSessionId = Me.ChatIntegrationSessionId,
                PaidStatusTypeId = Me.PaidStatusTypeId,
                AllowedViaLeadScoringUpsell = Me.AllowedViaLeadScoringUpsell,
                ExternalMatchItemGuid = Me.ExternalMatchItemGuid,
                UnaudittedRevenue = Me.UnaudittedRevenue,
                EstimatedRevShare = Me.EstimatedRevShare,
                PlacementViewGuid = Me.PlacementViewGuid,
                EstimatedLeadRev = Me.EstimatedLeadRev,
                LeadPingScoreId = Me.ScoreId
            };
        }

        public static RawPostDataDTO ConvertRPDToDTO(this RawPostData Me)
        {
            return new RawPostDataDTO()
            {

                RawPostDataID = Me.RawPostDataID,
                RemoteIp = Me.RemoteIp,
                BrowserInfo = Me.BrowserInfo,
                Referer = Me.Referer,
                PostData = Me.PostData,
                TransactionId = Me.TransactionId,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                RowGuid = Me.RowGuid
            };
        }

        public static RawPostData ConvertToRPDDataModel(this RawPostDataDTO Me)
        {
            return new RawPostData()
            {

                RawPostDataID = Me.RawPostDataID,
                RemoteIp = Me.RemoteIp,
                BrowserInfo = Me.BrowserInfo,
                Referer = Me.Referer,
                PostData = Me.PostData,
                TransactionId = Me.TransactionId,
                CreatedDate = Me.CreatedDate,
                CreatedBy = Me.CreatedBy,
                UpdatedDate = Me.UpdatedDate,
                UpdatedBy = Me.UpdatedBy,
                RowGuid = Me.RowGuid
            };
        }
    }
}
