//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDDY.IS.FormsEngine.PixelsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PixelsService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPixelsWithMultipleTypes", ReplyAction="http://tempuri.org/IService/GetPixelsWithMultipleTypesResponse")]
        string GetPixelsWithMultipleTypes(string TrackID, string[] Types, int ProspectID, int[] LeadIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPixelsWithMultipleTypes", ReplyAction="http://tempuri.org/IService/GetPixelsWithMultipleTypesResponse")]
        System.Threading.Tasks.Task<string> GetPixelsWithMultipleTypesAsync(string TrackID, string[] Types, int ProspectID, int[] LeadIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPixels", ReplyAction="http://tempuri.org/IService/GetPixelsResponse")]
        string GetPixels(string TrackID, string Type, int ProspectID, int[] LeadIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetPixels", ReplyAction="http://tempuri.org/IService/GetPixelsResponse")]
        System.Threading.Tasks.Task<string> GetPixelsAsync(string TrackID, string Type, int ProspectID, int[] LeadIDs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : EDDY.IS.FormsEngine.PixelsService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<EDDY.IS.FormsEngine.PixelsService.IService>, EDDY.IS.FormsEngine.PixelsService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPixelsWithMultipleTypes(string TrackID, string[] Types, int ProspectID, int[] LeadIDs) {
            return base.Channel.GetPixelsWithMultipleTypes(TrackID, Types, ProspectID, LeadIDs);
        }
        
        public System.Threading.Tasks.Task<string> GetPixelsWithMultipleTypesAsync(string TrackID, string[] Types, int ProspectID, int[] LeadIDs) {
            return base.Channel.GetPixelsWithMultipleTypesAsync(TrackID, Types, ProspectID, LeadIDs);
        }
        
        public string GetPixels(string TrackID, string Type, int ProspectID, int[] LeadIDs) {
            return base.Channel.GetPixels(TrackID, Type, ProspectID, LeadIDs);
        }
        
        public System.Threading.Tasks.Task<string> GetPixelsAsync(string TrackID, string Type, int ProspectID, int[] LeadIDs) {
            return base.Channel.GetPixelsAsync(TrackID, Type, ProspectID, LeadIDs);
        }
    }
}
